//! EFM32GG (Giant Gecko) family support.
//!
//! Adding another Gecko family (efm32pg, efm32hg, efm32lg, ...) means adding a sibling
//! `chips/efm32xx.rs` module following this same shape, its chip data in `build.rs`, and wiring
//! both up next to the `_efm32gg` ones in `src/lib.rs` and `build.rs`.

// Re-export the PAC for whichever specific die feature is enabled. `build.rs` checks that exactly
// one `efm32ggXXX` feature is.
#[cfg(feature = "efm32gg230")]
pub use efm32gg_pac::efm32gg230 as pac;
#[cfg(feature = "efm32gg232")]
pub use efm32gg_pac::efm32gg232 as pac;
#[cfg(feature = "efm32gg280")]
pub use efm32gg_pac::efm32gg280 as pac;
#[cfg(feature = "efm32gg290")]
pub use efm32gg_pac::efm32gg290 as pac;
#[cfg(feature = "efm32gg295")]
pub use efm32gg_pac::efm32gg295 as pac;
#[cfg(feature = "efm32gg330")]
pub use efm32gg_pac::efm32gg330 as pac;
#[cfg(feature = "efm32gg332")]
pub use efm32gg_pac::efm32gg332 as pac;
#[cfg(feature = "efm32gg380")]
pub use efm32gg_pac::efm32gg380 as pac;
#[cfg(feature = "efm32gg390")]
pub use efm32gg_pac::efm32gg390 as pac;
#[cfg(feature = "efm32gg395")]
pub use efm32gg_pac::efm32gg395 as pac;
#[cfg(feature = "efm32gg840")]
pub use efm32gg_pac::efm32gg840 as pac;
#[cfg(feature = "efm32gg842")]
pub use efm32gg_pac::efm32gg842 as pac;
#[cfg(feature = "efm32gg880")]
pub use efm32gg_pac::efm32gg880 as pac;
#[cfg(feature = "efm32gg890")]
pub use efm32gg_pac::efm32gg890 as pac;
#[cfg(feature = "efm32gg895")]
pub use efm32gg_pac::efm32gg895 as pac;
#[cfg(feature = "efm32gg900")]
pub use efm32gg_pac::efm32gg900 as pac;
#[cfg(feature = "efm32gg940")]
pub use efm32gg_pac::efm32gg940 as pac;
#[cfg(feature = "efm32gg942")]
pub use efm32gg_pac::efm32gg942 as pac;
#[cfg(feature = "efm32gg980")]
pub use efm32gg_pac::efm32gg980 as pac;
#[cfg(feature = "efm32gg990")]
pub use efm32gg_pac::efm32gg990 as pac;
#[cfg(feature = "efm32gg995")]
pub use efm32gg_pac::efm32gg995 as pac;

use crate::cmu::{Clocks, Config, HfrcoBand};
use crate::time::Hertz;

// The peripheral singletons, interrupts, and GPIO and USART pin trait impls for the selected chip,
// generated by `build.rs` from its chip data.
include!(concat!(env!("OUT_DIR"), "/_generated.rs"));

// Clock tree (CMU), used by `crate::cmu`.

#[inline]
fn cmu() -> &'static pac::cmu::RegisterBlock {
    unsafe { &*pac::CMU::ptr() }
}

// The device information page (`DEVINFO`), which holds factory data. `efm32gg-pac` doesn't
// describe it, so the layout below is from Silicon Labs' `efm32gg_devinfo.h`.

/// Base address of the device information page.
const DEVINFO_BASE: usize = 0x0FE0_81B0;
/// `DEVINFO->HFRCOCAL0`: the HFRCO `TUNING` values for the 1, 7, 11 and 14 MHz bands, one byte
/// each, lowest band first.
const DEVINFO_HFRCOCAL0: usize = 0x2C;
/// `DEVINFO->HFRCOCAL1`: the HFRCO `TUNING` values for the 21 and 28 MHz bands.
const DEVINFO_HFRCOCAL1: usize = 0x30;
/// `DEVINFO->PART`: the production revision is in bits 31:24.
const DEVINFO_PART: usize = 0x4C;

fn devinfo_read(offset: usize) -> u32 {
    unsafe { ((DEVINFO_BASE + offset) as *const u32).read_volatile() }
}

/// The production revision (`DEVINFO->PART`), which several errata depend on.
fn prod_rev() -> u8 {
    (devinfo_read(DEVINFO_PART) >> 24) as u8
}

// The chip revision is in the Cortex-M ROM table's peripheral ID registers. The layout is from
// Silicon Labs' `efm32gg_romtable.h` and `SYSTEM_ChipRevisionGet`.

/// Base address of the ROM table's peripheral ID registers.
const ROMTABLE_BASE: usize = 0xE00F_FFD0;
/// `PID0`: the major revision is in bits 5:0.
const ROMTABLE_PID0: usize = 0x10;
/// `PID2`: bits 7:4 are bits 7:4 of the minor revision.
const ROMTABLE_PID2: usize = 0x18;
/// `PID3`: bits 7:4 are bits 3:0 of the minor revision.
const ROMTABLE_PID3: usize = 0x1C;

/// The chip revision, as `(major, minor)`.
fn chip_rev() -> (u8, u8) {
    let pid = |offset: usize| unsafe { ((ROMTABLE_BASE + offset) as *const u32).read_volatile() };
    let major = (pid(ROMTABLE_PID0) & 0x3F) as u8;
    let minor = ((pid(ROMTABLE_PID2) & 0xF0) | ((pid(ROMTABLE_PID3) & 0xF0) >> 4)) as u8;
    (major, minor)
}

/// Errata CMU_E113, "LFXO Startup at High Temperature": from production revision 16 on, the LFXO
/// may not start with low capacitance crystals at high temperatures.
///
/// This is the fix from Silicon Labs' `CHIP_Init()` (`em_chip.h`), which embassy applications don't
/// run, with the same condition. It sets bits in a CMU register the reference manual doesn't
/// document (and the PAC doesn't describe), at CMU offset 0xC0.
fn apply_errata_cmu_e113() {
    let (major, minor) = chip_rev();
    // `CHIP_Init` excludes chip revision 2.4, which is a Leopard Gecko revision.
    if prod_rev() >= 16 && minor >= 3 && !(major == 2 && minor == 4) {
        let reg = (pac::CMU::PTR as usize + 0xC0) as *mut u32;
        unsafe { reg.write_volatile((reg.read_volatile() & !(1 << 6)) | (1 << 4)) };
    }
}

/// Factory HFRCO `TUNING` value for `band`.
fn hfrco_tuning(band: HfrcoBand) -> u8 {
    let (offset, shift) = match band {
        HfrcoBand::Band1Mhz => (DEVINFO_HFRCOCAL0, 0),
        HfrcoBand::Band7Mhz => (DEVINFO_HFRCOCAL0, 8),
        HfrcoBand::Band11Mhz => (DEVINFO_HFRCOCAL0, 16),
        HfrcoBand::Band14Mhz => (DEVINFO_HFRCOCAL0, 24),
        HfrcoBand::Band21Mhz => (DEVINFO_HFRCOCAL1, 0),
        HfrcoBand::Band28Mhz => (DEVINFO_HFRCOCAL1, 8),
    };
    (devinfo_read(offset) >> shift) as u8
}

/// The frequency of an HFRCO band, running with its factory `TUNING` value.
///
/// From production revision 19 on, the 7 and 1 MHz bands run at 6.6 and 1.2 MHz (data sheet,
/// HFRCO table). This is the same distinction as emlib's `SystemHFClockGet`.
fn hfrco_frequency(band: HfrcoBand) -> Hertz {
    let prod_rev = prod_rev();
    match band {
        HfrcoBand::Band1Mhz if prod_rev >= 19 => Hertz::khz(1200),
        HfrcoBand::Band1Mhz => Hertz::mhz(1),
        HfrcoBand::Band7Mhz if prod_rev >= 19 => Hertz::khz(6600),
        HfrcoBand::Band7Mhz => Hertz::mhz(7),
        HfrcoBand::Band11Mhz => Hertz::mhz(11),
        HfrcoBand::Band14Mhz => Hertz::mhz(14),
        HfrcoBand::Band21Mhz => Hertz::mhz(21),
        HfrcoBand::Band28Mhz => Hertz::mhz(28),
    }
}

/// HFRCO settling time after a band switch, in core cycles: 25 HFRCO cycles (data sheet, HFRCO
/// table) at the slowest band (1 MHz), with the core at the family's fastest 48 MHz.
const HFRCO_SETTLE_CORE_CYCLES: u32 = 25 * 48;

/// Set the flash wait states for the given `HFCORECLK` frequency: 0 up to 16 MHz, 1 up to 32 MHz,
/// 2 above (up to the family's 48 MHz maximum).
fn set_flash_wait_states(hfcoreclk: u32) {
    let msc = unsafe { &*pac::MSC::ptr() };
    msc.readctrl.modify(|_, w| match hfcoreclk {
        0..=16_000_000 => w.mode().ws0(),
        16_000_001..=32_000_000 => w.mode().ws1(),
        _ => w.mode().ws2(),
    });
}

/// Configure the clock tree, returning the resulting frequencies.
pub(crate) fn init_clocks(config: &Config) -> Clocks {
    let r = cmu();

    // Don't assume the clock tree is at its reset state: a bootloader may have run first, and
    // left e.g. the HFXO selected as HFCLK, other prescalers, or other flash wait states. This
    // follows emlib's `CMU_HFRCOBandSet`/`CMU_ClockSelectSet`.

    apply_errata_cmu_e113();

    // Worst case wait states while the frequency changes.
    set_flash_wait_states(u32::MAX);

    r.oscencmd.write(|w| w.hfrcoen().set_bit());
    while r.status.read().hfrcordy().bit_is_clear() {}

    // Errata CMU_E115, "HFRCO 1 MHz Band Switching": switching to or from the 1 MHz band while the
    // HFRCO clocks the core can glitch the clock and hard fault, even with the maximum wait states.
    // The workaround is to run from the LFRCO during the switch.
    let status = r.status.read();
    let detour = status.hfrcosel().bit_is_set()
        && (config.hfrco_band == HfrcoBand::Band1Mhz || r.hfrcoctrl.read().band().is_1mhz());
    let lfrco_was_enabled = status.lfrcoens().bit_is_set();
    if detour {
        r.oscencmd.write(|w| w.lfrcoen().set_bit());
        while r.status.read().lfrcordy().bit_is_clear() {}
        r.cmd.write(|w| w.hfclksel().lfrco());
        while r.status.read().lfrcosel().bit_is_clear() {}
    }

    let tuning = hfrco_tuning(config.hfrco_band);
    r.hfrcoctrl.modify(|_, w| {
        let w = unsafe { w.tuning().bits(tuning) };
        match config.hfrco_band {
            HfrcoBand::Band1Mhz => w.band()._1mhz(),
            HfrcoBand::Band7Mhz => w.band()._7mhz(),
            HfrcoBand::Band11Mhz => w.band()._11mhz(),
            HfrcoBand::Band14Mhz => w.band()._14mhz(),
            HfrcoBand::Band21Mhz => w.band()._21mhz(),
            HfrcoBand::Band28Mhz => w.band()._28mhz(),
        }
    });

    // Let the HFRCO settle on the new frequency before anything depends on it (reference manual,
    // 7.3.4.1), then wait for `HFRCORDY`. The core may run from a faster clock meanwhile (a
    // bootloader's HFXO), so the delay is sized for the fastest core clock and slowest band. On
    // the LFRCO detour, a single core cycle already outlasts the settling time.
    if !detour {
        // Not `cortex_m::asm::delay`: its code needs an 8-byte aligned `.text`, which the linker
        // warns about with this family's vector table size. Each iteration takes at least a cycle.
        for _ in 0..HFRCO_SETTLE_CORE_CYCLES {
            cortex_m::asm::nop();
        }
    }
    while r.status.read().hfrcordy().bit_is_clear() {}

    r.cmd.write(|w| w.hfclksel().hfrco());
    while r.status.read().hfrcosel().bit_is_clear() {}

    if detour && !lfrco_was_enabled {
        r.oscencmd.write(|w| w.lfrcodis().set_bit());
    }

    // HFCLK = HFRCO, HFCORECLK = HFPERCLK = HFCLK. The LE interface clock is HFCORECLK / 2
    // (`HFLE` clear): `HFLE` is only needed with HFCORECLK above 32 MHz (reference manual, table
    // 11.1), and the HFRCO tops out at 28 MHz. This is only done now that HFCLK runs from the
    // HFRCO: a bootloader running at up to 48 MHz may need `HFLE` set until then.
    r.ctrl.modify(|_, w| unsafe { w.hfclkdiv().bits(0) }.hfle().clear_bit());
    r.hfcoreclkdiv
        .write(|w| w.hfcoreclkdiv().hfclk().hfcoreclklediv().clear_bit());
    r.hfperclkdiv.write(|w| w.hfperclkdiv().hfclk().hfperclken().set_bit());

    let hfclk = hfrco_frequency(config.hfrco_band);
    set_flash_wait_states(hfclk.0);

    // Nothing in the HAL uses the HFXO: stop it if a bootloader left it running.
    if r.status.read().hfxoens().bit_is_set() {
        r.oscencmd.write(|w| w.hfxodis().set_bit());
    }

    // The LFXO pins are GPIOs: stop the LFXO if a bootloader left it running on them.
    #[cfg(feature = "lfxo-as-gpio")]
    if r.status.read().lfxoens().bit_is_set() {
        r.oscencmd.write(|w| w.lfxodis().set_bit());
    }

    // GPIO is always enabled: it's needed unconditionally by `crate::gpio`.
    r.hfperclken0.modify(|_, w| w.gpio().set_bit());

    #[cfg(feature = "_time-driver")]
    init_lfclk(config.lfa_source);

    Clocks { hfclk, hfperclk: hfclk }
}

/// Bring up the low-frequency oscillator and route it to the `LFA` branch, which clocks the RTC.
#[cfg(feature = "_time-driver")]
fn init_lfclk(source: crate::cmu::LfClockSource) {
    use crate::cmu::LfClockSource;

    let r = cmu();

    // Also clear `LFAE`, which overrides `LFA` with the 1 kHz ULFRCO when set. Neither this nor
    // the RTC prescaler below can be assumed to be at their reset value, since a bootloader may
    // have run before us.
    match source {
        LfClockSource::Lfrco => {
            r.oscencmd.write(|w| w.lfrcoen().set_bit());
            while r.status.read().lfrcordy().bit_is_clear() {}
            r.lfclksel.modify(|_, w| w.lfa().lfrco().lfae().clear_bit());
        }
        #[cfg(not(feature = "lfxo-as-gpio"))]
        LfClockSource::Lfxo => {
            // The LFXO settings: crystal mode, 70% start-up boost, 16k cycle timeout, and the boost
            // buffer current off, as errata CMU_E112 requires. Before production revision 15, the
            // buffer current is on instead, per errata CMU_E111 (those parts' reset values are
            // wrong). Applied in case the reset values or a bootloader left something else, and
            // only with the LFXO stopped.
            let bufcur = prod_rev() < 15;
            let ctrl = r.ctrl.read();
            let configured = ctrl.lfxomode().is_xtal()
                && ctrl.lfxoboost().bit_is_clear()
                && ctrl.lfxobufcur().bit() == bufcur
                && ctrl.lfxotimeout().is_16kcycles();
            if !configured {
                r.oscencmd.write(|w| w.lfxodis().set_bit());
                while r.status.read().lfxoens().bit_is_set() {}
                r.ctrl.modify(|_, w| {
                    w.lfxomode()
                        .xtal()
                        .lfxoboost()
                        .clear_bit()
                        .lfxobufcur()
                        .bit(bufcur)
                        .lfxotimeout()
                        ._16kcycles()
                });
            }

            // `LFXORDY` is only set once the crystal has stabilized (after `CTRL.LFXOTIMEOUT`
            // cycles, 16k, i.e. about 0.5 s).
            r.oscencmd.write(|w| w.lfxoen().set_bit());
            while r.status.read().lfxordy().bit_is_clear() {}
            r.lfclksel.modify(|_, w| w.lfa().lfxo().lfae().clear_bit());
        }
    }

    // The RTC (and other low-energy peripherals) additionally need the `HFCORECLK LE` interface
    // clock to be enabled to be accessible at all.
    r.hfcoreclken0.modify(|_, w| w.le().set_bit());

    while r.syncbusy.read().lfapresc0().bit_is_set() {}
    r.lfapresc0.modify(|_, w| w.rtc().div1());
    while r.syncbusy.read().lfapresc0().bit_is_set() {}

    // Like `LFAPRESC0`, `LFACLKEN0` is synchronized into the LF domain: wait for a previous
    // write to complete first, as emlib's `CMU_ClockEnable` does.
    while r.syncbusy.read().lfaclken0().bit_is_set() {}
    r.lfaclken0.modify(|_, w| w.rtc().set_bit());
}

/// A `HFPERCLK` peripheral clock gate, in `CMU_HFPERCLKEN0`.
#[derive(Debug, Clone, Copy, Eq, PartialEq)]
#[allow(clippy::upper_case_acronyms)]
pub(crate) enum PeripheralClock {
    USART0,
    USART1,
    USART2,
    #[cfg(feature = "_uart")]
    UART0,
    #[cfg(feature = "_uart")]
    UART1,
}

pub(crate) fn set_peripheral_clock(clock: PeripheralClock, enabled: bool) {
    critical_section::with(|_| {
        cmu().hfperclken0.modify(|_, w| match clock {
            PeripheralClock::USART0 => w.usart0().bit(enabled),
            PeripheralClock::USART1 => w.usart1().bit(enabled),
            PeripheralClock::USART2 => w.usart2().bit(enabled),
            #[cfg(feature = "_uart")]
            PeripheralClock::UART0 => w.uart0().bit(enabled),
            #[cfg(feature = "_uart")]
            PeripheralClock::UART1 => w.uart1().bit(enabled),
        })
    });
}
