[package]
name = "embassy-usb-synopsys-otg"
version = "0.4.0"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "`embassy-usb-driver` implementation for Synopsys OTG USB controllers"
keywords = ["embedded", "async", "usb", "hal", "embedded-hal"]
categories = ["embedded", "hardware-support", "no-std", "asynchronous"]
repository = "https://github.com/embassy-rs/embassy"
documentation = "https://docs.embassy.dev/embassy-usb-synopsys-otg"

[package.metadata.embassy]
build = [
    {target = "thumbv7m-none-eabi", features = ["defmt"]},
    {target = "thumbv7m-none-eabi", features = ["log"]},
    {target = "thumbv7m-none-eabi", features = ["defmt", "embassy-time"]},
    {target = "thumbv7m-none-eabi", features = ["log", "embassy-time"]},
    {target = "thumbv7m-none-eabi", features = ["defmt", "host"]},
    {target = "thumbv7m-none-eabi", features = ["log", "host"]},
    # Xtensa builds
    {group = "xtensa", build-std = ["core", "alloc"], target = "xtensa-esp32s2-none-elf", features = ["portable-atomic/critical-section", "defmt"]},
    {group = "xtensa", build-std = ["core", "alloc"], target = "xtensa-esp32s2-none-elf", features = ["portable-atomic/critical-section", "log"]},
    {group = "xtensa", build-std = ["core", "alloc"], target = "xtensa-esp32s2-none-elf", features = ["portable-atomic/critical-section", "defmt", "embassy-time"]},
    {group = "xtensa", build-std = ["core", "alloc"], target = "xtensa-esp32s2-none-elf", features = ["portable-atomic/critical-section", "log", "embassy-time"]},
    {group = "xtensa", build-std = ["core", "alloc"], target = "xtensa-esp32s2-none-elf", features = ["portable-atomic/critical-section", "defmt", "host"]},
    {group = "xtensa", build-std = ["core", "alloc"], target = "xtensa-esp32s2-none-elf", features = ["portable-atomic/critical-section", "log", "host"]},
]

[package.metadata.embassy_docs]
src_base = "https://github.com/embassy-rs/embassy/blob/embassy-usb-synopsys-otg-v$VERSION/embassy-usb-synopsys-otg/src/"
src_base_git = "https://github.com/embassy-rs/embassy/blob/$COMMIT/embassy-usb-synopsys-otg/src/"
features = ["defmt"]
target = "thumbv7em-none-eabi"

[dependencies]
portable-atomic = { version = "1" }

document-features = "0.2.7"

embassy-sync = { version = "0.8.0", path = "../embassy-sync" }
embassy-time = { version = "0.5.1", path = "../embassy-time", optional = true }
embassy-usb-driver = { version = "0.2.2", path = "../embassy-usb-driver" }

defmt = { version = "1.0.1", optional = true }
log = { version = "0.4.14", optional = true }

[features]
default = []
defmt = ["dep:defmt", "embassy-usb-driver/defmt"]
log = ["dep:log"]

## Enables USB host mode support.
host = ["embassy-time"]

## Enables remote wakeup support in device mode.
embassy-time = ["dep:embassy-time"]
