//! Wake-Up Unit (WUU) driver.
//!
//! Configures one external pin, internal module interrupt, or internal
//! DMA/trigger request and returns a guard that keeps the source armed.

use embassy_hal_internal::{Peri, PeripheralType};

use crate::gpio::{GpioPin, Input, Pull};
use crate::interrupt::InterruptExt;
use crate::interrupt::typelevel::{Binding, Handler};
use crate::pac::wuu::{Wupdc, Wupe, Wupmc};
use crate::{interrupt, pac, peripherals};

/// WUU initialization error.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub enum Error {
    /// The `clk_16k[0]` low-power clock required by WUU is not active.
    ClockUnavailable,
}

/// External wake detection condition.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub enum Edge {
    /// Detect a rising edge or high level.
    Rising,
    /// Detect a falling edge or low level.
    Falling,
    /// Detect either edge.
    Any,
}

impl From<Edge> for Wupe {
    fn from(value: Edge) -> Self {
        match value {
            Edge::Rising => Self::EnRiseHi,
            Edge::Falling => Self::EnFallLo,
            Edge::Any => Self::EnAny,
        }
    }
}

/// Event generated by an external wake pin.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub enum Event {
    /// Generate a WUU interrupt.
    Interrupt,
    /// Generate a DMA request.
    DmaRequest,
    /// Generate a trigger event.
    Trigger,
}

impl From<Event> for Wupdc {
    fn from(value: Event) -> Self {
        match value {
            Event::Interrupt => Self::Interrupt,
            Event::DmaRequest => Self::DmaReq,
            Event::Trigger => Self::Trigger,
        }
    }
}

/// Power modes in which an external wake pin remains active.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub enum PinMode {
    /// Enable detection only while the device is in a low-leakage mode.
    LowPowerOnly,
    /// Enable detection in active and low-leakage modes.
    AnyPower,
}

impl From<PinMode> for Wupmc {
    fn from(value: PinMode) -> Self {
        match value {
            PinMode::LowPowerOnly => Self::LowPwrOnly,
            PinMode::AnyPower => Self::AnyPwr,
        }
    }
}

/// External wake pin configuration.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct ExternalPinConfig {
    /// Detection condition.
    pub edge: Edge,
    /// Event generated when the condition is detected.
    pub event: Event,
    /// Power modes in which detection remains active.
    pub mode: PinMode,
}

/// Internal WUU module wake sources supported by this driver.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub enum InternalModule {
    /// System Power Controller interrupt.
    Spc,
    /// RTC interrupt.
    Rtc,
    /// Wake timer interrupt.
    WakeTimer,
    /// Tamper detect interrupt.
    TamperDetect,
    /// GPIO5 interrupt 0.
    #[cfg(feature = "mcxa5xx")]
    Gpio5Interrupt0,
    /// GPIO5 interrupt 1.
    #[cfg(feature = "mcxa5xx")]
    Gpio5Interrupt1,
    /// Low-Power Timer 0 interrupt.
    Lptmr0,
    /// Comparator 0 interrupt.
    Comparator0,
}

/// Internal WUU DMA or trigger wake sources.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub enum InternalRequest {
    /// GPIO5 DMA request 0.
    #[cfg(feature = "mcxa5xx")]
    Gpio5Dma0,
    /// GPIO5 DMA request 1.
    #[cfg(feature = "mcxa5xx")]
    Gpio5Dma1,
    /// GPIO5 trigger 0.
    #[cfg(feature = "mcxa5xx")]
    Gpio5Trigger0,
    /// GPIO5 trigger 1.
    #[cfg(feature = "mcxa5xx")]
    Gpio5Trigger1,
    /// LPTMR0 DMA request.
    Lptmr0Dma,
    /// LPTMR0 trigger.
    Lptmr0Trigger,
    /// Comparator 0 DMA request.
    Comparator0Dma,
}

pub(crate) mod sealed {
    pub trait SealedPin {
        fn wakeup_index(&self) -> usize;
    }
}

/// Pin that is connected to a WUU external input on the selected MCXA family.
#[allow(private_bounds)]
pub trait Pin: sealed::SealedPin + GpioPin + PeripheralType {}

/// GPIO input prepared for use as a WUU external wake source.
pub struct WakeupPin<'d> {
    index: usize,
    _input: Input<'d>,
}

impl<'d> WakeupPin<'d> {
    /// Configure a chip-valid WUU pin as a GPIO input.
    pub fn new(pin: Peri<'d, impl Pin>, pull: Pull) -> Self {
        let index = pin.wakeup_index();
        Self {
            index,
            _input: Input::new(pin, pull),
        }
    }

    /// Return whether the wake pin input is high.
    pub fn is_high(&self) -> bool {
        self._input.is_high()
    }

    /// Return whether the wake pin input is low.
    pub fn is_low(&self) -> bool {
        self._input.is_low()
    }
}

/// Wake-Up Unit.
pub struct Wuu<'d> {
    _peri: Peri<'d, peripherals::WUU0>,
}

impl<'d> Wuu<'d> {
    /// Create the WUU driver.
    pub fn new(
        peri: Peri<'d, peripherals::WUU0>,
        _irq: impl Binding<interrupt::typelevel::WUU0, InterruptHandler> + 'd,
    ) -> Result<Self, Error> {
        if !crate::clocks::with_clocks(|clocks| clocks.clk_16k_vsys.is_some()).unwrap_or(false) {
            return Err(Error::ClockUnavailable);
        }

        interrupt::WUU0.disable();
        disable_all_sources();
        clear_external_flags();
        interrupt::WUU0.unpend();
        Ok(Self { _peri: peri })
    }

    /// Arm an external pin as the active wake source.
    pub fn enable_external_pin<'a>(
        &'a mut self,
        pin: &'a mut WakeupPin<'d>,
        config: ExternalPinConfig,
    ) -> ConfiguredWake<'a, 'd> {
        configure_external_pin(pin.index, config);

        if config.event == Event::Interrupt {
            interrupt::WUU0.unpend();
            // SAFETY: the binding passed to Wuu::new installs InterruptHandler.
            unsafe { interrupt::WUU0.enable() };
        }

        ConfiguredWake {
            _wuu: self,
            source: Source::External {
                index: pin.index,
                event: config.event,
            },
            _pin: Some(pin),
        }
    }

    /// Arm an external wake source without taking ownership of its GPIO pin.
    ///
    /// The caller must configure the pin as an input before entering low power.
    /// This is intended for pins that are also managed by a GPIO-based runtime
    /// service.
    pub fn enable_external_pin_source<'a>(
        &'a mut self,
        pin: &Peri<'_, impl Pin>,
        config: ExternalPinConfig,
    ) -> ConfiguredWake<'a, 'd> {
        let index = pin.wakeup_index();
        configure_external_pin(index, config);

        if config.event == Event::Interrupt {
            interrupt::WUU0.unpend();
            // SAFETY: the binding passed to Wuu::new installs InterruptHandler.
            unsafe { interrupt::WUU0.enable() };
        }

        ConfiguredWake {
            _wuu: self,
            source: Source::External {
                index,
                event: config.event,
            },
            _pin: None,
        }
    }

    /// Arm an internal module interrupt as the active wake source.
    ///
    /// The source peripheral and its interrupt must be configured separately.
    pub fn enable_internal_module<'a>(&'a mut self, module: InternalModule) -> ConfiguredWake<'a, 'd> {
        set_internal_module(module, true);
        ConfiguredWake {
            _wuu: self,
            source: Source::Internal(module),
            _pin: None,
        }
    }

    /// Arm an internal DMA request or trigger as the active wake source.
    ///
    /// These sources request DMA or trigger service without waking the core.
    pub fn enable_internal_request<'a>(&'a mut self, request: InternalRequest) -> ConfiguredWake<'a, 'd> {
        set_internal_request(request, true);
        ConfiguredWake {
            _wuu: self,
            source: Source::InternalRequest(request),
            _pin: None,
        }
    }
}

#[derive(Clone, Copy)]
enum Source {
    External { index: usize, event: Event },
    Internal(InternalModule),
    InternalRequest(InternalRequest),
}

/// Guard proving that a WUU wake source is configured.
///
/// Dropping the guard disables its wake source.
#[must_use = "the wake source is disabled when this guard is dropped"]
pub struct ConfiguredWake<'a, 'd> {
    _wuu: &'a mut Wuu<'d>,
    source: Source,
    _pin: Option<&'a mut WakeupPin<'d>>,
}

impl Drop for ConfiguredWake<'_, '_> {
    fn drop(&mut self) {
        match self.source {
            Source::External { index, event } => {
                if event == Event::Interrupt {
                    interrupt::WUU0.disable();
                    interrupt::WUU0.unpend();
                }
                set_pin_mode(index, PinMode::LowPowerOnly);
                set_pin_edge_raw(index, Wupe::Disable);
                clear_external_flag(index);
            }
            Source::Internal(module) => set_internal_module(module, false),
            Source::InternalRequest(request) => set_internal_request(request, false),
        }
    }
}

fn configure_external_pin(index: usize, config: ExternalPinConfig) {
    set_pin_mode(index, PinMode::LowPowerOnly);
    set_pin_event(index, config.event);
    set_pin_edge(index, config.edge);
    clear_external_flag(index);
    set_pin_mode(index, config.mode);
}

/// WUU interrupt handler.
pub struct InterruptHandler;

impl Handler<interrupt::typelevel::WUU0> for InterruptHandler {
    unsafe fn on_interrupt() {
        clear_external_flags();
    }
}

fn disable_all_sources() {
    pac::WUU0.pe1().write(|w| w.0 = 0);
    pac::WUU0.pe2().write(|w| w.0 = 0);
    pac::WUU0.me().write(|w| w.0 = 0);
    pac::WUU0.de().write(|w| w.0 = 0);
}

fn set_pin_edge(index: usize, edge: Edge) {
    set_pin_edge_raw(index, edge.into());
}

fn set_pin_edge_raw(index: usize, edge: Wupe) {
    if index < 16 {
        pac::WUU0.pe1().modify(|w| w.set_wupe(index, edge));
    } else {
        pac::WUU0.pe2().modify(|w| w.set_wupe(index - 16, edge));
    }
}

fn set_pin_event(index: usize, event: Event) {
    if index < 16 {
        pac::WUU0.pdc1().modify(|w| w.set_wupdc(index, event.into()));
    } else {
        pac::WUU0.pdc2().modify(|w| w.set_wupdc(index - 16, event.into()));
    }
}

fn set_pin_mode(index: usize, mode: PinMode) {
    pac::WUU0.pmc().modify(|w| w.set_wupmc(index, mode.into()));
}

fn clear_external_flag(index: usize) {
    pac::WUU0.pf().write(|w| w.set_wuf(index, true));
}

fn clear_external_flags() {
    let flags = pac::WUU0.pf().read().0;
    pac::WUU0.pf().write(|w| w.0 = flags);
}

fn set_internal_module(module: InternalModule, enabled: bool) {
    match module {
        InternalModule::Spc => pac::WUU0.me().modify(|w| w.set_wume0(enabled)),
        InternalModule::Rtc => pac::WUU0.me().modify(|w| w.set_wume1(enabled)),
        InternalModule::WakeTimer => pac::WUU0.me().modify(|w| w.set_wume2(enabled)),
        InternalModule::TamperDetect => pac::WUU0.me().modify(|w| w.set_wume3(enabled)),
        #[cfg(feature = "mcxa5xx")]
        InternalModule::Gpio5Interrupt0 => pac::WUU0.me().modify(|w| w.set_wume4(enabled)),
        #[cfg(feature = "mcxa5xx")]
        InternalModule::Gpio5Interrupt1 => pac::WUU0.me().modify(|w| w.set_wume5(enabled)),
        InternalModule::Lptmr0 => pac::WUU0.me().modify(|w| w.set_wume6(enabled)),
        InternalModule::Comparator0 => pac::WUU0.me().modify(|w| w.set_wume8(enabled)),
    }
}

fn set_internal_request(request: InternalRequest, enabled: bool) {
    match request {
        #[cfg(feature = "mcxa5xx")]
        InternalRequest::Gpio5Dma0 => pac::WUU0.de().modify(|w| w.set_wude0(enabled)),
        #[cfg(feature = "mcxa5xx")]
        InternalRequest::Gpio5Dma1 => pac::WUU0.de().modify(|w| w.set_wude1(enabled)),
        #[cfg(feature = "mcxa5xx")]
        InternalRequest::Gpio5Trigger0 => pac::WUU0.de().modify(|w| w.set_wude2(enabled)),
        #[cfg(feature = "mcxa5xx")]
        InternalRequest::Gpio5Trigger1 => pac::WUU0.de().modify(|w| w.set_wude3(enabled)),
        InternalRequest::Lptmr0Dma => pac::WUU0.de().modify(|w| w.set_wude4(enabled)),
        InternalRequest::Lptmr0Trigger => pac::WUU0.de().modify(|w| w.set_wude6(enabled)),
        InternalRequest::Comparator0Dma => pac::WUU0.de().modify(|w| w.set_wude8(enabled)),
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! impl_wuu_pin {
    ($pin:ident, $index:literal) => {
        impl $crate::wuu::sealed::SealedPin for $crate::peripherals::$pin {
            #[inline]
            fn wakeup_index(&self) -> usize {
                $index
            }
        }

        impl $crate::wuu::Pin for $crate::peripherals::$pin {}
    };
}
