[package]
name = "embassy-crypto-driver"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "Driver trait for `embassy-crypto`."
repository = "https://github.com/embassy-rs/embassy"
documentation = "https://docs.embassy.dev/embassy-crypto-driver"
categories = [
    "embedded",
    "no-std",
    "asynchronous",
]

[package.metadata.embassy_docs]
src_base = "https://github.com/embassy-rs/embassy/blob/embassy-crypto-driver-v$VERSION/embassy-net-driver/src/"
src_base_git = "https://github.com/embassy-rs/embassy/blob/$COMMIT/embassy-crypto-driver/src/"
features = ["defmt"]
target = "thumbv7em-none-eabi"

[package.metadata.docs.rs]
features = ["defmt"]

[package.metadata.embassy]
build = [
    {target = "thumbv7em-none-eabi", features = ["defmt"]},
]

[dependencies]
defmt = { version = "1.0.1", optional = true }
unitrait = { git = "https://github.com/embassy-rs/unitrait", rev = "b98d69bbf6fa7872c0cc107e5b52f0bc1df03777" }

[features]
defmt = ["dep:defmt"]
large-md5 = []
large-sha1 = []
large-sha224 = []
large-sha256 = []
large-sha384 = []
large-sha512-224 = []
large-sha512-256 = []
large-sha512 = []
large-hmac-sha1 = []
large-hmac-sha224 = []
large-hmac-sha256 = []
large-hmac-sha384 = []
large-hmac-sha512-224 = []
large-hmac-sha512-256 = []
large-hmac-sha512 = []
