//! GATT Event types and handling
//!
//! This module defines events generated by GATT operations such as
//! characteristic writes, notification confirmations, and MTU exchanges.

use bt_hci::param::ConnHandle;
use stm32wb_hci::aci::AciEvent;
use stm32wb_hci::aci::ranges::EattMtu;
use stm32wb_hci::aci::values::EattBearerState;
use stm32wb_hci::wire::{AttBearer, OrUnknown};

/// GATT events generated by remote device operations
#[derive(Debug, Clone)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub enum GattEvent {
    /// A characteristic attribute was modified by the remote device
    ///
    /// This event is generated when:
    /// - A client writes to a characteristic
    /// - A client writes to the CCCD (Client Characteristic Configuration Descriptor)
    AttributeModified {
        /// Connection handle
        conn_handle: ConnHandle,
        /// Attribute handle that was modified
        attr_handle: u16,
        /// Offset within the attribute value
        offset: u16,
        /// The written data
        data: heapless::Vec<u8, 247>,
    },

    /// Notification was sent successfully
    NotificationComplete {
        /// Connection handle
        conn_handle: ConnHandle,
        /// Attribute handle
        attr_handle: u16,
    },

    /// Indication was confirmed by the client
    IndicationComplete {
        /// Connection handle
        conn_handle: ConnHandle,
        /// Attribute handle
        attr_handle: u16,
    },

    /// MTU exchange completed
    MtuExchangeComplete {
        /// Connection handle
        conn_handle: ConnHandle,
        /// Server MTU
        server_mtu: u16,
    },

    /// GATT procedure completed
    ProcedureComplete {
        /// Connection handle
        conn_handle: ConnHandle,
        /// Error code (0 = success)
        error_code: u8,
    },

    /// GATT procedure timed out
    ProcedureTimeout {
        /// Connection handle
        conn_handle: ConnHandle,
    },

    /// Write request confirmation needed
    ///
    /// Generated for writes that require confirmation (Write Request vs Write Command)
    WritePermitRequest {
        /// Connection handle
        conn_handle: ConnHandle,
        /// Attribute handle
        attr_handle: u16,
        /// Offset within the attribute
        offset: u16,
        /// Data to be written
        data: heapless::Vec<u8, 247>,
    },

    /// Read request (for dynamic value generation)
    ReadPermitRequest {
        /// Connection handle
        conn_handle: ConnHandle,
        /// Attribute handle
        attr_handle: u16,
        /// Offset for read
        offset: u16,
    },

    /// Prepare-write request confirmation needed.
    ///
    /// Generated for long/reliable writes that are staged before execute.
    PrepareWritePermitRequest {
        /// Connection handle
        conn_handle: ConnHandle,
        /// Attribute handle
        attr_handle: u16,
        /// Offset within the attribute
        offset: u16,
        /// Fragment data to stage
        data: heapless::Vec<u8, 247>,
    },

    /// TX buffer available for more data
    TxPoolAvailable {
        /// Connection handle
        conn_handle: ConnHandle,
        /// Number of available buffers
        available_buffers: u16,
    },

    /// Server confirmation is needed for a pending indication.
    ServerConfirmationNeeded {
        /// Connection handle
        conn_handle: ConnHandle,
    },

    /// Extended notification payload received from peer.
    NotificationReceivedExt {
        conn_handle: ConnHandle,
        attr_handle: u16,
        offset: u16,
        data: heapless::Vec<u8, 247>,
    },

    /// Extended indication payload received from peer.
    IndicationReceivedExt {
        conn_handle: ConnHandle,
        attr_handle: u16,
        offset: u16,
        data: heapless::Vec<u8, 247>,
    },

    /// Extended read response payload from a GATT client procedure.
    ReadResponseExt {
        conn_handle: ConnHandle,
        offset: u16,
        value: heapless::Vec<u8, 247>,
    },

    /// Multiple-notification payload block received from peer.
    MultiNotificationReceived {
        conn_handle: ConnHandle,
        offset: u16,
        data: heapless::Vec<u8, 247>,
    },

    /// Enhanced ATT bearer state change.
    EattBearerStateChanged {
        conn_handle: ConnHandle,
        channel_index: u8,
        state: OrUnknown<EattBearerState>,
        mtu: OrUnknown<EattMtu>,
    },
}

/// High-level GATT client-side events derived from vendor ATT/GATT responses.
#[derive(Debug, Clone)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub enum GattClientEvent {
    /// A primary service was discovered.
    PrimaryServiceFound {
        conn_handle: ConnHandle,
        start_handle: u16,
        end_handle: u16,
        uuid: heapless::Vec<u8, 16>,
    },
    /// A characteristic declaration was discovered.
    CharacteristicFound {
        conn_handle: ConnHandle,
        declaration_handle: u16,
        properties: u8,
        value_handle: u16,
        uuid: heapless::Vec<u8, 16>,
    },
    /// A descriptor was discovered.
    DescriptorFound {
        conn_handle: ConnHandle,
        handle: u16,
        uuid: heapless::Vec<u8, 16>,
    },
    /// Characteristic/descriptor read response payload.
    ReadResponse {
        conn_handle: ConnHandle,
        value: heapless::Vec<u8, 247>,
    },
    /// GATT procedure completion status.
    ProcedureComplete { conn_handle: ConnHandle, success: bool },
    /// ATT error response associated with a client procedure.
    ErrorResponse {
        conn_handle: ConnHandle,
        request_opcode: u8,
        attribute_handle: u16,
        error_code: u8,
    },
}

impl GattClientEvent {
    /// Returns `true` when this event marks the end of a client procedure.
    pub fn is_terminal(&self) -> bool {
        matches!(self, Self::ProcedureComplete { .. } | Self::ErrorResponse { .. })
    }
}

/// ACI GATT event codes (vendor-specific events)
pub mod aci_event_code {
    /// Attribute was modified by remote device
    pub const GATT_ATTRIBUTE_MODIFIED: u16 = 0x0C01;
    /// GATT procedure completed
    pub const GATT_PROC_COMPLETE: u16 = 0x0C02;
    /// Notification sent
    pub const GATT_NOTIFICATION_COMPLETE: u16 = 0x0C03;
    /// Indication confirmed
    pub const GATT_INDICATION_COMPLETE: u16 = 0x0C04;
    /// ATT MTU exchange response
    pub const ATT_EXCHANGE_MTU_RESP: u16 = 0x0802;
    /// GATT procedure timeout
    pub const GATT_PROC_TIMEOUT: u16 = 0x0C05;
    /// Write permit request
    pub const GATT_WRITE_PERMIT_REQ: u16 = 0x0C06;
    /// Read permit request
    pub const GATT_READ_PERMIT_REQ: u16 = 0x0C07;
    /// TX pool available
    pub const GATT_TX_POOL_AVAILABLE: u16 = 0x0C08;
    /// Server confirmation needed
    pub const GATT_SERVER_CONFIRMATION_NEEDED: u16 = 0x0C09;
    /// Prepare write permit request
    pub const GATT_PREPARE_WRITE_PERMIT_REQ: u16 = 0x0C0A;
}

/// CCCD (Client Characteristic Configuration Descriptor) values
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub struct CccdValue {
    /// Notifications enabled
    pub notifications: bool,
    /// Indications enabled
    pub indications: bool,
}

impl CccdValue {
    /// Create from raw CCCD bytes (little-endian u16)
    pub fn from_bytes(bytes: &[u8]) -> Self {
        if bytes.len() >= 2 {
            let value = u16::from_le_bytes([bytes[0], bytes[1]]);
            Self {
                notifications: (value & 0x0001) != 0,
                indications: (value & 0x0002) != 0,
            }
        } else if bytes.len() == 1 {
            Self {
                notifications: (bytes[0] & 0x01) != 0,
                indications: (bytes[0] & 0x02) != 0,
            }
        } else {
            Self::default()
        }
    }

    /// Convert to raw CCCD bytes
    pub fn to_bytes(&self) -> [u8; 2] {
        let mut value: u16 = 0;
        if self.notifications {
            value |= 0x0001;
        }
        if self.indications {
            value |= 0x0002;
        }
        value.to_le_bytes()
    }
}

/// Offset from characteristic declaration handle to value handle
pub const CHAR_VALUE_HANDLE_OFFSET: u16 = 1;

/// Offset from characteristic declaration handle to CCCD handle
pub const CHAR_CCCD_HANDLE_OFFSET: u16 = 2;

/// Check if an attribute handle is a CCCD based on characteristic handle
pub fn is_cccd_handle(char_handle: u16, attr_handle: u16) -> bool {
    attr_handle == char_handle + CHAR_CCCD_HANDLE_OFFSET
}

/// Check if an attribute handle is a characteristic value based on characteristic handle
pub fn is_value_handle(char_handle: u16, attr_handle: u16) -> bool {
    attr_handle == char_handle + CHAR_VALUE_HANDLE_OFFSET
}

/// The connection of an unenhanced ATT bearer.
///
/// The high-level API runs its procedures on unenhanced bearers only, so events
/// on an enhanced ATT bearer are not modeled.
fn bearer_conn(bearer: AttBearer) -> Option<ConnHandle> {
    bearer.connection()
}

fn to_vec<const N: usize>(data: &[u8]) -> heapless::Vec<u8, N> {
    let mut v = heapless::Vec::new();
    let _ = v.extend_from_slice(&data[..data.len().min(N)]);
    v
}

/// Convert an STM32 vendor-specific event into a high-level GATT event.
///
/// Returns `None` for vendor events that are not part of the core GATT event
/// surface modeled by [`GattEvent`].
pub fn from_vendor_event(event: &AciEvent<'_>) -> Option<GattEvent> {
    match event {
        AciEvent::GattAttributeModified(e) => Some(GattEvent::AttributeModified {
            conn_handle: bearer_conn(e.connection_handle)?,
            attr_handle: e.attr_handle,
            // Mask out the "more fragments" flag bit (bit 15) to return pure offset.
            offset: e.offset & 0x7FFF,
            data: to_vec(e.attr_data),
        }),
        #[cfg(not(feature = "ble-stack-po"))]
        AciEvent::GattProcComplete(e) => Some(GattEvent::ProcedureComplete {
            conn_handle: bearer_conn(e.connection_handle)?,
            error_code: e.error_code,
        }),
        AciEvent::GattProcTimeout(e) => Some(GattEvent::ProcedureTimeout {
            conn_handle: bearer_conn(e.connection_handle)?,
        }),
        AciEvent::AttExchangeMtuResp(e) => Some(GattEvent::MtuExchangeComplete {
            conn_handle: e.connection_handle,
            server_mtu: e.server_rx_mtu,
        }),
        AciEvent::GattWritePermitReq(e) => Some(GattEvent::WritePermitRequest {
            conn_handle: bearer_conn(e.connection_handle)?,
            attr_handle: e.attribute_handle,
            // ST's write-permit event payload does not include an offset field.
            offset: 0,
            data: to_vec(e.data),
        }),
        AciEvent::GattReadPermitReq(e) => Some(GattEvent::ReadPermitRequest {
            conn_handle: bearer_conn(e.connection_handle)?,
            attr_handle: e.attribute_handle,
            offset: e.offset,
        }),
        AciEvent::GattPrepareWritePermitReq(e) => Some(GattEvent::PrepareWritePermitRequest {
            conn_handle: bearer_conn(e.connection_handle)?,
            attr_handle: e.attribute_handle,
            offset: e.offset,
            data: to_vec(e.data),
        }),
        AciEvent::GattTxPoolAvailable(e) => Some(GattEvent::TxPoolAvailable {
            conn_handle: e.connection_handle,
            available_buffers: e.available_buffers,
        }),
        AciEvent::GattServerConfirmation(e) => Some(GattEvent::ServerConfirmationNeeded {
            conn_handle: bearer_conn(e.connection_handle)?,
        }),
        AciEvent::GattNotificationComplete(e) => Some(GattEvent::NotificationComplete {
            // This vendor event does not include a connection handle.
            conn_handle: ConnHandle::new(0),
            attr_handle: e.attr_handle,
        }),
        #[cfg(not(feature = "ble-stack-po"))]
        AciEvent::GattIndicationExt(e) => Some(GattEvent::IndicationReceivedExt {
            conn_handle: bearer_conn(e.connection_handle)?,
            attr_handle: e.attribute_handle,
            offset: e.offset & 0x7FFF,
            data: to_vec(e.attribute_value),
        }),
        #[cfg(not(feature = "ble-stack-po"))]
        AciEvent::GattNotificationExt(e) => Some(GattEvent::NotificationReceivedExt {
            conn_handle: bearer_conn(e.connection_handle)?,
            attr_handle: e.attribute_handle,
            offset: e.offset & 0x7FFF,
            data: to_vec(e.attribute_value),
        }),
        #[cfg(not(feature = "ble-stack-po"))]
        AciEvent::GattReadExt(e) => Some(GattEvent::ReadResponseExt {
            conn_handle: bearer_conn(e.connection_handle)?,
            offset: e.offset & 0x7FFF,
            value: to_vec(e.attribute_value),
        }),
        #[cfg(not(any(feature = "ble-stack-basic", feature = "ble-stack-po")))]
        AciEvent::GattMultNotification(e) => Some(GattEvent::MultiNotificationReceived {
            conn_handle: bearer_conn(e.connection_handle)?,
            offset: e.offset & 0x7FFF,
            data: to_vec(e.data),
        }),
        #[cfg(not(any(feature = "ble-stack-basic", feature = "ble-stack-po")))]
        AciEvent::GattEattBearer(e) => Some(GattEvent::EattBearerStateChanged {
            conn_handle: e.connection_handle,
            channel_index: e.channel_index,
            state: e.eab_state,
            mtu: e.mtu,
        }),
        _ => None,
    }
}

/// Convert an STM32 vendor-specific event into zero or more high-level GATT
/// client events.
///
/// Some ATT responses contain multiple records (services/chars/descriptors),
/// therefore this returns a bounded vector.
pub fn client_events_from_vendor_event(event: &AciEvent<'_>) -> heapless::Vec<GattClientEvent, 16> {
    // The peripheral-only stack has no GATT client.
    #[cfg_attr(feature = "ble-stack-po", allow(unused_mut))]
    let mut out = heapless::Vec::<GattClientEvent, 16>::new();

    match event {
        #[cfg(not(feature = "ble-stack-po"))]
        AciEvent::AttReadByGroupTypeResp(e) => {
            let Some(conn_handle) = bearer_conn(e.connection_handle) else {
                return out;
            };
            // Each record: [start handle: u16, end handle: u16, uuid: u16/128]
            let len = e.attribute_data_length as usize;
            if len >= 4 {
                for item in e.attribute_data_list.chunks_exact(len) {
                    let _ = out.push(GattClientEvent::PrimaryServiceFound {
                        conn_handle,
                        start_handle: u16::from_le_bytes([item[0], item[1]]),
                        end_handle: u16::from_le_bytes([item[2], item[3]]),
                        uuid: to_vec(&item[4..]),
                    });
                }
            }
        }
        #[cfg(not(feature = "ble-stack-po"))]
        AciEvent::AttReadByTypeResp(e) => {
            let Some(conn_handle) = bearer_conn(e.connection_handle) else {
                return out;
            };
            // Each record: [handle: u16, value]
            let len = e.handle_value_pair_length as usize;
            if len >= 2 {
                for item in e.handle_value_pair_data.chunks_exact(len) {
                    let value = &item[2..];
                    // Characteristic declaration value format:
                    // [properties: u8, value_handle: u16, uuid: u16/128]
                    if value.len() >= 3 {
                        let _ = out.push(GattClientEvent::CharacteristicFound {
                            conn_handle,
                            declaration_handle: u16::from_le_bytes([item[0], item[1]]),
                            properties: value[0],
                            value_handle: u16::from_le_bytes([value[1], value[2]]),
                            uuid: to_vec(&value[3..]),
                        });
                    }
                }
            }
        }
        #[cfg(not(feature = "ble-stack-po"))]
        AciEvent::AttFindInfoResp(e) => {
            let Some(conn_handle) = bearer_conn(e.connection_handle) else {
                return out;
            };
            // Format 1: [handle: u16, uuid: u16]; format 2: [handle: u16, uuid: u128]
            let len = match e.format {
                1 => 4,
                2 => 18,
                _ => return out,
            };
            for item in e.handle_uuid_pair.chunks_exact(len) {
                let _ = out.push(GattClientEvent::DescriptorFound {
                    conn_handle,
                    handle: u16::from_le_bytes([item[0], item[1]]),
                    uuid: to_vec(&item[2..]),
                });
            }
        }
        #[cfg(not(feature = "ble-stack-po"))]
        AciEvent::AttReadResp(e) => {
            if let Some(conn_handle) = bearer_conn(e.connection_handle) {
                let _ = out.push(GattClientEvent::ReadResponse {
                    conn_handle,
                    value: to_vec(e.attribute_value),
                });
            }
        }
        #[cfg(not(feature = "ble-stack-po"))]
        AciEvent::AttReadBlobResp(e) => {
            if let Some(conn_handle) = bearer_conn(e.connection_handle) {
                let _ = out.push(GattClientEvent::ReadResponse {
                    conn_handle,
                    value: to_vec(e.attribute_value),
                });
            }
        }
        #[cfg(not(feature = "ble-stack-po"))]
        AciEvent::AttReadMultipleResp(e) => {
            if let Some(conn_handle) = bearer_conn(e.connection_handle) {
                let _ = out.push(GattClientEvent::ReadResponse {
                    conn_handle,
                    value: to_vec(e.set_of_values),
                });
            }
        }
        #[cfg(not(feature = "ble-stack-po"))]
        AciEvent::GattProcComplete(e) => {
            if let Some(conn_handle) = bearer_conn(e.connection_handle) {
                let _ = out.push(GattClientEvent::ProcedureComplete {
                    conn_handle,
                    success: e.error_code == 0,
                });
            }
        }
        #[cfg(not(feature = "ble-stack-po"))]
        AciEvent::GattErrorResp(e) => {
            if let Some(conn_handle) = bearer_conn(e.connection_handle) {
                let _ = out.push(GattClientEvent::ErrorResponse {
                    conn_handle,
                    request_opcode: e.req_opcode,
                    attribute_handle: e.attribute_handle,
                    error_code: e.error_code.to_raw(),
                });
            }
        }
        _ => {}
    }

    out
}
