//! GATT Event types and handling
//!
//! This module defines events generated by GATT operations such as
//! characteristic writes, notification confirmations, and MTU exchanges.

use stm32wb_hci::ConnectionHandle;
use stm32wb_hci::vendor::event::{EabState, GattProcedureStatus, VendorEvent};

/// GATT events generated by remote device operations
#[derive(Debug, Clone)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub enum GattEvent {
    /// A characteristic attribute was modified by the remote device
    ///
    /// This event is generated when:
    /// - A client writes to a characteristic
    /// - A client writes to the CCCD (Client Characteristic Configuration Descriptor)
    AttributeModified {
        /// Connection handle
        conn_handle: ConnectionHandle,
        /// Attribute handle that was modified
        attr_handle: u16,
        /// Offset within the attribute value
        offset: u16,
        /// The written data
        data: heapless::Vec<u8, 247>,
    },

    /// Notification was sent successfully
    NotificationComplete {
        /// Connection handle
        conn_handle: ConnectionHandle,
        /// Attribute handle
        attr_handle: u16,
    },

    /// Indication was confirmed by the client
    IndicationComplete {
        /// Connection handle
        conn_handle: ConnectionHandle,
        /// Attribute handle
        attr_handle: u16,
    },

    /// MTU exchange completed
    MtuExchangeComplete {
        /// Connection handle
        conn_handle: ConnectionHandle,
        /// Server MTU
        server_mtu: u16,
    },

    /// GATT procedure completed
    ProcedureComplete {
        /// Connection handle
        conn_handle: ConnectionHandle,
        /// Error code (0 = success)
        error_code: u8,
    },

    /// GATT procedure timed out
    ProcedureTimeout {
        /// Connection handle
        conn_handle: ConnectionHandle,
    },

    /// Write request confirmation needed
    ///
    /// Generated for writes that require confirmation (Write Request vs Write Command)
    WritePermitRequest {
        /// Connection handle
        conn_handle: ConnectionHandle,
        /// Attribute handle
        attr_handle: u16,
        /// Offset within the attribute
        offset: u16,
        /// Data to be written
        data: heapless::Vec<u8, 247>,
    },

    /// Read request (for dynamic value generation)
    ReadPermitRequest {
        /// Connection handle
        conn_handle: ConnectionHandle,
        /// Attribute handle
        attr_handle: u16,
        /// Offset for read
        offset: u16,
    },

    /// Prepare-write request confirmation needed.
    ///
    /// Generated for long/reliable writes that are staged before execute.
    PrepareWritePermitRequest {
        /// Connection handle
        conn_handle: ConnectionHandle,
        /// Attribute handle
        attr_handle: u16,
        /// Offset within the attribute
        offset: u16,
        /// Fragment data to stage
        data: heapless::Vec<u8, 247>,
    },

    /// TX buffer available for more data
    TxPoolAvailable {
        /// Connection handle
        conn_handle: ConnectionHandle,
        /// Number of available buffers
        available_buffers: u16,
    },

    /// Server confirmation is needed for a pending indication.
    ServerConfirmationNeeded {
        /// Connection handle
        conn_handle: ConnectionHandle,
    },

    /// Extended notification payload received from peer.
    NotificationReceivedExt {
        conn_handle: ConnectionHandle,
        attr_handle: u16,
        offset: u16,
        data: heapless::Vec<u8, 247>,
    },

    /// Extended indication payload received from peer.
    IndicationReceivedExt {
        conn_handle: ConnectionHandle,
        attr_handle: u16,
        offset: u16,
        data: heapless::Vec<u8, 247>,
    },

    /// Extended read response payload from a GATT client procedure.
    ReadResponseExt {
        conn_handle: ConnectionHandle,
        offset: u16,
        value: heapless::Vec<u8, 247>,
    },

    /// Multiple-notification payload block received from peer.
    MultiNotificationReceived {
        conn_handle: ConnectionHandle,
        offset: u16,
        data: heapless::Vec<u8, 247>,
    },

    /// Enhanced ATT bearer state change.
    EattBearerStateChanged {
        channel_index: u8,
        state: EabState,
        success: bool,
    },
}

/// High-level GATT client-side events derived from vendor ATT/GATT responses.
#[derive(Debug, Clone)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub enum GattClientEvent {
    /// A primary service was discovered.
    PrimaryServiceFound {
        conn_handle: ConnectionHandle,
        start_handle: u16,
        end_handle: u16,
        uuid: heapless::Vec<u8, 16>,
    },
    /// A characteristic declaration was discovered.
    CharacteristicFound {
        conn_handle: ConnectionHandle,
        declaration_handle: u16,
        properties: u8,
        value_handle: u16,
        uuid: heapless::Vec<u8, 16>,
    },
    /// A descriptor was discovered.
    DescriptorFound {
        conn_handle: ConnectionHandle,
        handle: u16,
        uuid: heapless::Vec<u8, 16>,
    },
    /// Characteristic/descriptor read response payload.
    ReadResponse {
        conn_handle: ConnectionHandle,
        value: heapless::Vec<u8, 247>,
    },
    /// GATT procedure completion status.
    ProcedureComplete {
        conn_handle: ConnectionHandle,
        success: bool,
    },
    /// ATT error response associated with a client procedure.
    ErrorResponse {
        conn_handle: ConnectionHandle,
        request_opcode: u8,
        attribute_handle: u16,
        error_code: u8,
    },
}

impl GattClientEvent {
    /// Returns `true` when this event marks the end of a client procedure.
    pub fn is_terminal(&self) -> bool {
        matches!(self, Self::ProcedureComplete { .. } | Self::ErrorResponse { .. })
    }
}

/// ACI GATT event codes (vendor-specific events)
pub mod aci_event_code {
    /// Attribute was modified by remote device
    pub const GATT_ATTRIBUTE_MODIFIED: u16 = 0x0C01;
    /// GATT procedure completed
    pub const GATT_PROC_COMPLETE: u16 = 0x0C02;
    /// Notification sent
    pub const GATT_NOTIFICATION_COMPLETE: u16 = 0x0C03;
    /// Indication confirmed
    pub const GATT_INDICATION_COMPLETE: u16 = 0x0C04;
    /// ATT MTU exchange response
    pub const ATT_EXCHANGE_MTU_RESP: u16 = 0x0802;
    /// GATT procedure timeout
    pub const GATT_PROC_TIMEOUT: u16 = 0x0C05;
    /// Write permit request
    pub const GATT_WRITE_PERMIT_REQ: u16 = 0x0C06;
    /// Read permit request
    pub const GATT_READ_PERMIT_REQ: u16 = 0x0C07;
    /// TX pool available
    pub const GATT_TX_POOL_AVAILABLE: u16 = 0x0C08;
    /// Server confirmation needed
    pub const GATT_SERVER_CONFIRMATION_NEEDED: u16 = 0x0C09;
    /// Prepare write permit request
    pub const GATT_PREPARE_WRITE_PERMIT_REQ: u16 = 0x0C0A;
}

/// CCCD (Client Characteristic Configuration Descriptor) values
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub struct CccdValue {
    /// Notifications enabled
    pub notifications: bool,
    /// Indications enabled
    pub indications: bool,
}

impl CccdValue {
    /// Create from raw CCCD bytes (little-endian u16)
    pub fn from_bytes(bytes: &[u8]) -> Self {
        if bytes.len() >= 2 {
            let value = u16::from_le_bytes([bytes[0], bytes[1]]);
            Self {
                notifications: (value & 0x0001) != 0,
                indications: (value & 0x0002) != 0,
            }
        } else if bytes.len() == 1 {
            Self {
                notifications: (bytes[0] & 0x01) != 0,
                indications: (bytes[0] & 0x02) != 0,
            }
        } else {
            Self::default()
        }
    }

    /// Convert to raw CCCD bytes
    pub fn to_bytes(&self) -> [u8; 2] {
        let mut value: u16 = 0;
        if self.notifications {
            value |= 0x0001;
        }
        if self.indications {
            value |= 0x0002;
        }
        value.to_le_bytes()
    }
}

/// Offset from characteristic declaration handle to value handle
pub const CHAR_VALUE_HANDLE_OFFSET: u16 = 1;

/// Offset from characteristic declaration handle to CCCD handle
pub const CHAR_CCCD_HANDLE_OFFSET: u16 = 2;

/// Check if an attribute handle is a CCCD based on characteristic handle
pub fn is_cccd_handle(char_handle: u16, attr_handle: u16) -> bool {
    attr_handle == char_handle + CHAR_CCCD_HANDLE_OFFSET
}

/// Check if an attribute handle is a characteristic value based on characteristic handle
pub fn is_value_handle(char_handle: u16, attr_handle: u16) -> bool {
    attr_handle == char_handle + CHAR_VALUE_HANDLE_OFFSET
}

/// Convert an STM32 vendor-specific event into a high-level GATT event.
///
/// Returns `None` for vendor events that are not part of the core GATT event
/// surface modeled by [`GattEvent`].
pub fn from_vendor_event(event: &VendorEvent) -> Option<GattEvent> {
    match event {
        VendorEvent::GattAttributeModified(e) => {
            let mut data = heapless::Vec::<u8, 247>::new();
            let _ = data.extend_from_slice(e.data());
            Some(GattEvent::AttributeModified {
                conn_handle: e.conn_handle,
                attr_handle: e.attr_handle.0,
                // Mask out the "more fragments" flag bit (bit 15) to return pure offset.
                offset: (e.offset() as u16) & 0x7FFF,
                data,
            })
        }
        VendorEvent::GattProcedureComplete(e) => Some(GattEvent::ProcedureComplete {
            conn_handle: e.conn_handle,
            error_code: match e.status {
                GattProcedureStatus::Success => 0x00,
                GattProcedureStatus::Failed => 0x41,
            },
        }),
        VendorEvent::GattProcedureTimeout(conn_handle) => Some(GattEvent::ProcedureTimeout {
            conn_handle: *conn_handle,
        }),
        VendorEvent::AttExchangeMtuResponse(e) => Some(GattEvent::MtuExchangeComplete {
            conn_handle: e.conn_handle,
            server_mtu: e.server_rx_mtu as u16,
        }),
        VendorEvent::AttWritePermitRequest(e) => {
            let mut data = heapless::Vec::<u8, 247>::new();
            let _ = data.extend_from_slice(e.value());
            Some(GattEvent::WritePermitRequest {
                conn_handle: e.conn_handle,
                attr_handle: e.attribute_handle.0,
                // ST's write-permit event payload does not include an offset field.
                offset: 0,
                data,
            })
        }
        VendorEvent::AttReadPermitRequest(e) => Some(GattEvent::ReadPermitRequest {
            conn_handle: e.conn_handle,
            attr_handle: e.attribute_handle.0,
            offset: e.offset as u16,
        }),
        VendorEvent::AttPrepareWritePermitRequest(e) => {
            let mut data = heapless::Vec::<u8, 247>::new();
            let _ = data.extend_from_slice(e.value());
            Some(GattEvent::PrepareWritePermitRequest {
                conn_handle: e.conn_handle,
                attr_handle: e.attribute_handle.0,
                offset: e.offset as u16,
                data,
            })
        }
        VendorEvent::GattTxPoolAvailable(e) => Some(GattEvent::TxPoolAvailable {
            conn_handle: e.conn_handle,
            available_buffers: e.available_buffers as u16,
        }),
        VendorEvent::GattServerConfirmation(conn_handle) => Some(GattEvent::ServerConfirmationNeeded {
            conn_handle: *conn_handle,
        }),
        VendorEvent::GattNotificationComplete(attr_handle) => Some(GattEvent::NotificationComplete {
            // This vendor event does not include a connection handle.
            conn_handle: ConnectionHandle(0),
            attr_handle: attr_handle.0,
        }),
        VendorEvent::GattIndicationExt(e) => {
            let mut data = heapless::Vec::<u8, 247>::new();
            let _ = data.extend_from_slice(e.value());
            Some(GattEvent::IndicationReceivedExt {
                conn_handle: e.conn_handle,
                attr_handle: e.attribute_handle.0,
                offset: e.offset & 0x7FFF,
                data,
            })
        }
        VendorEvent::GattNotificationExt(e) => {
            let mut data = heapless::Vec::<u8, 247>::new();
            let _ = data.extend_from_slice(e.value());
            Some(GattEvent::NotificationReceivedExt {
                conn_handle: e.conn_handle,
                attr_handle: e.attribute_handle.0,
                offset: e.offset & 0x7FFF,
                data,
            })
        }
        VendorEvent::GattReadExt(e) => {
            let mut value = heapless::Vec::<u8, 247>::new();
            let _ = value.extend_from_slice(e.value());
            Some(GattEvent::ReadResponseExt {
                conn_handle: e.conn_handle,
                offset: e.offset & 0x7FFF,
                value,
            })
        }
        VendorEvent::GattMultiNotification(e) => {
            let mut data = heapless::Vec::<u8, 247>::new();
            let len = core::cmp::min(e.data_len as usize, e.data.len());
            let _ = data.extend_from_slice(&e.data[..len]);
            Some(GattEvent::MultiNotificationReceived {
                conn_handle: e.conn_handle,
                offset: e.offset & 0x7FFF,
                data,
            })
        }
        VendorEvent::GattEattBrearer(e) => Some(GattEvent::EattBearerStateChanged {
            channel_index: e.channel_index,
            state: e.eab_state,
            success: matches!(e.status, GattProcedureStatus::Success),
        }),
        _ => None,
    }
}

/// Convert an STM32 vendor-specific event into zero or more high-level GATT
/// client events.
///
/// Some ATT responses contain multiple records (services/chars/descriptors),
/// therefore this returns a bounded vector.
pub fn client_events_from_vendor_event(event: &VendorEvent) -> heapless::Vec<GattClientEvent, 16> {
    let mut out = heapless::Vec::<GattClientEvent, 16>::new();

    match event {
        VendorEvent::AttReadByGroupTypeResponse(e) => {
            for item in e.attribute_data_iter() {
                let mut uuid = heapless::Vec::<u8, 16>::new();
                let _ = uuid.extend_from_slice(item.value);
                let _ = out.push(GattClientEvent::PrimaryServiceFound {
                    conn_handle: e.conn_handle,
                    start_handle: item.attribute_handle.0,
                    end_handle: item.attribute_end_handle.0,
                    uuid,
                });
            }
        }
        VendorEvent::AttReadByTypeResponse(e) => {
            for item in e.handle_value_pair_iter() {
                // Characteristic declaration value format:
                // [properties: u8, value_handle: u16, uuid: u16/128]
                if item.value.len() >= 3 {
                    let properties = item.value[0];
                    let value_handle = u16::from_le_bytes([item.value[1], item.value[2]]);
                    let mut uuid = heapless::Vec::<u8, 16>::new();
                    let _ = uuid.extend_from_slice(&item.value[3..]);
                    let _ = out.push(GattClientEvent::CharacteristicFound {
                        conn_handle: e.conn_handle,
                        declaration_handle: item.handle.0,
                        properties,
                        value_handle,
                        uuid,
                    });
                }
            }
        }
        VendorEvent::AttFindInformationResponse(e) => match e.handle_uuid_pair_iter() {
            stm32wb_hci::vendor::event::HandleUuidPairIterator::Format16(iter) => {
                for item in iter {
                    let mut uuid = heapless::Vec::<u8, 16>::new();
                    let _ = uuid.extend_from_slice(&item.uuid.0.to_le_bytes());
                    let _ = out.push(GattClientEvent::DescriptorFound {
                        conn_handle: e.conn_handle,
                        handle: item.handle.0,
                        uuid,
                    });
                }
            }
            stm32wb_hci::vendor::event::HandleUuidPairIterator::Format128(iter) => {
                for item in iter {
                    let mut uuid = heapless::Vec::<u8, 16>::new();
                    let _ = uuid.extend_from_slice(&item.uuid.0);
                    let _ = out.push(GattClientEvent::DescriptorFound {
                        conn_handle: e.conn_handle,
                        handle: item.handle.0,
                        uuid,
                    });
                }
            }
        },
        VendorEvent::AttReadResponse(e)
        | VendorEvent::AttReadBlobResponse(e)
        | VendorEvent::AttReadMultipleResponse(e) => {
            let mut value = heapless::Vec::<u8, 247>::new();
            let _ = value.extend_from_slice(e.value());
            let _ = out.push(GattClientEvent::ReadResponse {
                conn_handle: e.conn_handle,
                value,
            });
        }
        VendorEvent::GattProcedureComplete(e) => {
            let _ = out.push(GattClientEvent::ProcedureComplete {
                conn_handle: e.conn_handle,
                success: matches!(e.status, GattProcedureStatus::Success),
            });
        }
        VendorEvent::AttErrorResponse(e) => {
            let _ = out.push(GattClientEvent::ErrorResponse {
                conn_handle: e.conn_handle,
                request_opcode: e.request as u8,
                attribute_handle: e.attribute_handle.0,
                error_code: e.error as u8,
            });
        }
        _ => {}
    }

    out
}
