= Project Structure

There are many ways to configure embassy and its components for your exact application. The link:https://github.com/embassy-rs/embassy/tree/main/examples[examples] directory for each chipset demonstrates how your project structure should look. Let's break it down:

The toplevel file structure of your project should look like this:
[source,plain]
----
{} = Maybe

my-project
|- .cargo
|  |- config.toml
|- src
|  |- main.rs
|- build.rs
|- Cargo.toml
|- {memory.x}
|- rust-toolchain.toml
----

== .cargo/config.toml

This directory/file describes what platform you're on, and configures link:https://github.com/probe-rs/probe-rs[probe-rs] to deploy to your device.

Here is a minimal example:

[source,toml]
----
[target.thumbv6m-none-eabi] # <-change for your platform
runner = 'probe-rs run --chip STM32F031K6Tx' # <- change for your chip

[build]
target = "thumbv6m-none-eabi" # <-change for your platform

[env]
DEFMT_LOG = "trace" # <- can change to info, warn, or error
----

== build.rs

This is the build script for your project. It links defmt (what is link:https://defmt.ferrous-systems.com[defmt]?) and the `memory.x` file if needed. This file is pretty specific for each chipset, just copy and paste from the corresponding link:https://github.com/embassy-rs/embassy/tree/main/examples[example].

== Cargo.toml

This is your manifest file, where you can configure all of the embassy components and appropriate features.

Features enable certain capabilities for time-keeping, hardware access, logging, etc.

=== Features

==== embassy-executor

**executor-interrupt**

Enables the ability to drive an executor with an interrupt.

> Example: https://github.com/embassy-rs/embassy/blob/main/examples/nrf52840/src/bin/multiprio.rs
> Learn more: https://embassy.dev/book/dev/runtime.html#_interrupts

**task-arena-size-?** - *Default:* `task-arena-size-4096`

Configures the task arena size available to the executor.

> Learn more: https://embassy.dev/book/dev/faq.html#_how_do_i_set_up_the_task_arenas_on_stable

==== embassy-time

**tick-hz-?**

Configures the tick rate of the active time driver.

> This **must** be specified as the default of `1MHz` is not operational.
> A typical value is `tick-hz-32_768` but this should be set appropriately for the application.
> Learn more: https://github.com/embassy-rs/embassy/tree/main/embassy-time#tick-rate

**defmt-timestamp-uptime**

Enables the reporting of the uptime (seconds) in RTT messages.

==== embassy-stm32

**exti**

Enables the use of the EXTI peripheral.

> Example: https://github.com/embassy-rs/embassy/blob/main/examples/stm32g4/src/bin/button_exti.rs

**time-driver-?**

Configures the time driver to be provided to `embassy-time`.

> An exact timer to be used can be specified with `time-driver-timX` where `X` is the timer number.
> `embassy-stm32` can pick a time driver itself with `time-driver-any`.
> Learn more: https://github.com/embassy-rs/embassy/tree/18da9a2b66f21a1d1b5cd07c8567b700be8c7b09/embassy-stm32#embassy-time-time-driver

**time**

Enables additional time related functionality.

> In general, enables timouts for IO transactions.

==== embassy-nrf

**time-driver-rtc1**

Configures the time driver to be provided to `embassy-time`.

> Only one timer (`RTC1`) is available as a time driver.
> Learn more: https://github.com/embassy-rs/embassy/tree/18da9a2b66f21a1d1b5cd07c8567b700be8c7b09/embassy-nrf#time-driver

**time**

Enables additional time related functionality.

> In general, enables timouts for IO transactions.

== memory.x

This file outlines the flash/ram usage of your program. It is especially useful when using link:https://github.com/embassy-rs/nrf-softdevice[nrf-softdevice] on an nRF5x.

Here is an example for using S140 with an nRF52840:

[source,x]
----
MEMORY
{
  /* NOTE 1 K = 1 KiBi = 1024 bytes */
  /* These values correspond to the NRF52840 with Softdevices S140 7.0.1 */
  FLASH : ORIGIN = 0x00027000, LENGTH = 868K
  RAM : ORIGIN = 0x20020000, LENGTH = 128K
}
----

== rust-toolchain.toml

This file configures the rust version and configuration to use.

A minimal example:

[source,toml]
----
[toolchain]
channel = "nightly-2023-08-19" # <- as of writing, this is the exact rust version embassy uses
components = [ "rust-src", "rustfmt" ] # <- optionally add "llvm-tools-preview" for some extra features like "cargo size"
targets = [
    "thumbv6m-none-eabi" # <-change for your platform
]
----
