//! Split-build traits: the interface between `configure_pins`' closure tuple
//! and the shape-dependent split structs. The split structs, selectors and
//! `ChannelCfgTuple` impls are generated by `build.rs` (see
//! `src/dfsdm/codegen.rs`) and glob-re-exported from `crate::_generated::dfsdm`.

use super::*;

// =============================================================================
// SplitBuild - filter-count dispatch, one trait per channel arity
// =============================================================================

/// Builds the actual split struct from already-extracted pin pairs.
pub trait Tcv2SplitBuild<T: Instance, C: ClockOutputMode, S0: PinSet, S1: PinSet> {
    /// The split struct for this (transceiver, filter) shape.
    type Out;

    /// Registers the pins with `common` and constructs the split.
    fn build<'d>(
        common: &mut DfsdmCommon<'d, T, Enabled>,
        ch0: (S0::Datin<'d>, S0::Ckin<'d>),
        ch1: (S1::Datin<'d>, S1::Ckin<'d>),
    ) -> Self::Out;
}

/// 4-transceiver twin of [`Tcv2SplitBuild`].
pub trait Tcv4SplitBuild<T: Instance, C: ClockOutputMode, S0: PinSet, S1: PinSet, S2: PinSet, S3: PinSet> {
    /// The split struct for this (transceiver, filter) shape.
    type Out;

    /// Registers the pins with `common` and constructs the split.
    fn build<'d>(
        common: &mut DfsdmCommon<'d, T, Enabled>,
        ch0: (S0::Datin<'d>, S0::Ckin<'d>),
        ch1: (S1::Datin<'d>, S1::Ckin<'d>),
        ch2: (S2::Datin<'d>, S2::Ckin<'d>),
        ch3: (S3::Datin<'d>, S3::Ckin<'d>),
    ) -> Self::Out;
}

/// 8-transceiver twin of [`Tcv2SplitBuild`].
pub trait Tcv8SplitBuild<
    T: Instance,
    C: ClockOutputMode,
    S0: PinSet,
    S1: PinSet,
    S2: PinSet,
    S3: PinSet,
    S4: PinSet,
    S5: PinSet,
    S6: PinSet,
    S7: PinSet,
>
{
    /// The split struct for this (transceiver, filter) shape.
    type Out;

    /// Registers the pins with `common` and constructs the split.
    ///
    /// The eight `(datin, ckin)` tuples are the point of the API: they carry
    /// each channel's type-level pin pair, so the arity is load-bearing.
    #[allow(clippy::too_many_arguments)]
    fn build<'d>(
        common: &mut DfsdmCommon<'d, T, Enabled>,
        ch0: (S0::Datin<'d>, S0::Ckin<'d>),
        ch1: (S1::Datin<'d>, S1::Ckin<'d>),
        ch2: (S2::Datin<'d>, S2::Ckin<'d>),
        ch3: (S3::Datin<'d>, S3::Ckin<'d>),
        ch4: (S4::Datin<'d>, S4::Ckin<'d>),
        ch5: (S5::Datin<'d>, S5::Ckin<'d>),
        ch6: (S6::Datin<'d>, S6::Ckin<'d>),
        ch7: (S7::Datin<'d>, S7::Ckin<'d>),
    ) -> Self::Out;
}

// =============================================================================
// Channel-config tuples - the split entry point
// =============================================================================

/// Implemented for the tuple a `configure_pins` closure returns.
/// The arity *is* the transceiver-count check: `(C0, C1)` only impls for
/// `Tcv2` instances, the 8-tuple only for `Tcv8`.
#[diagnostic::on_unimplemented(
    message = "the closure must return one pin token per transceiver of `{T}`",
    label = "tuple length doesn't match `{T}`'s transceiver count",
    note = "check `{T}`'s transceiver count and return a tuple of that length, one token per `creator.chN`"
)]
pub trait ChannelCfgTuple<'d, T: Instance, C: ClockOutputMode> {
    /// The fully-wired split (neighbor pin-sets already correct).
    type Split;

    /// Consumes the tuple and builds the split.
    fn split_parts(self, common: &mut DfsdmCommon<'d, T, Enabled>) -> Self::Split;
}
