//! USB 2.0 device driver for the MCXA5xx USBHS controller.
//!
//! The MCXA5xx exposes a single Chipidea/EHCI USB-OTG core (`USB1_HS`) with an
//! integrated high-speed PHY. This driver operates that core in **device mode**
//! and forces **full speed** (12 Mbit/s) operation, which is the configuration
//! used by simple USB device classes such as HID.
//!
//! It implements the [`embassy_usb_driver`] traits so it can be used directly
//! with `embassy-usb` (e.g. the HID class).
//!
//! # Board clocking
//! The MCXA577 USBHS PHY expects the board clock tree to match the SDK/Zephyr
//! profile used by FRDM-MCXA577: over-drive voltage mode with the 24 MHz SOSC
//! crystal enabled. [`Driver::new`] asserts if the USBPHY PLL does not lock, so
//! a missing board-level clock/voltage setup fails loudly during initialization.
//!
//! # Limitations
//! - Device mode only (no host / OTG role switching).
//! - Forced full speed; high-speed operation is not exposed.
//! - No hardware VBUS detection yet; the bus reports power detected at startup.
//! - Remote wakeup is not implemented.
//! - Isochronous endpoints and packet sizes greater than 64 bytes are not
//!   supported.
//! - One transfer descriptor in flight per endpoint direction at a time.
//!
//! # Register access
//! MMIO register blocks come from `nxp-pac`. The local [`registers`] module only
//! contains EHCI DMA structures and bit masks that are not generated by the PAC.

mod clock;
mod registers;

use core::cell::UnsafeCell;
use core::future::poll_fn;
use core::marker::PhantomData;
use core::sync::atomic::{AtomicBool, AtomicU8, AtomicU16, Ordering};
use core::task::Poll;

use cortex_m::asm;
use embassy_hal_internal::{Peri, PeripheralType};
use embassy_sync::waitqueue::AtomicWaker;
use embassy_usb_driver::{
    Direction, EndpointAddress, EndpointAllocError, EndpointError, EndpointInfo, EndpointType, Event, Unsupported,
};

pub use clock::PhyConfig;

use crate::interrupt;
use crate::interrupt::typelevel::{Binding, Interrupt};

use registers::{
    DEVICEADDR_USBADR_SHIFT, DEVICEADDR_USBADRA, DTD_BUFFER_PAGE_MASK, DTD_BUFFER_PAGE_SIZE, DTD_NEXT_TERMINATE,
    DTD_TOKEN_ACTIVE, DTD_TOKEN_ERROR_MASK, DTD_TOKEN_IOC, DTD_TOKEN_TOTAL_MASK, DTD_TOKEN_TOTAL_SHIFT, EPCTRL_RXE,
    EPCTRL_RXR, EPCTRL_RXS, EPCTRL_RXT_SHIFT, EPCTRL_TXE, EPCTRL_TXR, EPCTRL_TXS, EPCTRL_TXT_SHIFT, PORTSC1_PFSC,
    QH_CAP_IOS, QH_CAP_MAXLEN_SHIFT, QH_CAP_ZLT, QueueHead, TransferDescriptor, USBCMD_RS, USBCMD_RST, USBCMD_SUTW,
    USBMODE_CM_DEVICE, USBMODE_SLOM, USBSTS_PCI, USBSTS_SLI, USBSTS_UEI, USBSTS_UI, USBSTS_URI,
};

/// USBHS device-driver configuration.
///
/// The controller is currently always placed in device mode and forced to
/// full-speed operation. The configuration carries board-specific PHY trim and
/// PLL settings so applications can use the FRDM-MCXA577 defaults or provide
/// calibrated values from their board support package.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[non_exhaustive]
pub struct Config {
    /// USBPHY trim and PLL settings.
    pub phy: PhyConfig,
}

impl Default for Config {
    fn default() -> Self {
        Self {
            phy: PhyConfig::default(),
        }
    }
}

impl From<PhyConfig> for Config {
    fn from(phy: PhyConfig) -> Self {
        Self { phy }
    }
}

/// Number of bidirectional endpoint pairs supported (EP0..EP{N-1}).
///
/// The MCXA577 USBHS controller exposes eight bidirectional endpoint pairs.
const EP_COUNT: usize = 8;

/// Maximum packet size for a full-speed endpoint.
const FS_MAX_PACKET: u16 = 64;
const ENDPOINT_TYPE_UNALLOCATED: u8 = 0xFF;
const ALL_USBSTS: u32 = 0xFFFF_FFFF;
const ALL_ENDPOINT_BITS: u32 = 0xFFFF_FFFF;
const DEFAULT_BURST_SIZE: u32 = (0x10 << 8) | 0x10;

/// Static DMA memory cell.
///
/// The USBHS controller reads and writes these objects directly. This wrapper
/// keeps the global mutability localized and makes all access sites spell out
/// their raw-pointer safety instead of exposing `static mut` items throughout
/// the driver.
struct DmaCell<T>(UnsafeCell<T>);

impl<T> DmaCell<T> {
    const fn new(value: T) -> Self {
        Self(UnsafeCell::new(value))
    }

    #[inline]
    fn as_ptr(&self) -> *mut T {
        self.0.get()
    }
}

// SAFETY: USB driver ownership plus per-endpoint transfer ownership serialize
// mutable access. The controller may access the memory concurrently as DMA, so
// all synchronization with hardware is done with explicit barriers.
unsafe impl<T> Sync for DmaCell<T> {}

// ---- DMA-visible controller structures (statically allocated) ----
//
// MCXA577 SRAM is treated as non-cacheable by the current MCX-A target setup.
// If this driver is reused on a target with data-cacheable SRAM, these
// descriptors and bounce buffers must either be placed in a non-cacheable
// section or wrapped with explicit cache clean/invalidate operations.
//
// The MCXA5xx family exposes one USBHS controller. These DMA structures,
// wakers, and flags are therefore module-static; the `Instance` trait keeps the
// public API aligned with Embassy's interrupt-binding style, not multi-instance
// USBHS support.

/// The device queue-head list. Must be 2 KiB aligned and contain `2 * EP_COUNT`
/// entries (OUT at even indices, IN at odd indices).
#[repr(C, align(2048))]
struct QhList {
    qh: [QueueHead; EP_COUNT * 2],
}

/// One transfer descriptor per endpoint direction.
#[repr(C, align(32))]
struct DtdList {
    dtd: [TransferDescriptor; EP_COUNT * 2],
}

static QH_LIST: DmaCell<QhList> = DmaCell::new(QhList {
    qh: [QueueHead::new(); EP_COUNT * 2],
});
static DTD_LIST: DmaCell<DtdList> = DmaCell::new(DtdList {
    dtd: [TransferDescriptor::new(); EP_COUNT * 2],
});

/// Per-endpoint-direction transfer-complete wakers (index = `2*ep + dir`).
static EP_WAKERS: [AtomicWaker; EP_COUNT * 2] = [const { AtomicWaker::new() }; EP_COUNT * 2];
/// Waker for bus events (reset/suspend/resume) handled in [`Bus::poll`].
static BUS_WAKER: AtomicWaker = AtomicWaker::new();

/// Bus event flags set by the interrupt handler and consumed by [`Bus::poll`].
static FLAG_RESET: AtomicBool = AtomicBool::new(false);
static FLAG_SUSPEND: AtomicBool = AtomicBool::new(false);
static FLAG_RESUME: AtomicBool = AtomicBool::new(false);
static FLAG_SETUP: AtomicBool = AtomicBool::new(false);

/// Per-endpoint-direction configuration captured at allocation time and applied
/// by [`Bus::endpoint_set_enabled`] (index = `2*ep + dir`).
static EP_MAX_PACKET: [AtomicU16; EP_COUNT * 2] = [const { AtomicU16::new(0) }; EP_COUNT * 2];
static EP_TYPE: [AtomicU8; EP_COUNT * 2] = [const { AtomicU8::new(ENDPOINT_TYPE_UNALLOCATED) }; EP_COUNT * 2];

#[derive(Clone, Copy)]
struct EndpointSlot {
    index: usize,
    dir: Direction,
}

impl EndpointSlot {
    #[inline]
    fn new(index: usize, dir: Direction) -> Self {
        Self { index, dir }
    }

    #[inline]
    fn from_addr(addr: EndpointAddress) -> Self {
        let dir = if addr.is_in() { Direction::In } else { Direction::Out };
        Self::new(addr.index(), dir)
    }

    #[inline]
    fn array_index(self) -> usize {
        self.index * 2 + self.dir_index()
    }

    #[inline]
    fn dir_index(self) -> usize {
        match self.dir {
            Direction::Out => 0,
            Direction::In => 1,
        }
    }

    #[inline]
    #[cfg_attr(not(feature = "defmt"), allow(dead_code))]
    fn dir_num(self) -> u8 {
        self.dir_index() as u8
    }

    #[inline]
    fn endpoint_bit(self) -> u32 {
        match self.dir {
            Direction::Out => 1 << self.index,
            Direction::In => 1 << (self.index + 16),
        }
    }

    #[inline]
    fn is_enabled(self, r: UsbRegs) -> bool {
        r.endptctrl(self.index) & endpoint_enable_bit(self) != 0
    }

    #[inline]
    fn waker(self) -> &'static AtomicWaker {
        &EP_WAKERS[self.array_index()]
    }
}

#[inline]
fn endpoint_type_bits(ep_type: EndpointType) -> u32 {
    match ep_type {
        EndpointType::Control => 0b00,
        EndpointType::Isochronous => 0b01,
        EndpointType::Bulk => 0b10,
        EndpointType::Interrupt => 0b11,
    }
}

#[inline]
fn endpoint_ctrl_enable_bits(slot: EndpointSlot, ep_type: EndpointType) -> (u32, u32) {
    let ty = endpoint_type_bits(ep_type);
    match slot.dir {
        Direction::Out => (
            0b11 << EPCTRL_RXT_SHIFT,
            (ty << EPCTRL_RXT_SHIFT) | EPCTRL_RXE | EPCTRL_RXR,
        ),
        Direction::In => (
            0b11 << EPCTRL_TXT_SHIFT,
            (ty << EPCTRL_TXT_SHIFT) | EPCTRL_TXE | EPCTRL_TXR,
        ),
    }
}

#[inline]
fn endpoint_stall_bit(slot: EndpointSlot) -> u32 {
    match slot.dir {
        Direction::Out => EPCTRL_RXS,
        Direction::In => EPCTRL_TXS,
    }
}

#[inline]
fn endpoint_enable_bit(slot: EndpointSlot) -> u32 {
    match slot.dir {
        Direction::Out => EPCTRL_RXE,
        Direction::In => EPCTRL_TXE,
    }
}

#[inline]
fn qh_ptr() -> *mut [QueueHead; EP_COUNT * 2] {
    // SAFETY: only constructs a raw pointer to DMA-owned static memory.
    unsafe { core::ptr::addr_of_mut!((*QH_LIST.as_ptr()).qh) }
}

#[inline]
fn dtd_ptr() -> *mut [TransferDescriptor; EP_COUNT * 2] {
    // SAFETY: only constructs a raw pointer to DMA-owned static memory.
    unsafe { core::ptr::addr_of_mut!((*DTD_LIST.as_ptr()).dtd) }
}

#[inline]
fn ep_buffer_ptr(slot: EndpointSlot) -> *mut u8 {
    // SAFETY: only constructs a raw pointer to the endpoint's dedicated bounce
    // buffer. The endpoint future owns that slot while the transfer is active.
    unsafe { core::ptr::addr_of_mut!((*EP_BUFFERS.as_ptr()).buf[slot.array_index()]) as *mut u8 }
}

/// Controller register handle.
#[derive(Clone, Copy)]
struct UsbRegs(crate::pac::usbhs::Usbhs);

impl UsbRegs {
    #[inline]
    #[cfg_attr(not(feature = "defmt"), allow(dead_code))]
    fn id(self) -> u32 {
        self.0.ID().read().0
    }

    #[inline]
    fn usbcmd(self) -> u32 {
        self.0.USBCMD().read().0
    }

    #[inline]
    fn set_usbcmd(self, bits: u32) {
        self.0.USBCMD().write(|w| w.0 = bits);
    }

    #[inline]
    fn modify_usbcmd(self, f: impl FnOnce(u32) -> u32) {
        self.set_usbcmd(f(self.usbcmd()));
    }

    #[inline]
    fn usbsts(self) -> u32 {
        self.0.USBSTS().read().0
    }

    #[inline]
    fn clear_usbsts(self, bits: u32) {
        self.0.USBSTS().write(|w| w.0 = bits);
    }

    #[inline]
    fn usbintr(self) -> u32 {
        self.0.USBINTR().read().0
    }

    #[inline]
    fn set_usbintr(self, bits: u32) {
        self.0.USBINTR().write(|w| w.0 = bits);
    }

    #[inline]
    fn set_deviceaddr(self, bits: u32) {
        self.0.DEVICEADDR().write(|w| w.0 = bits);
    }

    #[inline]
    fn set_endptlistaddr(self, bits: u32) {
        self.0.ENDPTLISTADDR().write(|w| w.0 = bits);
    }

    #[inline]
    fn set_burstsize(self, bits: u32) {
        self.0.BURSTSIZE().write(|w| w.0 = bits);
    }

    #[inline]
    fn portsc1(self) -> u32 {
        self.0.PORTSC1().read().0
    }

    #[inline]
    fn set_portsc1(self, bits: u32) {
        self.0.PORTSC1().write(|w| w.0 = bits);
    }

    #[inline]
    fn modify_portsc1(self, f: impl FnOnce(u32) -> u32) {
        self.set_portsc1(f(self.portsc1()));
    }

    #[inline]
    fn set_usbmode(self, bits: u32) {
        self.0.USBMODE().write(|w| w.0 = bits);
    }

    #[inline]
    fn endptsetupstat(self) -> u32 {
        self.0.ENDPTSETUPSTAT().read().0
    }

    #[inline]
    fn clear_endptsetupstat(self, bits: u32) {
        self.0.ENDPTSETUPSTAT().write(|w| w.0 = bits);
    }

    #[inline]
    fn endptprime(self) -> u32 {
        self.0.ENDPTPRIME().read().0
    }

    #[inline]
    fn set_endptprime(self, bits: u32) {
        self.0.ENDPTPRIME().write(|w| w.0 = bits);
    }

    #[inline]
    fn endptflush(self) -> u32 {
        self.0.ENDPTFLUSH().read().0
    }

    #[inline]
    fn set_endptflush(self, bits: u32) {
        self.0.ENDPTFLUSH().write(|w| w.0 = bits);
    }

    #[inline]
    fn endptcomplete(self) -> u32 {
        self.0.ENDPTCOMPLETE().read().0
    }

    #[inline]
    fn clear_endptcomplete(self, bits: u32) {
        self.0.ENDPTCOMPLETE().write(|w| w.0 = bits);
    }

    #[inline]
    fn endptctrl(self, index: usize) -> u32 {
        match index {
            0 => self.0.ENDPTCTRL0().read().0,
            1 => self.0.ENDPTCTRL1().read().0,
            2 => self.0.ENDPTCTRL2().read().0,
            3 => self.0.ENDPTCTRL3().read().0,
            4 => self.0.ENDPTCTRL4().read().0,
            5 => self.0.ENDPTCTRL5().read().0,
            6 => self.0.ENDPTCTRL6().read().0,
            7 => self.0.ENDPTCTRL7().read().0,
            _ => unreachable!(),
        }
    }

    #[inline]
    fn set_endptctrl(self, index: usize, bits: u32) {
        match index {
            0 => self.0.ENDPTCTRL0().write(|w| w.0 = bits),
            1 => self.0.ENDPTCTRL1().write(|w| w.0 = bits),
            2 => self.0.ENDPTCTRL2().write(|w| w.0 = bits),
            3 => self.0.ENDPTCTRL3().write(|w| w.0 = bits),
            4 => self.0.ENDPTCTRL4().write(|w| w.0 = bits),
            5 => self.0.ENDPTCTRL5().write(|w| w.0 = bits),
            6 => self.0.ENDPTCTRL6().write(|w| w.0 = bits),
            7 => self.0.ENDPTCTRL7().write(|w| w.0 = bits),
            _ => unreachable!(),
        }
    }

    #[inline]
    fn modify_endptctrl(self, index: usize, f: impl FnOnce(u32) -> u32) {
        self.set_endptctrl(index, f(self.endptctrl(index)));
    }
}

#[inline]
fn regs() -> UsbRegs {
    UsbRegs(crate::pac::USB1)
}

#[inline]
fn control_setup_pending() -> bool {
    FLAG_SETUP.load(Ordering::Relaxed) || regs().endptsetupstat() & 1 != 0
}

#[inline]
fn dma_write_barrier() {
    // The SDK either places USB data in non-cacheable memory or performs cache
    // maintenance around transfers. MCXA577's current Embassy memory map does
    // not enable a data cache for these buffers, so a memory barrier is enough
    // to order descriptor/buffer writes before the controller fetches them.
    asm::dsb();
}

#[inline]
fn dma_read_barrier() {
    // Order CPU reads after controller DMA writes. If this driver is ported to
    // a cacheable memory region, cache invalidation belongs next to this call.
    asm::dsb();
}

// =========================================================================
// Interrupt handler
// =========================================================================

/// Interrupt handler for the USB controller.
///
/// Bind this with [`crate::bind_interrupts!`] to the `USB1_HS` interrupt.
pub struct InterruptHandler<T: Instance> {
    _phantom: PhantomData<T>,
}

impl<T: Instance> interrupt::typelevel::Handler<T::Interrupt> for InterruptHandler<T> {
    unsafe fn on_interrupt() {
        let r = regs();
        let status = r.usbsts() & r.usbintr();
        // Acknowledge all handled sources (write-1-to-clear).
        r.clear_usbsts(status);

        if status & USBSTS_URI != 0 {
            FLAG_RESET.store(true, Ordering::Relaxed);
            BUS_WAKER.wake();
        }
        if status & USBSTS_SLI != 0 {
            FLAG_SUSPEND.store(true, Ordering::Relaxed);
            BUS_WAKER.wake();
        }
        if status & USBSTS_PCI != 0 {
            // Port change: treat as resume notification.
            FLAG_RESUME.store(true, Ordering::Relaxed);
            BUS_WAKER.wake();
        }

        if status & USBSTS_UI != 0 {
            // Endpoint transfer(s) and/or setup packet(s) complete.
            // Wake setup/OUT/IN waiters; the futures re-check hardware state.
            let setup = r.endptsetupstat();
            let complete = r.endptcomplete();
            if setup != 0 {
                FLAG_SETUP.store(true, Ordering::Relaxed);
            }
            if complete != 0 {
                r.clear_endptcomplete(complete);
            }
            for ep in 0..EP_COUNT {
                let out = EndpointSlot::new(ep, Direction::Out);
                let in_ = EndpointSlot::new(ep, Direction::In);
                if setup & (1 << ep) != 0 || complete & out.endpoint_bit() != 0 {
                    out.waker().wake();
                }
                if complete & in_.endpoint_bit() != 0 {
                    in_.waker().wake();
                }
            }
        }

        // Mask further interrupts are not needed: sources are level and cleared above.
        T::Interrupt::unpend();
    }
}

// =========================================================================
// Instance trait
// =========================================================================

trait SealedInstance {}

/// USB peripheral instance.
#[allow(private_bounds)]
pub trait Instance: SealedInstance + PeripheralType + 'static {
    /// Interrupt for this USB instance.
    type Interrupt: interrupt::typelevel::Interrupt;
}

impl SealedInstance for crate::peripherals::USB1 {}
impl Instance for crate::peripherals::USB1 {
    type Interrupt = crate::interrupt::typelevel::USB1_HS;
}

type UsbInterrupt = crate::interrupt::typelevel::USB1_HS;

/// Marker for OUT endpoints.
pub enum Out {}
/// Marker for IN endpoints.
pub enum In {}

trait EndpointDir {
    const DIR: Direction;
}

impl EndpointDir for Out {
    const DIR: Direction = Direction::Out;
}

impl EndpointDir for In {
    const DIR: Direction = Direction::In;
}

#[derive(Clone, Copy)]
struct EndpointConfig {
    ep_type: EndpointType,
    max_packet_size: u16,
}

impl EndpointConfig {
    #[inline]
    fn store(self, slot: EndpointSlot) {
        let i = slot.array_index();
        EP_MAX_PACKET[i].store(self.max_packet_size, Ordering::Relaxed);
        EP_TYPE[i].store(self.ep_type as u8, Ordering::Relaxed);
    }

    #[inline]
    fn load(slot: EndpointSlot) -> Option<Self> {
        let i = slot.array_index();
        let ep_type = match EP_TYPE[i].load(Ordering::Relaxed) {
            0 => EndpointType::Control,
            1 => EndpointType::Isochronous,
            2 => EndpointType::Bulk,
            3 => EndpointType::Interrupt,
            _ => return None,
        };
        let max_packet_size = EP_MAX_PACKET[i].load(Ordering::Relaxed);
        (max_packet_size != 0).then_some(Self {
            ep_type,
            max_packet_size,
        })
    }
}

// =========================================================================
// Driver
// =========================================================================

/// USB device driver.
pub struct Driver<'d> {
    _phantom: PhantomData<&'d mut crate::peripherals::USB1>,
    alloc_out: u8,
    alloc_in: u8,
}

impl<'d> Driver<'d> {
    /// Create a new USB device driver, forced to full speed.
    ///
    /// This enables the USB clocks, brings up the PHY, and resets the controller
    /// into device mode. The controller starts detached; the `embassy-usb` stack
    /// attaches it via [`embassy_usb_driver::Bus::enable`].
    pub fn new<T: Instance>(
        _usb: Peri<'d, T>,
        _irq: impl Binding<T::Interrupt, InterruptHandler<T>>,
        config: impl Into<Config>,
    ) -> Self {
        let config = config.into();
        #[cfg(feature = "defmt")]
        defmt::trace!(
            "usb: init phy pll_div={=u32} d_cal={=u32} txcal45dp={=u32} txcal45dm={=u32}",
            config.phy.pll_div_sel,
            config.phy.d_cal,
            config.phy.txcal45dp,
            config.phy.txcal45dm
        );
        // SAFETY: we own the USB peripheral and bring up its clocks/PHY once.
        unsafe {
            clock::init_clocks_and_phy(&config.phy);
        }
        reset_controller();

        // EP0 (control) is implicitly allocated.
        Self {
            _phantom: PhantomData,
            alloc_out: 1 << 0,
            alloc_in: 1 << 0,
        }
    }

    fn alloc_endpoint<D: EndpointDir>(
        &mut self,
        ep_type: EndpointType,
        ep_addr: Option<EndpointAddress>,
        max_packet_size: u16,
        interval_ms: u8,
    ) -> Result<Endpoint<D>, EndpointAllocError> {
        if ep_type == EndpointType::Control
            || ep_type == EndpointType::Isochronous
            || max_packet_size == 0
            || max_packet_size > FS_MAX_PACKET
        {
            return Err(EndpointAllocError);
        }

        let is_in = D::DIR == Direction::In;
        let alloc = if is_in { &mut self.alloc_in } else { &mut self.alloc_out };

        let index = match ep_addr {
            Some(addr) => {
                let i = addr.index();
                if addr.is_in() != is_in || i == 0 || i >= EP_COUNT || (*alloc & (1 << i)) != 0 {
                    return Err(EndpointAllocError);
                }
                i
            }
            None => {
                // Endpoint 0 is reserved for control transfers.
                let mut found = None;
                for i in 1..EP_COUNT {
                    if *alloc & (1 << i) == 0 {
                        found = Some(i);
                        break;
                    }
                }
                found.ok_or(EndpointAllocError)?
            }
        };

        *alloc |= 1 << index;

        let addr = EndpointAddress::from_parts(index, D::DIR);
        let slot = EndpointSlot::from_addr(addr);
        EndpointConfig {
            ep_type,
            max_packet_size,
        }
        .store(slot);

        #[cfg(feature = "defmt")]
        defmt::trace!(
            "usb: alloc ep{=usize} dir={=u8} type={=u8} mps={=u16} interval={=u8}",
            index,
            slot.dir_num(),
            endpoint_type_bits(ep_type) as u8,
            max_packet_size,
            interval_ms
        );

        Ok(Endpoint {
            _phantom: PhantomData,
            info: EndpointInfo {
                addr,
                ep_type,
                max_packet_size,
                interval_ms,
            },
        })
    }
}

impl<'d> embassy_usb_driver::Driver<'d> for Driver<'d> {
    type EndpointOut = Endpoint<Out>;
    type EndpointIn = Endpoint<In>;
    type ControlPipe = ControlPipe;
    type Bus = Bus;

    fn alloc_endpoint_out(
        &mut self,
        ep_type: EndpointType,
        ep_addr: Option<EndpointAddress>,
        max_packet_size: u16,
        interval_ms: u8,
    ) -> Result<Self::EndpointOut, EndpointAllocError> {
        self.alloc_endpoint::<Out>(ep_type, ep_addr, max_packet_size, interval_ms)
    }

    fn alloc_endpoint_in(
        &mut self,
        ep_type: EndpointType,
        ep_addr: Option<EndpointAddress>,
        max_packet_size: u16,
        interval_ms: u8,
    ) -> Result<Self::EndpointIn, EndpointAllocError> {
        self.alloc_endpoint::<In>(ep_type, ep_addr, max_packet_size, interval_ms)
    }

    fn start(self, control_max_packet_size: u16) -> (Self::Bus, Self::ControlPipe) {
        // Configure the control endpoint queue heads.
        init_control_qh(control_max_packet_size);

        let bus = Bus {
            inited: false,
            control_max_packet_size,
        };
        let control = ControlPipe {
            max_packet_size: control_max_packet_size,
        };
        (bus, control)
    }
}

// =========================================================================
// Controller bring-up helpers
// =========================================================================

/// Reset the controller and place it in device mode (detached, full speed).
fn reset_controller() {
    let r = regs();

    // Stop the controller, then issue a controller reset and wait for it.
    r.modify_usbcmd(|v| v & !USBCMD_RS);
    r.modify_usbcmd(|v| v | USBCMD_RST);
    while r.usbcmd() & USBCMD_RST != 0 {}

    // Device mode, setup-lockout off (we use the setup tripwire instead).
    r.set_usbmode(USBMODE_CM_DEVICE | USBMODE_SLOM);

    // Force full speed.
    r.modify_portsc1(|v| v | PORTSC1_PFSC);

    // Program the endpoint list base.
    let qh_addr = QH_LIST.as_ptr() as u32;
    r.set_endptlistaddr(qh_addr);

    #[cfg(feature = "defmt")]
    defmt::trace!("usb: controller reset id=0x{=u32:08x} qh=0x{=u32:08x}", r.id(), qh_addr);

    // Reasonable default burst size.
    r.set_burstsize(DEFAULT_BURST_SIZE);

    // Clear any pending status, leave interrupts disabled until `enable`.
    r.clear_usbsts(ALL_USBSTS);
    r.set_usbintr(0);
}

/// Initialize the control-endpoint (EP0) queue heads. Called once during `start`.
fn init_control_qh(mps: u16) {
    // SAFETY: exclusive access during start-up; QH list is owned by the driver.
    unsafe {
        let qh = qh_ptr();
        // Disable automatic ZLP termination. `embassy-usb` requests status/ZLP
        // packets explicitly via the control pipe and endpoint transfers.
        // OUT QH[0]: interrupt-on-setup so SETUP packets notify us.
        (*qh)[0].capabilities = ((mps as u32) << QH_CAP_MAXLEN_SHIFT) | QH_CAP_IOS | QH_CAP_ZLT;
        (*qh)[0].next_dtd = DTD_NEXT_TERMINATE;
        // IN QH[1].
        (*qh)[1].capabilities = ((mps as u32) << QH_CAP_MAXLEN_SHIFT) | QH_CAP_ZLT;
        (*qh)[1].next_dtd = DTD_NEXT_TERMINATE;
    }

    let r = regs();
    r.modify_endptctrl(0, |v| {
        (v & !(EPCTRL_TXS | EPCTRL_RXS)) | EPCTRL_RXE | EPCTRL_TXE | EPCTRL_RXR | EPCTRL_TXR
    });
}

// =========================================================================
// Endpoint
// =========================================================================

/// A USB endpoint.
pub struct Endpoint<D> {
    _phantom: PhantomData<D>,
    info: EndpointInfo,
}

/// Configure an endpoint's queue head and control register.
fn configure_endpoint(addr: EndpointAddress, ep_type: EndpointType, mps: u16) {
    let index = addr.index();
    let slot = EndpointSlot::from_addr(addr);
    let qhi = slot.array_index();

    // SAFETY: queue-head list is owned by the driver; exclusive access here.
    unsafe {
        let qh = qh_ptr();
        // Disable automatic ZLP termination. The USB stack explicitly requests
        // short/ZLP packets when the class transfer needs one.
        (*qh)[qhi].capabilities = ((mps as u32) << QH_CAP_MAXLEN_SHIFT) | QH_CAP_ZLT;
        (*qh)[qhi].next_dtd = DTD_NEXT_TERMINATE;
        (*qh)[qhi].token = 0;
    }

    let r = regs();
    let (type_mask, enable_bits) = endpoint_ctrl_enable_bits(slot, ep_type);
    #[cfg(feature = "defmt")]
    defmt::trace!(
        "usb: configure ep{=usize} dir={=u8} type={=u8} mps={=u16}",
        index,
        slot.dir_num(),
        endpoint_type_bits(ep_type) as u8,
        mps
    );
    r.modify_endptctrl(index, |v| {
        // Reset the data toggle and enable the requested direction.
        (v & !type_mask) | enable_bits
    });
}

impl<D> embassy_usb_driver::Endpoint for Endpoint<D> {
    fn info(&self) -> &EndpointInfo {
        &self.info
    }

    async fn wait_enabled(&mut self) {
        let slot = EndpointSlot::from_addr(self.info.addr);
        poll_fn(|cx| {
            slot.waker().register(cx.waker());
            let r = regs();
            if slot.is_enabled(r) {
                Poll::Ready(())
            } else {
                Poll::Pending
            }
        })
        .await
    }
}

impl embassy_usb_driver::EndpointOut for Endpoint<Out> {
    async fn read(&mut self, buf: &mut [u8]) -> Result<usize, EndpointError> {
        let index = self.info.addr.index();
        ep_read(index, buf).await
    }
}

impl embassy_usb_driver::EndpointIn for Endpoint<In> {
    async fn write(&mut self, buf: &[u8]) -> Result<(), EndpointError> {
        let index = self.info.addr.index();
        ep_write(index, buf, false).await
    }
}

// =========================================================================
// Low-level transfer primitives (dTD prime + completion wait)
// =========================================================================

/// Prime a transfer descriptor on the given endpoint/direction and wait for it
/// to complete, returning the number of bytes transferred.
async fn ep_transfer(
    slot: EndpointSlot,
    buf_ptr: *mut u8,
    len: usize,
    abort_on_setup: bool,
) -> Result<usize, EndpointError> {
    let dtd_i = slot.array_index();
    let qhi = dtd_i;

    // SAFETY: the descriptor/queue-head for this endpoint direction is owned by
    // the caller for the duration of the transfer.
    unsafe {
        // Build the transfer descriptor.
        let dtd = dtd_ptr();
        (*dtd)[dtd_i].next = DTD_NEXT_TERMINATE;
        (*dtd)[dtd_i].token = ((len as u32) << DTD_TOKEN_TOTAL_SHIFT) | DTD_TOKEN_IOC | DTD_TOKEN_ACTIVE;
        let base = buf_ptr as u32;
        (*dtd)[dtd_i].buffer[0] = base;
        for page in 1..5 {
            (*dtd)[dtd_i].buffer[page] = (base & !DTD_BUFFER_PAGE_MASK) + (page as u32) * DTD_BUFFER_PAGE_SIZE;
        }

        // Link it into the queue head overlay and clear status.
        let qh = qh_ptr();
        (*qh)[qhi].next_dtd = core::ptr::addr_of!((*dtd)[dtd_i]) as u32;
        (*qh)[qhi].token = 0;
    }

    let r = regs();
    let prime_bit = slot.endpoint_bit();

    dma_write_barrier();

    // Prime the endpoint. We allow only one outstanding dTD per endpoint
    // direction, so there is no need to use the add-dTD tripwire (ATDTW).
    r.set_endptprime(prime_bit);
    // Wait until the controller has acknowledged the prime.
    while r.endptprime() & prime_bit != 0 {}

    // Wait for completion via the waker, re-checking the descriptor status.
    let n = poll_fn(|cx| {
        slot.waker().register(cx.waker());
        if !slot.is_enabled(r) {
            return Poll::Ready(Err(EndpointError::Disabled));
        }
        if abort_on_setup && (FLAG_SETUP.load(Ordering::Relaxed) || r.endptsetupstat() & 1 != 0) {
            r.set_endptflush(prime_bit);
            while r.endptflush() & prime_bit != 0 {}
            return Poll::Ready(Err(EndpointError::Disabled));
        }
        dma_read_barrier();
        // SAFETY: reading the (volatile) hardware-updated descriptor token.
        let token = unsafe {
            let dtd = dtd_ptr();
            core::ptr::read_volatile(core::ptr::addr_of!((*dtd)[dtd_i].token))
        };
        if token & DTD_TOKEN_ACTIVE != 0 {
            return Poll::Pending;
        }
        if token & DTD_TOKEN_ERROR_MASK != 0 {
            #[cfg(feature = "defmt")]
            defmt::warn!(
                "usb: transfer error ep{=usize} dir={=u8} token=0x{=u32:08x}",
                slot.index,
                slot.dir_num(),
                token
            );
            return Poll::Ready(Err(EndpointError::Disabled));
        }
        // Remaining bytes are in token[30:16]; transferred = requested - remaining.
        let remaining = (token >> DTD_TOKEN_TOTAL_SHIFT) & DTD_TOKEN_TOTAL_MASK;
        Poll::Ready(Ok(len - remaining as usize))
    })
    .await?;

    Ok(n)
}

/// Static bounce buffers for endpoint transfers (one per endpoint direction),
/// ensuring DMA-visible, suitably-aligned storage.
#[repr(C, align(64))]
struct EpBuffers {
    buf: [[u8; FS_MAX_PACKET as usize]; EP_COUNT * 2],
}
static EP_BUFFERS: DmaCell<EpBuffers> = DmaCell::new(EpBuffers {
    buf: [[0; FS_MAX_PACKET as usize]; EP_COUNT * 2],
});

async fn ep_read(index: usize, buf: &mut [u8]) -> Result<usize, EndpointError> {
    let slot = EndpointSlot::new(index, Direction::Out);
    let bounce = ep_buffer_ptr(slot);
    let cap = FS_MAX_PACKET as usize;
    let n = ep_transfer(slot, bounce, cap, false).await?;
    if n > buf.len() {
        return Err(EndpointError::BufferOverflow);
    }
    // SAFETY: `bounce` is valid for `n` bytes and `buf` for its length.
    unsafe { core::ptr::copy_nonoverlapping(bounce, buf.as_mut_ptr(), n) };
    Ok(n)
}

async fn ep_write(index: usize, buf: &[u8], abort_on_setup: bool) -> Result<(), EndpointError> {
    if buf.len() > FS_MAX_PACKET as usize {
        return Err(EndpointError::BufferOverflow);
    }
    let slot = EndpointSlot::new(index, Direction::In);
    let bounce = ep_buffer_ptr(slot);
    // SAFETY: copying caller data into the owned bounce buffer.
    unsafe { core::ptr::copy_nonoverlapping(buf.as_ptr(), bounce, buf.len()) };
    ep_transfer(slot, bounce, buf.len(), abort_on_setup).await?;
    Ok(())
}

async fn ep_read_control(buf: &mut [u8]) -> Result<usize, EndpointError> {
    let slot = EndpointSlot::new(0, Direction::Out);
    let bounce = ep_buffer_ptr(slot);
    let cap = FS_MAX_PACKET as usize;
    let n = ep_transfer(slot, bounce, cap, true).await?;
    if n > buf.len() {
        return Err(EndpointError::BufferOverflow);
    }
    // SAFETY: `bounce` is valid for `n` bytes and `buf` for its length.
    unsafe { core::ptr::copy_nonoverlapping(bounce, buf.as_mut_ptr(), n) };
    Ok(n)
}

async fn ep_zlp(index: usize, dir: Direction, abort_on_setup: bool) -> Result<(), EndpointError> {
    let slot = EndpointSlot::new(index, dir);
    // EHCI should not dereference buffer pointers for zero-length transfers, but
    // giving it a real aligned address avoids relying on null-pointer behavior.
    let bounce = ep_buffer_ptr(slot);
    ep_transfer(slot, bounce, 0, abort_on_setup).await?;
    Ok(())
}

// =========================================================================
// Control pipe
// =========================================================================

/// Control endpoint (EP0) pipe.
pub struct ControlPipe {
    max_packet_size: u16,
}

impl embassy_usb_driver::ControlPipe for ControlPipe {
    fn max_packet_size(&self) -> usize {
        self.max_packet_size as usize
    }

    async fn setup(&mut self) -> [u8; 8] {
        let r = regs();
        poll_fn(|cx| {
            EndpointSlot::new(0, Direction::Out).waker().register(cx.waker());
            let stat = r.endptsetupstat();
            if stat & 1 == 0 {
                return Poll::Pending;
            }

            // Read the setup packet using the setup tripwire so a back-to-back
            // SETUP cannot corrupt the read.
            let setup = loop {
                r.modify_usbcmd(|v| v | USBCMD_SUTW);
                // SAFETY: control OUT queue head holds the latest setup bytes.
                let bytes = unsafe {
                    let qh = qh_ptr();
                    let w0 = core::ptr::read_volatile(core::ptr::addr_of!((*qh)[0].setup[0]));
                    let w1 = core::ptr::read_volatile(core::ptr::addr_of!((*qh)[0].setup[1]));
                    let mut b = [0u8; 8];
                    b[0..4].copy_from_slice(&w0.to_le_bytes());
                    b[4..8].copy_from_slice(&w1.to_le_bytes());
                    b
                };
                if r.usbcmd() & USBCMD_SUTW != 0 {
                    break bytes;
                }
            };
            r.modify_usbcmd(|v| v & !USBCMD_SUTW);
            // Acknowledge the setup status.
            r.clear_endptsetupstat(stat);
            r.modify_endptctrl(0, |v| v & !(EPCTRL_TXS | EPCTRL_RXS));
            FLAG_SETUP.store(false, Ordering::Relaxed);

            Poll::Ready(setup)
        })
        .await
    }

    async fn data_out(&mut self, buf: &mut [u8], _first: bool, _last: bool) -> Result<usize, EndpointError> {
        // EP0 OUT owned by the control pipe.
        // `embassy-usb-driver` chunks multi-packet control OUT transfers by
        // `max_packet_size()`, so the EP0 bounce buffer only has to hold one
        // full-speed control packet.
        ep_read_control(buf).await
    }

    async fn data_in(&mut self, data: &[u8], _first: bool, last: bool) -> Result<(), EndpointError> {
        // EP0 IN owned by the control pipe.
        ep_write(0, data, true).await?;
        if last {
            // Status stage: receive the host's zero-length OUT.
            ep_zlp(0, Direction::Out, true).await?;
        }
        Ok(())
    }

    async fn accept(&mut self) {
        if control_setup_pending() {
            return;
        }
        // Status stage: send a zero-length IN packet.
        // EP0 IN owned by control pipe.
        let _ = ep_zlp(0, Direction::In, true).await;
    }

    async fn reject(&mut self) {
        if control_setup_pending() {
            return;
        }
        // Stall EP0 in both directions to reject the request.
        let r = regs();
        r.modify_endptctrl(0, |v| v | EPCTRL_TXS | EPCTRL_RXS);
    }

    async fn accept_set_address(&mut self, addr: u8) {
        if control_setup_pending() {
            return;
        }
        // EHCI: program the address with the "advance" bit so it is applied
        // only after the status stage completes, then send the status IN.
        let r = regs();
        r.set_deviceaddr(((addr as u32) << DEVICEADDR_USBADR_SHIFT) | DEVICEADDR_USBADRA);
        // EP0 IN for status.
        let _ = ep_zlp(0, Direction::In, true).await;
    }
}

// =========================================================================
// Bus
// =========================================================================

/// USB bus control.
pub struct Bus {
    inited: bool,
    control_max_packet_size: u16,
}

impl Drop for Bus {
    fn drop(&mut self) {
        let r = regs();
        r.modify_usbcmd(|v| v & !USBCMD_RS);
        r.set_usbintr(0);
        r.clear_usbsts(ALL_USBSTS);
        UsbInterrupt::disable();

        // SAFETY: dropping the bus is the terminal owner path for the USBHS
        // peripheral. Embassy's USB device graph drops endpoint/class handles
        // with the bus, so no further endpoint transfer should touch the gated
        // controller registers after this point.
        unsafe {
            clock::deinit_clocks_and_phy();
        }
    }
}

impl embassy_usb_driver::Bus for Bus {
    async fn enable(&mut self) {
        let r = regs();
        // Enable the interrupt sources we handle.
        r.set_usbintr(USBSTS_UI | USBSTS_UEI | USBSTS_PCI | USBSTS_URI | USBSTS_SLI);
        #[cfg(feature = "defmt")]
        defmt::trace!("usb: bus enable");

        // SAFETY: enabling the controller interrupt.
        unsafe {
            UsbInterrupt::unpend();
            UsbInterrupt::enable();
        }

        // Attach: set Run/Stop.
        r.modify_usbcmd(|v| v | USBCMD_RS);
        self.inited = true;
    }

    async fn disable(&mut self) {
        let r = regs();
        #[cfg(feature = "defmt")]
        defmt::trace!("usb: bus disable");
        r.modify_usbcmd(|v| v & !USBCMD_RS);
        r.set_usbintr(0);
        UsbInterrupt::disable();
    }

    async fn poll(&mut self) -> Event {
        poll_fn(|cx| {
            BUS_WAKER.register(cx.waker());

            if !self.inited {
                // Surface an initial power-detected event so the stack proceeds.
                self.inited = true;
                return Poll::Ready(Event::PowerDetected);
            }

            if FLAG_RESET.swap(false, Ordering::Relaxed) {
                #[cfg(feature = "defmt")]
                defmt::trace!("usb: bus reset");
                // Re-initialize endpoint 0 and clear setup/complete state.
                let r = regs();
                let setup = r.endptsetupstat();
                r.clear_endptsetupstat(setup);
                FLAG_SETUP.store(false, Ordering::Relaxed);
                let complete = r.endptcomplete();
                r.clear_endptcomplete(complete);
                while r.endptprime() != 0 {}
                r.set_endptflush(ALL_ENDPOINT_BITS);
                r.set_deviceaddr(0);
                init_control_qh(self.control_max_packet_size);
                return Poll::Ready(Event::Reset);
            }
            if FLAG_RESUME.swap(false, Ordering::Relaxed) {
                #[cfg(feature = "defmt")]
                defmt::trace!("usb: resume");
                return Poll::Ready(Event::Resume);
            }
            if FLAG_SUSPEND.swap(false, Ordering::Relaxed) {
                #[cfg(feature = "defmt")]
                defmt::trace!("usb: suspend");
                return Poll::Ready(Event::Suspend);
            }
            Poll::Pending
        })
        .await
    }

    async fn remote_wakeup(&mut self) -> Result<(), Unsupported> {
        Err(Unsupported)
    }

    fn endpoint_set_enabled(&mut self, ep_addr: EndpointAddress, enabled: bool) {
        let slot = EndpointSlot::from_addr(ep_addr);
        if enabled {
            if let Some(config) = EndpointConfig::load(slot) {
                configure_endpoint(ep_addr, config.ep_type, config.max_packet_size);
            }
        } else {
            let r = regs();
            #[cfg(feature = "defmt")]
            defmt::trace!("usb: disable ep{=usize} dir={=u8}", slot.index, slot.dir_num());
            r.modify_endptctrl(slot.index, |v| v & !endpoint_enable_bit(slot));
        }
        slot.waker().wake();
    }

    fn endpoint_set_stalled(&mut self, ep_addr: EndpointAddress, stalled: bool) {
        let slot = EndpointSlot::from_addr(ep_addr);
        let r = regs();
        #[cfg(feature = "defmt")]
        defmt::trace!(
            "usb: stall ep{=usize} dir={=u8} stalled={=u8}",
            slot.index,
            slot.dir_num(),
            stalled as u8
        );
        r.modify_endptctrl(slot.index, |v| {
            let bit = endpoint_stall_bit(slot);
            if stalled { v | bit } else { v & !bit }
        });
    }

    fn endpoint_is_stalled(&mut self, ep_addr: EndpointAddress) -> bool {
        let slot = EndpointSlot::from_addr(ep_addr);
        regs().endptctrl(slot.index) & endpoint_stall_bit(slot) != 0
    }
}
