use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    println!("cargo:rustc-link-arg-bins=--nmagic");
    println!("cargo:rustc-link-arg-bins=-Tlink.x");
    println!("cargo:rustc-link-arg-bins=-Tdefmt.x");
    println!("cargo:rerun-if-changed=lvgl/lv_conf.h");
    println!("cargo:rerun-if-changed=lvgl-port/port.c");
    println!("cargo:rerun-if-changed=lvgl-port/port.h");
    println!("cargo:rerun-if-changed=touch-projects/SporthalleLudwigsfelde/hall_config.json");
    println!("cargo:rerun-if-changed=touch-projects/SporthalleLudwigsfelde/can_config.json");

    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

    generate_touch_config(&manifest_dir, &out_dir);

    if env::var("CARGO_FEATURE_LVGL").is_ok() {
        compile_lvgl_port(&manifest_dir);
    }
}

fn generate_touch_config(manifest_dir: &Path, out_dir: &Path) {
    let project = manifest_dir.join("touch-projects/SporthalleLudwigsfelde");
    let hall_path = project.join("hall_config.json");
    let can_path = project.join("can_config.json");

    let hall_json: serde_json::Value =
        serde_json::from_str(&fs::read_to_string(&hall_path).expect("read hall_config.json"))
            .expect("parse hall_config.json");
    let can_json: serde_json::Value =
        serde_json::from_str(&fs::read_to_string(&can_path).expect("read can_config.json"))
            .expect("parse can_config.json");

    let fields = hall_json["fields"].as_array().expect("fields array");
    let field_count = fields.len();
    let button_count = field_count * 3 + 3;

    let ui = &hall_json["ui"];
    let display_width: u16 = env::var("HALL_DISPLAY_WIDTH")
        .ok()
        .and_then(|v| v.parse().ok())
        .unwrap_or(800);
    let display_height: u16 = env::var("HALL_DISPLAY_HEIGHT")
        .ok()
        .and_then(|v| v.parse().ok())
        .unwrap_or(480);

    let pct = |value: f64, total: u16| -> u16 { ((value / 100.0) * f64::from(total)).round() as u16 };

    let mut rust = String::new();
    writeln!(rust, "// @generated by build.rs — do not edit").unwrap();
    writeln!(rust, "pub const DISPLAY_WIDTH: u16 = {display_width};").unwrap();
    writeln!(rust, "pub const DISPLAY_HEIGHT: u16 = {display_height};").unwrap();
    writeln!(rust, "pub const FIELD_COUNT: usize = {field_count};").unwrap();
    writeln!(rust, "pub const BUTTON_COUNT: usize = {button_count};").unwrap();
    writeln!(rust, "pub const GROUP_BUTTON_BASE: u8 = {};", field_count * 3).unwrap();
    writeln!(rust).unwrap();

    writeln!(
        rust,
        "pub const HALL_NAME: &str = {:?};",
        hall_json["hall_name"].as_str().unwrap_or("")
    )
    .unwrap();
    writeln!(
        rust,
        "pub const OFF_LABEL: &str = {:?};",
        ui["off_label"].as_str().unwrap_or("")
    )
    .unwrap();
    writeln!(
        rust,
        "pub const ALL_PREFIX: &str = {:?};",
        ui["all_prefix"].as_str().unwrap_or("")
    )
    .unwrap();
    writeln!(
        rust,
        "pub const LUX_SUFFIX: &str = {:?};",
        ui["lux_suffix"].as_str().unwrap_or("")
    )
    .unwrap();
    writeln!(
        rust,
        "pub const CENTRAL_OFF_LABEL: &str = {:?};",
        ui["central_off_label"].as_str().unwrap_or("")
    )
    .unwrap();
    writeln!(
        rust,
        "pub const GROUP_EYEBROW: &str = {:?};",
        ui["group_eyebrow"].as_str().unwrap_or("")
    )
    .unwrap();
    writeln!(
        rust,
        "pub const SUMMARY_READY: &str = {:?};",
        ui["summary_ready"].as_str().unwrap_or("Lichtsteuerung bereit")
    )
    .unwrap();
    writeln!(rust).unwrap();

    writeln!(rust, "pub struct FieldLayout {{").unwrap();
    writeln!(rust, "    pub id: &'static str,").unwrap();
    writeln!(rust, "    pub label: &'static str,").unwrap();
    writeln!(rust, "    pub eyebrow: &'static str,").unwrap();
    writeln!(rust, "    pub x: u16,").unwrap();
    writeln!(rust, "    pub y: u16,").unwrap();
    writeln!(rust, "    pub w: u16,").unwrap();
    writeln!(rust, "    pub h: u16,").unwrap();
    writeln!(rust, "    pub default_lux: u16,").unwrap();
    writeln!(rust, "    pub button_base: u8,").unwrap();
    writeln!(rust, "}}").unwrap();
    writeln!(rust).unwrap();

    writeln!(rust, "pub const FIELDS: [FieldLayout; FIELD_COUNT] = [").unwrap();
    for (i, field) in fields.iter().enumerate() {
        let left = field["left"].as_f64().unwrap_or(0.0);
        let top = field["top"].as_f64().unwrap_or(0.0);
        let width = field["width"].as_f64().unwrap_or(10.0);
        let height = field["height"].as_f64().unwrap_or(10.0);
        writeln!(
            rust,
            "    FieldLayout {{ id: {:?}, label: {:?}, eyebrow: {:?}, x: {}, y: {}, w: {}, h: {}, default_lux: {}, button_base: {} }},",
            field["id"].as_str().unwrap_or(""),
            field["label"].as_str().unwrap_or(""),
            field["eyebrow"].as_str().unwrap_or(""),
            pct(left, display_width),
            pct(top, display_height),
            pct(width, display_width).max(40),
            pct(height, display_height).max(40),
            field["default_lux"].as_u64().unwrap_or(0) as u16,
            i * 3,
        )
        .unwrap();
    }
    writeln!(rust, "];").unwrap();
    writeln!(rust).unwrap();

    writeln!(rust, "pub const BUTTON_TOKENS: [&str; BUTTON_COUNT] = [").unwrap();
    for field in fields {
        let id = field["id"].as_str().unwrap_or("");
        writeln!(rust, "    {:?},", format!("field:{id}:500")).unwrap();
        writeln!(rust, "    {:?},", format!("field:{id}:300")).unwrap();
        writeln!(rust, "    {:?},", format!("field:{id}:0")).unwrap();
    }
    writeln!(rust, "    \"group:play-fields:500\",").unwrap();
    writeln!(rust, "    \"group:play-fields:300\",").unwrap();
    writeln!(rust, "    \"group:all-fields:0\",").unwrap();
    writeln!(rust, "];").unwrap();
    writeln!(rust).unwrap();

    let enabled = can_json["enabled"].as_bool().unwrap_or(true);
    let tx_id = can_json["tx_id"].as_u64().unwrap_or(512) as u16;
    let tx_endian = can_json["tx_endian"].as_str().unwrap_or("little");
    let command_repeat_ms = can_json["command_repeat_ms"].as_u64().unwrap_or(25);
    let minp = can_json["minp"].as_array().expect("minp array");

    writeln!(rust, "pub const CAN_ENABLED: bool = {enabled};").unwrap();
    writeln!(rust, "pub const CAN_TX_ID: u16 = {tx_id};").unwrap();
    writeln!(rust, "pub const CAN_TX_LITTLE_ENDIAN: bool = {};", tx_endian == "little").unwrap();
    writeln!(rust, "pub const CAN_COMMAND_REPEAT_MS: u64 = {command_repeat_ms};").unwrap();
    writeln!(rust, "pub const MINP_COUNT: usize = {};", minp.len()).unwrap();
    writeln!(rust, "pub const MINP_RX_ID: u16 = {};", minp[0][0].as_u64().unwrap_or(645) as u16)
        .unwrap();
    writeln!(rust).unwrap();

    writeln!(rust, "pub struct MinpEntry {{").unwrap();
    writeln!(rust, "    pub can_id: u16,").unwrap();
    writeln!(rust, "    pub active_value: u8,").unwrap();
    writeln!(rust, "    pub byte_index: u8,").unwrap();
    writeln!(rust, "    pub bit_index: u8,").unwrap();
    writeln!(rust, "}}").unwrap();
    writeln!(rust).unwrap();
    writeln!(rust, "pub const MINP: [MinpEntry; MINP_COUNT] = [").unwrap();
    for entry in minp {
        let arr = entry.as_array().expect("minp tuple");
        writeln!(
            rust,
            "    MinpEntry {{ can_id: {}, active_value: {}, byte_index: {}, bit_index: {} }},",
            arr[0].as_u64().unwrap_or(0) as u16,
            arr[1].as_u64().unwrap_or(0) as u8,
            arr[2].as_u64().unwrap_or(0) as u8,
            arr[3].as_u64().unwrap_or(0) as u8,
        )
        .unwrap();
    }
    writeln!(rust, "];").unwrap();

    fs::write(out_dir.join("touch_config.rs"), rust).expect("write touch_config.rs");
}

fn compile_lvgl_port(manifest_dir: &Path) {
    let port_dir = manifest_dir.join("lvgl-port");
    let lv_config_dir = manifest_dir.join("lvgl");
    let vendor = lvgl_sys_vendor_dir().join("vendor");

    cc::Build::new()
        .file(port_dir.join("port.c"))
        .include(&port_dir)
        .include(&lv_config_dir)
        .include(vendor.join("lvgl").join("src"))
        .include(&vendor)
        .define("LV_CONF_INCLUDE_SIMPLE", "1")
        .warnings(false)
        .compile("rvt50_lvgl_port");
}

fn lvgl_sys_vendor_dir() -> PathBuf {
    if let Ok(path) = env::var("LVGL_SYS_VENDOR") {
        return PathBuf::from(path);
    }

    let cargo_home = env::var("CARGO_HOME")
        .or_else(|_| env::var("HOME").map(|home| format!("{home}/.cargo")))
        .expect("CARGO_HOME or HOME must be set");

    let mut search_roots = vec![
        PathBuf::from(&cargo_home).join("registry/src"),
        PathBuf::from(&cargo_home).join("git/checkouts"),
    ];

    if let Ok(entries) = fs::read_dir(search_roots[0].join("index.crates.io-1949cf8c6b5b557f")) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path
                .file_name()
                .is_some_and(|name| name.to_string_lossy().starts_with("lvgl-sys-"))
                && path.join("vendor/lvgl/src").is_dir()
            {
                return path;
            }
        }
    }

    for base in search_roots.drain(..) {
        if let Some(path) = find_lvgl_sys_vendor(&base) {
            return path;
        }
    }

    panic!(
        "Could not locate lvgl-sys vendor directory. Set LVGL_SYS_VENDOR to the lvgl-sys crate root."
    );
}

fn find_lvgl_sys_vendor(base: &Path) -> Option<PathBuf> {
    let entries = std::fs::read_dir(base).ok()?;
    let mut matches = Vec::new();
    for entry in entries.flatten() {
        let path = entry.path();
        let name = path.file_name()?.to_string_lossy();
        if name.starts_with("lvgl-sys-") {
            matches.push(path);
        } else if name.starts_with("lv_binding_rust-") {
            if let Some(nested) = find_nested_lvgl_sys(&path) {
                matches.push(nested);
            }
        }
    }

    matches.sort_by_key(|path| path.file_name().map(|name| name.to_string_lossy().to_string()));
    for candidate in matches {
        if candidate.join("vendor/lvgl/src").is_dir() {
            return Some(candidate);
        }
    }
    None
}

fn find_nested_lvgl_sys(checkout: &Path) -> Option<PathBuf> {
    let entries = std::fs::read_dir(checkout).ok()?;
    for entry in entries.flatten() {
        let candidate = entry.path().join("lvgl-sys");
        if candidate.join("vendor/lvgl/src").is_dir() {
            return Some(candidate);
        }
    }
    None
}
