[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# Riverdi RVT50HQSNWC00-B uses STM32U5A9NJH6Q
runner = "probe-rs run --chip STM32U5A9NJH6Q"

[build]
target = "thumbv8m.main-none-eabihf"

[target.thumbv8m.main-none-eabihf]
linker = "rust-lld"

[env]
DEFMT_LOG = "trace"
DEP_LV_CONFIG_PATH = { value = "lvgl", relative = true }
"CC_thumbv8m.main-none-eabihf" = "/home/mkoeppchen/.platformio/packages/toolchain-gccarmnoneeabi/bin/arm-none-eabi-gcc"
"CFLAGS_thumbv8m.main-none-eabihf" = "-mcpu=cortex-m33 -mthumb -mfloat-abi=hard -mfpu=fpv5-sp-d16"
"AR_thumbv8m.main-none-eabihf" = "/home/mkoeppchen/.platformio/packages/toolchain-gccarmnoneeabi/bin/arm-none-eabi-ar"
BINDGEN_EXTRA_CLANG_ARGS = "--target=thumbv8m.main-none-eabihf -mcpu=cortex-m33 -mthumb -I/home/mkoeppchen/.platformio/packages/toolchain-gccarmnoneeabi/arm-none-eabi/include -I/home/mkoeppchen/.platformio/packages/toolchain-gccarmnoneeabi/lib/gcc/arm-none-eabi/12.3.1/include"
