//! The vector tables, generated by `build.rs`.
//!
//! All byte strings point into one blob linked as read-only data, so a binary
//! only pays for the suites it references.

#![allow(missing_docs)]

/// A named table of cases.
pub struct Suite<T: 'static> {
    /// The Wycheproof file or generated table the cases come from.
    pub name: &'static str,
    /// The cases.
    pub cases: &'static [T],
}

/// What Wycheproof expects of a case.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Expected {
    /// The operation must succeed with the listed output.
    Valid,
    /// The operation must fail.
    Invalid,
    /// Either, but if it succeeds the output must be the listed one.
    Acceptable,
}

/// A digest of a prefix of [`MESSAGE`].
pub struct Digest {
    pub len: usize,
    pub digest: &'static [u8],
}

/// An HMAC or CMAC case. `tag` may be truncated.
pub struct Mac {
    pub tc_id: u32,
    pub key: &'static [u8],
    pub msg: &'static [u8],
    pub tag: &'static [u8],
    pub result: Expected,
}

/// A GCM or CCM case.
pub struct Aead {
    pub tc_id: u32,
    pub key: &'static [u8],
    pub nonce: &'static [u8],
    pub aad: &'static [u8],
    pub msg: &'static [u8],
    pub ct: &'static [u8],
    pub tag: &'static [u8],
    pub result: Expected,
}

/// A CBC case: `ct` is the PKCS#7-padded encryption of `msg`.
pub struct Cbc {
    pub tc_id: u32,
    pub key: &'static [u8],
    pub iv: &'static [u8],
    pub msg: &'static [u8],
    pub ct: &'static [u8],
    pub result: Expected,
}

/// An ECB case: `ct` is the encryption of the first `pt_len` bytes of [`MESSAGE`].
pub struct Ecb {
    pub key: &'static [u8],
    pub pt_len: usize,
    pub ct: &'static [u8],
}

/// A CTR case: `ct` is the encryption of the first `pt_len` bytes of [`MESSAGE`].
pub struct Ctr {
    pub key: &'static [u8],
    pub iv: &'static [u8],
    pub pt_len: usize,
    pub ct: &'static [u8],
}

/// A Diffie-Hellman case. For ECDH, `public` is a SEC1 point of whatever
/// length and `private` a big-endian integer of whatever length; malformed
/// ones are part of the vectors.
pub struct Dh {
    pub tc_id: u32,
    pub private: &'static [u8],
    pub public: &'static [u8],
    pub shared: &'static [u8],
    pub result: Expected,
}

/// An ECDSA verification case: the message is pre-hashed, `sig` is `r || s`
/// of whatever length.
pub struct Ecdsa {
    pub tc_id: u32,
    pub public: &'static [u8],
    pub digest: &'static [u8],
    pub sig: &'static [u8],
    pub result: Expected,
}

/// An EdDSA verification case: `public` is a compressed point, `sig` is
/// `R || S` of whatever length; malformed ones are part of the vectors.
pub struct Eddsa {
    pub tc_id: u32,
    pub public: &'static [u8],
    pub msg: &'static [u8],
    pub sig: &'static [u8],
    pub result: Expected,
}

/// Curve arithmetic on two scalars `a` and `b`. Points are uncompressed SEC1,
/// or empty for the point at infinity.
pub struct EcArith {
    pub a: &'static [u8],
    pub b: &'static [u8],
    /// `a * G`
    pub a_g: &'static [u8],
    /// `b * G`
    pub b_g: &'static [u8],
    /// `a * G + b * G`
    pub sum: &'static [u8],
    /// `a * (b * G)`
    pub a_times_b_g: &'static [u8],
    /// `a * G + b * (b * G)`
    pub lincomb: &'static [u8],
    pub a_plus_b: &'static [u8],
    pub a_minus_b: &'static [u8],
    pub a_times_b: &'static [u8],
    pub a_inv: &'static [u8],
}

/// A key pair.
pub struct KeyPair {
    pub private: &'static [u8],
    pub public: &'static [u8],
}

/// A deterministic signature: `sig` is the signature of the first `msg_len`
/// bytes of [`MESSAGE`] under `private`, whose public key is `public`.
pub struct Sign {
    pub private: &'static [u8],
    pub public: &'static [u8],
    pub msg_len: usize,
    pub sig: &'static [u8],
}

include!(concat!(env!("OUT_DIR"), "/vectors.rs"));
