//! The vector tables, generated by `build.rs`.
//!
//! All byte strings point into one blob linked as read-only data, so a binary
//! only pays for the suites it references.

#![allow(missing_docs)]

/// A named table of cases.
pub struct Suite<T: 'static> {
    /// The Wycheproof file or generated table the cases come from.
    pub name: &'static str,
    /// The cases.
    pub cases: &'static [T],
}

/// What Wycheproof expects of a case.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub enum Expected {
    /// The operation must succeed with the listed output.
    Valid,
    /// The operation must fail.
    Invalid,
    /// Either, but if it succeeds the output must be the listed one.
    Acceptable,
}

/// A digest of a prefix of [`MESSAGE`].
pub struct Digest {
    pub len: usize,
    pub digest: &'static [u8],
}

/// An HMAC or CMAC case. `tag` may be truncated.
pub struct Mac {
    pub tc_id: u32,
    pub key: &'static [u8],
    pub msg: &'static [u8],
    pub tag: &'static [u8],
    pub result: Expected,
}

/// A GCM, CCM or ChaCha-Poly1305 case.
pub struct Aead {
    pub tc_id: u32,
    pub key: &'static [u8],
    pub nonce: &'static [u8],
    pub aad: &'static [u8],
    pub msg: &'static [u8],
    pub ct: &'static [u8],
    pub tag: &'static [u8],
    pub result: Expected,
}

/// A CBC case: `ct` is the PKCS#7-padded encryption of `msg`.
pub struct Cbc {
    pub tc_id: u32,
    pub key: &'static [u8],
    pub iv: &'static [u8],
    pub msg: &'static [u8],
    pub ct: &'static [u8],
    pub result: Expected,
}

/// An ECB case: `ct` is the encryption of the first `pt_len` bytes of [`MESSAGE`].
pub struct Ecb {
    pub key: &'static [u8],
    pub pt_len: usize,
    pub ct: &'static [u8],
}

/// A CTR case: `ct` is the encryption of the first `pt_len` bytes of [`MESSAGE`].
pub struct Ctr {
    pub key: &'static [u8],
    pub iv: &'static [u8],
    pub pt_len: usize,
    pub ct: &'static [u8],
}

/// A ChaCha case: `ct` is the encryption of the first `pt_len` bytes of
/// [`MESSAGE`] with the keystream starting at block `counter`.
pub struct ChaCha {
    pub key: &'static [u8],
    pub nonce: &'static [u8],
    pub counter: u32,
    pub pt_len: usize,
    pub ct: &'static [u8],
}

/// An RSA key and one raw (unpadded) operation under it. Every integer is
/// big-endian; `n`, `d`, `m` and `c` have the size of the modulus, the CRT
/// values half of it, `e` is as short as it gets.
pub struct Rsa {
    pub n: &'static [u8],
    pub e: &'static [u8],
    pub d: &'static [u8],
    pub p: &'static [u8],
    pub q: &'static [u8],
    /// `d mod (p - 1)`
    pub dp: &'static [u8],
    /// `d mod (q - 1)`
    pub dq: &'static [u8],
    /// `q^-1 mod p`
    pub qinv: &'static [u8],
    /// A plaintext representative, smaller than `n`.
    pub m: &'static [u8],
    /// `m^e mod n`
    pub c: &'static [u8],
}

/// Known answers on a short Weierstrass curve: two key pairs, their shared
/// point, and an ECDSA signature made with a given nonce. Scalars have
/// the size of the curve, points are uncompressed SEC1, `sig` is `r || s`.
pub struct EcKat {
    pub private: &'static [u8],
    /// `private * G`
    pub public: &'static [u8],
    pub private2: &'static [u8],
    /// `private2 * G`
    pub public2: &'static [u8],
    /// `private * private2 * G`
    pub shared: &'static [u8],
    /// The nonce of `sig`.
    pub k: &'static [u8],
    /// The (already hashed) message `sig` signs. Its length varies: longer
    /// than the order, shorter, or equal.
    pub digest: &'static [u8],
    /// The signature of `digest` by `private` with `k`.
    pub sig: &'static [u8],
}

/// A Diffie-Hellman case. For ECDH, `public` is a SEC1 point of whatever
/// length and `private` a big-endian integer of whatever length; malformed
/// ones are part of the vectors.
pub struct Dh {
    pub tc_id: u32,
    pub private: &'static [u8],
    pub public: &'static [u8],
    pub shared: &'static [u8],
    pub result: Expected,
}

/// An ECDSA verification case: the message is pre-hashed, `sig` is `r || s`
/// of whatever length.
pub struct Ecdsa {
    pub tc_id: u32,
    pub public: &'static [u8],
    pub digest: &'static [u8],
    pub sig: &'static [u8],
    pub result: Expected,
}

/// An EdDSA verification case: `public` is a compressed point, `sig` is
/// `R || S` of whatever length; malformed ones are part of the vectors.
pub struct Eddsa {
    pub tc_id: u32,
    pub public: &'static [u8],
    pub msg: &'static [u8],
    pub sig: &'static [u8],
    pub result: Expected,
}

/// Curve arithmetic on two scalars `a` and `b`. Points are uncompressed SEC1,
/// or empty for the point at infinity.
pub struct EcArith {
    pub a: &'static [u8],
    pub b: &'static [u8],
    /// `a * G`
    pub a_g: &'static [u8],
    /// `b * G`
    pub b_g: &'static [u8],
    /// `a * G + b * G`
    pub sum: &'static [u8],
    /// `a * (b * G)`
    pub a_times_b_g: &'static [u8],
    /// `a * G + b * (b * G)`
    pub lincomb: &'static [u8],
    pub a_plus_b: &'static [u8],
    pub a_minus_b: &'static [u8],
    pub a_times_b: &'static [u8],
    pub a_inv: &'static [u8],
}

/// A key pair.
pub struct KeyPair {
    pub private: &'static [u8],
    pub public: &'static [u8],
}

/// A deterministic signature: `sig` is the signature of the first `msg_len`
/// bytes of [`MESSAGE`] under `private`, whose public key is `public`.
pub struct Sign {
    pub private: &'static [u8],
    pub public: &'static [u8],
    pub msg_len: usize,
    pub sig: &'static [u8],
}

include!(concat!(env!("OUT_DIR"), "/vectors.rs"));
