//! Memory-remap regions.
//!
//! ICACHE can remap up to 4 windows of an external memory (typically OCTOSPI/XSPI-mapped
//! flash) as if they were internal Code-region memory, so code can be fetched from them
//! through the cache instead of directly over the (slower) external bus.
//!
//! Only available on chips whose ICACHE block has `CRR` registers (U5, U3, WBA, H5, L5) — not
//! on N6.

use crate::pac::icache::vals::{Hburst, Mstsel, Rsize};

use super::regs;

/// Number of remap regions.
pub const REGION_COUNT: usize = 4;

/// Size of a memory-remap region.
///
/// This also determines the address alignment required for [`RegionConfig::base_address`] and
/// [`RegionConfig::remap_address`]: both must be aligned to the region size.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub enum RegionSize {
    /// 2 MB
    Mb2,
    /// 4 MB
    Mb4,
    /// 8 MB
    Mb8,
    /// 16 MB
    Mb16,
    /// 32 MB
    Mb32,
    /// 64 MB
    Mb64,
    /// 128 MB
    Mb128,
}

impl RegionSize {
    fn rsize(self) -> Rsize {
        match self {
            RegionSize::Mb2 => Rsize::MegaBytes2,
            RegionSize::Mb4 => Rsize::MegaBytes4,
            RegionSize::Mb8 => Rsize::MegaBytes8,
            RegionSize::Mb16 => Rsize::MegaBytes16,
            RegionSize::Mb32 => Rsize::MegaBytes32,
            RegionSize::Mb64 => Rsize::MegaBytes64,
            RegionSize::Mb128 => Rsize::MegaBytes128,
        }
    }

    // The RSIZE code (1..=7) doubles as the width, in bits, of the low part of the
    // BASEADDR/REMAPADDR fields that must be zero for a given region size: bigger regions need
    // more low bits cleared (coarser alignment), which is exactly `code - 1` bits.
    fn code(self) -> u32 {
        self.rsize().to_bits() as u32
    }
}

/// AHB master whose traffic is routed through a remap region.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub enum TrafficRoute {
    /// Master 1 port.
    Master1,
    /// Master 2 port.
    Master2,
}

impl From<TrafficRoute> for Mstsel {
    fn from(r: TrafficRoute) -> Self {
        match r {
            TrafficRoute::Master1 => Mstsel::Master1selected,
            TrafficRoute::Master2 => Mstsel::Master2selected,
        }
    }
}

/// Output burst type used for AHB accesses generated by a remap region.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub enum OutputBurst {
    /// WRAP bursts.
    Wrap,
    /// INCR bursts.
    Increment,
}

impl From<OutputBurst> for Hburst {
    fn from(b: OutputBurst) -> Self {
        match b {
            OutputBurst::Wrap => Hburst::Wrap,
            OutputBurst::Increment => Hburst::Increment,
        }
    }
}

/// Configuration for a memory-remap region.
#[derive(Clone, Copy, Debug)]
pub struct RegionConfig {
    /// Base address (in the external memory's AHB address window) of the region to remap.
    /// Must be aligned to `size`.
    pub base_address: u32,
    /// Address it's remapped to. Must be aligned to `size`.
    pub remap_address: u32,
    /// Region size.
    pub size: RegionSize,
    /// AHB master whose traffic is routed through this region.
    pub route: TrafficRoute,
    /// Output burst type for AHB accesses generated by this region.
    pub burst: OutputBurst,
}

/// Error returned by [`super::Icache::enable_remap_region()`].
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub enum RegionError {
    /// The cache must be disabled to configure a remap region.
    CacheEnabled,
    /// This region is already enabled; disable it first.
    AlreadyEnabled,
}

impl<'d> super::Icache<'d> {
    /// Configure and enable a memory-remap region.
    ///
    /// `region` must be less than [`REGION_COUNT`] (this panics otherwise). The cache must be
    /// disabled, and the region must not already be enabled.
    pub fn enable_remap_region(&mut self, region: u8, config: RegionConfig) -> Result<(), RegionError> {
        if regs().cr().read().en() {
            return Err(RegionError::CacheEnabled);
        }

        let crr = regs().crr(region as usize);
        if crr.read().ren() {
            return Err(RegionError::AlreadyEnabled);
        }

        let code = config.size.code();
        let low_bits_mask = !(code - 1);
        let baseaddr = (((config.base_address & 0x1FFF_FFFF) >> 21) & (0xFF & low_bits_mask)) as u8;
        let remapaddr = ((config.remap_address >> 21) & (0x7FF & low_bits_mask)) as u16;

        crr.write(|w| {
            w.set_baseaddr(baseaddr);
            w.set_remapaddr(remapaddr);
            w.set_rsize(config.size.rsize());
            w.set_mstsel(config.route.into());
            w.set_hburst(config.burst.into());
            w.set_ren(true);
        });

        Ok(())
    }

    /// Disable a memory-remap region.
    ///
    /// `region` must be less than [`REGION_COUNT`] (this panics otherwise). The cache must be
    /// disabled.
    pub fn disable_remap_region(&mut self, region: u8) -> Result<(), RegionError> {
        if regs().cr().read().en() {
            return Err(RegionError::CacheEnabled);
        }

        regs().crr(region as usize).modify(|w| w.set_ren(false));

        Ok(())
    }
}
