//! NPU — ST Neural-ART accelerator ("ATON") of the STM32N6.
//!
//! The Neural-ART NPU is a data-flow machine: convolution accelerators,
//! activation/pooling/arithmetic units and DMA "streaming engines" connected
//! by a stream switch. For inference, ST's Edge AI tooling compiles a network
//! into *epochs* — self-contained hardware schedules. With the (default,
//! recommended) `--enable-epoch-controller` option, each hardware epoch is
//! emitted as a **blob**: a command stream that the NPU's built-in *epoch
//! controller* unit executes autonomously, programming all units and raising
//! an interrupt when the epoch completes. The CPU's job is reduced to:
//!
//! 1. load (and optionally relocate/patch) the blobs — see [`ecloader`],
//! 2. point the epoch controller at a blob and start it,
//! 3. sleep until the end-of-epoch interrupt,
//! 4. run any interleaved *software epochs* (CPU-side operators emitted by
//!    the tool, e.g. a final dequantize) and cache maintenance callbacks,
//! 5. repeat for the next epoch block.
//!
//! This driver implements that execution model, mirroring ST's `LL_ATON`
//! runtime (`LL_ATON_RT_RunEpochBlock` + `ATON_STD_IRQHandler`) with an async
//! API. Networks compiled to *streaming-engine* epochs (without the epoch
//! controller) are **not** supported.
//!
//! # Prerequisites
//!
//! System-level setup that the driver deliberately leaves to board/startup
//! code, matching the split in ST's examples:
//!
//! - NPU RAMs (AXISRAM3..6) powered and clocked, if the network's memory
//!   pools live there (`RCC.MEMENR`, RAMCFG).
//! - When running with TrustZone / RIF: the NPU (and NPU cache) bus masters
//!   granted access to the memories holding weights and activations.
//! - Input/output/blob buffers placed in NPU-visible memory, respecting the
//!   cache rules below.
//! - The NPU cache should be enabled ([`cache::npu_cache_enable`]) when
//!   weights live in cacheable external memory (flash/PSRAM).
//!
//! # Caches
//!
//! Buffers shared between CPU and NPU need explicit maintenance; the
//! [`cache`] submodule provides both MCU-side (Cortex-M55 D-cache) and
//! NPU-side (CACHEAXI) operations. ST Edge AI generates the required calls as
//! per-epoch callbacks — port them into the epoch's `start`/`end` functions.
//!
//! # Example
//!
//! ```rust,ignore
//! use embassy_stm32::{bind_interrupts, npu, peripherals};
//! use embassy_stm32::npu::ecloader::EcBinary;
//!
//! bind_interrupts!(struct Irqs {
//!     NPU0 => npu::InterruptHandler<peripherals::NPU>;
//! });
//!
//! // EC binary generated by ST Edge AI (`<network>_ecblobs.h`, here included
//! // as a u64 array) and a writable, NPU-visible copy of its blob.
//! static EC_BIN: &[u64] = &[/* ... */];
//! static BLOB: StaticCell<[u64; 3800]> = StaticCell::new();
//!
//! let p = embassy_stm32::init(Default::default());
//! let mut npu = npu::Npu::new(p.NPU, Irqs);
//!
//! // Network init: load the blob, relocate its "user input" symbol to the
//! // actual input buffer (mirrors LL_ATON_EC_Network/Inference_Init_*).
//! let bin = EcBinary::new(EC_BIN).unwrap();
//! let blob = BLOB.init([0; 3800]);
//! bin.load_blob(blob).unwrap();
//! let mut prev_base = 0;
//! bin.reloc_by_id(blob, "_user_io_input_0", input_buf.as_ptr() as u32, &mut prev_base).unwrap();
//!
//! // Inference: run the epoch list of the network.
//! npu.run_epoch_blob(blob).await.unwrap();
//! ```
//!
//! For multi-epoch networks, [`Npu::run_network`] executes a list of
//! [`EpochBlock`]s (hardware blobs interleaved with software epochs), which
//! is the direct equivalent of the generated `EpochBlock_ItemTypeDef` array.

pub mod cache;
pub mod ecloader;
mod regs;

use core::future::poll_fn;
use core::marker::PhantomData;
use core::sync::atomic::{AtomicU32, Ordering};
use core::task::Poll;

use embassy_hal_internal::PeripheralType;
use embassy_sync::waitqueue::AtomicWaker;

use crate::interrupt::typelevel::Interrupt;
use crate::{Peri, interrupt, pac};

/// Interrupt handler for ATON interrupt line 0 (NVIC `NPU0`).
///
/// All ATON interrupt sources are routed to this single line, matching ST's
/// runtime (`ATON_STD_IRQ_LINE = 0`).
pub struct InterruptHandler<T: Instance> {
    _phantom: PhantomData<T>,
}

/// Driver event bit: epoch controller finished a blob.
const EVT_EC_DONE: u32 = 1 << 0;

static WAKER: AtomicWaker = AtomicWaker::new();
static EVENTS: AtomicU32 = AtomicU32::new(0);
static ERRORS: AtomicU32 = AtomicU32::new(0);

// Diagnostic snapshot captured on the last DMA-transpose call. Used by
// `Npu::last_transpose_debug()` to help post-mortem when the transfer
// silently produces wrong data.
static DBG_LAST_INTREG:   AtomicU32 = AtomicU32::new(0);
static DBG_LAST_OUT_CTRL: AtomicU32 = AtomicU32::new(0);
static DBG_LAST_IN_CTRL:  AtomicU32 = AtomicU32::new(0);
static DBG_LAST_SPUN:     AtomicU32 = AtomicU32::new(0);
static DBG_LAST_OUT_POS:  AtomicU32 = AtomicU32::new(0);
static DBG_LAST_IN_POS:   AtomicU32 = AtomicU32::new(0);
static DBG_LAST_OUT_IRQ:  AtomicU32 = AtomicU32::new(0);
static DBG_LAST_IN_IRQ:   AtomicU32 = AtomicU32::new(0);
static DBG_LAST_OUT_EVT:  AtomicU32 = AtomicU32::new(0);
static DBG_LAST_SW_CTRL:  AtomicU32 = AtomicU32::new(0);
static DBG_LAST_SW_DST:   AtomicU32 = AtomicU32::new(0);
static DBG_LAST_ICTRL:    AtomicU32 = AtomicU32::new(0);
static DBG_EARLY_OUT_CTRL: AtomicU32 = AtomicU32::new(0);
static DBG_EARLY_IN_CTRL:  AtomicU32 = AtomicU32::new(0);
static DBG_EARLY_INTREG:   AtomicU32 = AtomicU32::new(0);

impl<T: Instance> interrupt::typelevel::Handler<T::Interrupt> for InterruptHandler<T> {
    unsafe fn on_interrupt() {
        let irqs = regs::read(regs::INTCTRL_INTREG);

        // Everything except the end-of-blob event and streaming-engine
        // completion events is an error condition for this execution model.
        let errors = irqs & !(regs::INT_ECTRL_EVT | regs::INT_STRENG_EVT_MASK);

        // Acknowledge interrupt *sources* first; the interrupt controller
        // latch is cleared afterwards, otherwise it re-latches immediately.
        if irqs & (regs::INT_ECTRL_EVT | regs::INT_ECTRL_ERR | regs::INT_ECTRL_NOACK) != 0 {
            let v = regs::read(regs::EPOCHCTRL_IRQ);
            regs::write(regs::EPOCHCTRL_IRQ, v);
        }
        let streng = (irqs & regs::INT_STRENG_EVT_MASK) | ((irqs & regs::INT_STRENG_ERR_MASK) >> regs::INT_STRENG_ERR_SHIFT);
        for i in 0..regs::STRENG_NUM {
            if streng & (1 << i) != 0 {
                let v = regs::read(regs::streng_irq(i));
                regs::write(regs::streng_irq(i), v);
            }
        }

        if errors != 0 {
            // Mask line 0 completely to guard against interrupt storms from
            // sources that stay asserted; `run_epoch_blob` restores the mask.
            regs::write(regs::intctrl_intormsk(0), 0xFFFF_FFFF);
            ERRORS.fetch_or(errors, Ordering::Relaxed);
        }
        if irqs & regs::INT_ECTRL_EVT != 0 {
            EVENTS.fetch_or(EVT_EC_DONE, Ordering::Relaxed);
        }

        cortex_m::asm::dsb();
        regs::write(regs::INTCTRL_INTCLR, irqs);
        cortex_m::asm::dsb();

        WAKER.wake();
    }
}

/// NPU error.
#[derive(Debug, Eq, PartialEq, Copy, Clone)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[non_exhaustive]
pub enum Error {
    /// The buffer passed as a blob does not start with the blob magic.
    InvalidBlob,
    /// The epoch controller reported an error (illegal opcode, bus fault).
    EpochController,
    /// The epoch controller waited for a unit acknowledge that never came.
    EpochControllerNoAck,
    /// One or more streaming engines reported an error (bitmask by engine).
    StreamingEngine(u16),
    /// One or more bus interfaces reported an error (bitmask by unit).
    BusInterface(u8),
    /// Unexpected interrupt source(s) (raw INTCTRL bitmask).
    Fault(u32),
}

fn decode_errors(bits: u32) -> Error {
    if bits & regs::INT_ECTRL_ERR != 0 {
        Error::EpochController
    } else if bits & regs::INT_ECTRL_NOACK != 0 {
        Error::EpochControllerNoAck
    } else if bits & regs::INT_STRENG_ERR_MASK != 0 {
        Error::StreamingEngine(((bits & regs::INT_STRENG_ERR_MASK) >> regs::INT_STRENG_ERR_SHIFT) as u16)
    } else if bits & regs::INT_BUSIF_ERR_MASK != 0 {
        Error::BusInterface(((bits & regs::INT_BUSIF_ERR_MASK) >> regs::INT_BUSIF_ERR_SHIFT) as u8)
    } else {
        Error::Fault(bits)
    }
}

/// One entry of a network's epoch list — the Rust equivalent of the generated
/// `EpochBlock_ItemTypeDef`.
///
/// `start` runs before the hardware epoch is started (typically MCU/NPU cache
/// maintenance for the epoch's inputs), `end` after it completes (cache
/// invalidation of outputs, or the body of a pure software epoch).
#[derive(Copy, Clone)]
pub struct EpochBlock<'a> {
    /// Called before the epoch (blob) is started.
    pub start: Option<fn()>,
    /// Called after the epoch completes.
    pub end: Option<fn()>,
    /// Epoch controller blob to execute; `None` for a pure software epoch.
    pub blob: Option<&'a [u64]>,
}

impl<'a> EpochBlock<'a> {
    /// A hardware epoch executing `blob` on the epoch controller.
    pub const fn hw(blob: &'a [u64]) -> Self {
        Self {
            start: None,
            end: None,
            blob: Some(blob),
        }
    }

    /// A hardware epoch with cache-maintenance/trace callbacks.
    pub const fn hw_with(blob: &'a [u64], start: Option<fn()>, end: Option<fn()>) -> Self {
        Self {
            start,
            end,
            blob: Some(blob),
        }
    }

    /// A pure software epoch: `start`/`end` run on the CPU, no hardware use.
    pub const fn sw(start: Option<fn()>, end: Option<fn()>) -> Self {
        Self { start, end, blob: None }
    }
}

/// Neural-ART NPU driver.
pub struct Npu<'d, T: Instance> {
    _peri: Peri<'d, T>,
}

impl<'d, T: Instance> Npu<'d, T> {
    /// Enable and initialize the NPU.
    ///
    /// Enables the NPU kernel clock, resets the IP, ungates all ATON-internal
    /// unit clocks, enables the bus interfaces and configures the interrupt
    /// controller (the equivalent of `LL_ATON_RT_RuntimeInit()`).
    pub fn new(peri: Peri<'d, T>, _irq: impl interrupt::typelevel::Binding<T::Interrupt, InterruptHandler<T>> + 'd) -> Self {
        // Kernel clock + reset pulse.
        pac::RCC.ahb5enr().modify(|w| w.set_npuen(true));
        pac::RCC.ahb5rstr().modify(|w| w.set_npurst(true));
        pac::RCC.ahb5rstr().modify(|w| w.set_npurst(false));

        // ATON global init (LL_ATON_Init): clear the clock-controller
        // pipeline, then enable it and ungate all unit clocks. Per-unit
        // dynamic clock gating (BGATES) is not used — all gates stay open.
        regs::modify(regs::CLKCTRL_CTRL, |v| v | regs::CLKCTRL_CTRL_CLR);
        regs::write(regs::CLKCTRL_CTRL, regs::CLKCTRL_CTRL_EN);
        regs::write(regs::CLKCTRL_AGATES0, 0xFFFF_FFFF);
        regs::write(regs::CLKCTRL_AGATES1, 0xFFFF_FFFF);
        regs::write(regs::CLKCTRL_BGATES, 0xFFFF_FFFF);

        // Enable the bus interfaces.
        for i in 0..regs::BUSIF_NUM {
            regs::write(regs::busif_ctrl(i), regs::BUSIF_CTRL_EN);
        }

        // Interrupt controller: disable + clear pipeline + reset config...
        regs::write(regs::INTCTRL_CTRL, regs::INTCTRL_CTRL_CLR);
        while regs::read(regs::INTCTRL_CTRL) & regs::INTCTRL_CTRL_CLR != 0 {}
        regs::write(regs::INTCTRL_CTRL, regs::INTCTRL_CTRL_CONFCLR);
        while regs::read(regs::INTCTRL_CTRL) & regs::INTCTRL_CTRL_CONFCLR != 0 {}

        // ...then route to line 0: OR-mask blocks the (polled) streaming
        // engine completion events and passes every other event and error;
        // the AND-mask group stays disabled (all ones).
        regs::write(regs::intctrl_intormsk(0), regs::INT_STRENG_EVT_MASK);
        regs::write(regs::intctrl_intandmsk(0), 0xFFFF_FFFF);
        regs::modify(regs::INTCTRL_CTRL, |v| v | regs::INTCTRL_CTRL_EN);

        EVENTS.store(0, Ordering::Relaxed);
        ERRORS.store(0, Ordering::Relaxed);

        T::Interrupt::unpend();
        unsafe { T::Interrupt::enable() };

        Self { _peri: peri }
    }

    /// Execute one epoch controller blob and wait for its completion.
    ///
    /// `blob` must contain a loaded blob — magic word, length, instructions —
    /// as produced by [`ecloader::EcBinary::load_blob`] (or a fully linked
    /// blob straight from `<network>_ecblobs.h`). The slice's 8-byte
    /// alignment satisfies the epoch controller's address requirement.
    ///
    /// If the blob (or any data it reads) was written by the CPU into
    /// MCU-cacheable memory, clean the MCU cache first (see [`cache`]).
    ///
    /// The future completes when the epoch controller raises its
    /// end-of-epoch interrupt. No hardware timeout is applied; wrap the
    /// future in `embassy_time::with_timeout` if needed.
    pub async fn run_epoch_blob(&mut self, blob: &[u64]) -> Result<(), Error> {
        if blob.is_empty() || blob[0] as u32 != ecloader::BLOB_MAGIC {
            return Err(Error::InvalidBlob);
        }

        EVENTS.store(0, Ordering::Relaxed);
        ERRORS.store(0, Ordering::Relaxed);

        // Unmask the epoch for line 0: keep streaming-engine completion
        // events blocked, let the epoch-controller event and all errors
        // through (mirrors __LL_ATON_RT_SetWaitMask for blob epochs).
        regs::write(regs::intctrl_intandmsk(0), !regs::INT_STRENG_EVT_MASK);

        // Make sure blob memory writes are visible before the EC fetches it.
        cortex_m::asm::dsb();

        // Configure and start the epoch controller (LL_EpochCtrl_Init).
        regs::write(regs::EPOCHCTRL_CTRL, 0); // step mode off
        regs::write(regs::EPOCHCTRL_ADDR, blob.as_ptr() as u32);
        regs::modify(regs::EPOCHCTRL_CTRL, |v| v | regs::EPOCHCTRL_CTRL_EN);

        let res = poll_fn(|cx| {
            WAKER.register(cx.waker());
            let err = ERRORS.load(Ordering::Relaxed);
            if err != 0 {
                return Poll::Ready(Err(decode_errors(err)));
            }
            if EVENTS.load(Ordering::Relaxed) & EVT_EC_DONE != 0 {
                return Poll::Ready(Ok(()));
            }
            Poll::Pending
        })
        .await;

        // Stop the epoch controller and clear its pipeline & configuration
        // (ATON_DISABLE_CLR_CONFCLR), so the next blob starts from a clean
        // unit even after an error.
        regs::write(regs::EPOCHCTRL_CTRL, regs::EPOCHCTRL_CTRL_CLR);
        while regs::read(regs::EPOCHCTRL_CTRL) & regs::EPOCHCTRL_CTRL_CLR != 0 {}
        regs::write(regs::EPOCHCTRL_CTRL, regs::EPOCHCTRL_CTRL_CONFCLR);
        while regs::read(regs::EPOCHCTRL_CTRL) & regs::EPOCHCTRL_CTRL_CONFCLR != 0 {}

        // Re-mask the epoch event and restore the OR-mask (the IRQ handler
        // fully masks the line after an error).
        regs::write(regs::intctrl_intandmsk(0), 0xFFFF_FFFF);
        regs::write(regs::intctrl_intormsk(0), regs::INT_STRENG_EVT_MASK);

        res
    }

    /// Rank-4 int8 tensor transpose on the ATON stream engines (hardware DMA).
    ///
    /// Streams `input.addr` sequentially through STRENG-0 (RAW input DMA) into
    /// the switch, which routes it to STRENG-1 (structured output DMA) writing
    /// the permuted result to `output.addr`. Mirrors ST's `LL_ATON_LIB_DMA_Transpose`
    /// (`ll_aton_lib.c`) for the byte-tensor case.
    ///
    /// - `input_shape`  — `[N, ...]` shape of the source tensor. `input_shape[0]`
    ///   must be 1 (only rank-4 with an outermost batch of 1 is supported here;
    ///   BlazeFace always has N=1).
    /// - `output_axes_offsets_bytes` — output tensor's per-axis byte strides.
    /// - `perm` — permutation such that `output[i0,i1,i2,i3] = input[j0..j3]`
    ///   with `j[perm[k]] = i[k]`. This is the same `perm` field emitted by
    ///   the generator; internally we index into `output_axes_offsets` with it.
    ///
    /// The caller is responsible for cache maintenance: neither the NPU nor
    /// the M55 D-cache is touched by this call.
    pub async fn dma_transpose_int8(
        &mut self,
        input_addr: u32,
        input_shape: [u16; 4],
        output_addr: u32,
        output_axes_offsets_bytes: [u32; 4],
        perm: [u8; 4],
    ) -> Result<(), Error> {
        // We use STRENG 0 as raw input DMA and STRENG 1 as structured output DMA.
        // These two engines are also part of the "epoch controller" execution
        // model, so we take care to leave them cleared+configuration-cleared on
        // the way out.
        const IN: usize = 0;
        const OUT: usize = 1;

        let sh = input_shape;
        let fwidth  = sh[3] as u32;
        let fheight = sh[2] as u32;
        let frame_loop_cnt = sh[1] as u32;
        let frame_tot_cnt  = sh[0] as u32 * sh[1] as u32;
        let in_bytes = sh[0] as u32 * sh[1] as u32 * sh[2] as u32 * sh[3] as u32;

        let oo = output_axes_offsets_bytes;
        let line_offset  = oo[perm[2] as usize];
        let batch_offset = oo[perm[3] as usize];
        let frame_offset = oo[perm[1] as usize];
        let loop_offset  = oo[perm[0] as usize];

        // Reset both engines to a known state before programming. Unlike
        // INTCTRL/EPOCHCTRL, the STRENG CLR/CONFCLR bits are not observably
        // self-clearing on this SoC, so we just write and move on — matching
        // ST's `LL_Streng_TensorInit`, which programs the fields directly.
        // Zero the entire register block so residual state from a prior
        // HW-blob epoch (CID_CACHE.LOFF_MSB, POS.GAPCYCLES, LIMIT{EN,ADDR},
        // FRAME_RPT, FRPTOFF, FOFFSET, EXTSYNC{,2}, STOPTAG, DESCRADDR, ...)
        // doesn't OR into our config.
        for n in [IN, OUT] {
            // Force the engine's state machine back to idle via CLR pulse
            // (bounded: never wait more than a few µs — the CLR bit may be
            // observably not-self-clearing on some devices, but issuing the
            // write still resets internal counters and external-sync waits).
            regs::write(regs::streng_reg(n, regs::STRENG_CTRL_OFF), regs::STRENG_CTRL_CLR);
            for _ in 0..10_000 {
                if regs::read(regs::streng_reg(n, regs::STRENG_CTRL_OFF)) & regs::STRENG_CTRL_CLR == 0 {
                    break;
                }
            }
            regs::write(regs::streng_reg(n, regs::STRENG_CTRL_OFF), regs::STRENG_CTRL_CONFCLR);
            for _ in 0..10_000 {
                if regs::read(regs::streng_reg(n, regs::STRENG_CTRL_OFF)) & regs::STRENG_CTRL_CONFCLR == 0 {
                    break;
                }
            }
            // Belt-and-braces: explicitly zero every field we don't program.
            regs::write(regs::streng_reg(n, regs::STRENG_CTRL_OFF), 0);
            regs::write(regs::streng_reg(n, regs::STRENG_ADDR_OFF), 0);
            regs::write(regs::streng_reg(n, regs::STRENG_FSIZE_OFF), 0);
            regs::write(regs::streng_reg(n, regs::STRENG_DEPTH_OFF), 0);
            regs::write(regs::streng_reg(n, regs::STRENG_STRD_OFF), 0);
            regs::write(regs::streng_reg(n, regs::STRENG_FOFFSET_OFF), 0);
            regs::write(regs::streng_reg(n, regs::STRENG_FRAME_RPT_OFF), 0);
            regs::write(regs::streng_reg(n, regs::STRENG_FRPTOFF_OFF), 0);
            regs::write(regs::streng_reg(n, regs::STRENG_POS_OFF), 0);
            regs::write(regs::streng_reg(n, regs::STRENG_EVENT_OFF), 0);
            regs::write(regs::streng_reg(n, regs::STRENG_STOPTAG_OFF), 0);
            regs::write(regs::streng_reg(n, regs::STRENG_LIMITEN_OFF), 0);
            regs::write(regs::streng_reg(n, regs::STRENG_LIMIT_OFF), 0);
            regs::write(regs::streng_reg(n, regs::STRENG_LIMITADDR_OFF), 0);
            regs::write(regs::streng_reg(n, regs::STRENG_CID_CACHE_OFF), 0);
            regs::write(regs::streng_reg(n, regs::STRENG_EXTSYNC_OFF), 0);
            regs::write(regs::streng_reg(n, regs::STRENG_EXTSYNC2_OFF), 0);
            regs::write(regs::streng_reg(n, regs::STRENG_DESCRADDR_OFF), 0);
            // Ack any stale IRQ latches.
            let v = regs::read(regs::streng_irq(n));
            if v != 0 { regs::write(regs::streng_irq(n), v); }
        }

        // Clear our destination-port entry in the switch (leaves other
        // routes owned by the epoch controller alone).
        let dst_reg = regs::strswitch_dst(regs::strsw_dst_idx_streng(OUT));
        regs::write(dst_reg, 0);

        // ── Program STRENG-1 (output, structured) ──────────────────────────
        // CTRL: DIR=1 (stream->bus), RAW=0, SINGLE=(frame_tot_cnt==1), 8-bit.
        let mut ctrl_out = regs::STRENG_CTRL_DIR | (8u32 << regs::STRENG_CTRL_SIZE0_LSB);
        if frame_tot_cnt == 1 {
            ctrl_out |= regs::STRENG_CTRL_SINGLE;
        }
        regs::write(regs::streng_reg(OUT, regs::STRENG_CTRL_OFF), ctrl_out);
        regs::write(regs::streng_reg(OUT, regs::STRENG_ADDR_OFF), output_addr);
        // FSIZE: WIDTH=fwidth, HEIGHT=fheight
        regs::write(
            regs::streng_reg(OUT, regs::STRENG_FSIZE_OFF),
            (fwidth & 0xFFFF) | ((fheight & 0xFFFF) << regs::STRENG_FSIZE_HEIGHT_LSB),
        );
        // DEPTH: SIZE=1, OFFSET=batch_offset (low 16 bits; MSBs go into LIMITEN.DOFF_MSB)
        let batch_offset_lo = batch_offset & 0xFFFF;
        let batch_offset_hi = batch_offset >> 16;
        regs::write(
            regs::streng_reg(OUT, regs::STRENG_DEPTH_OFF),
            1u32 | (batch_offset_lo << regs::STRENG_DEPTH_OFFSET_LSB),
        );
        // STRD: LOFF=line_offset (or fwidth*batch_offset if 0; here always non-zero).
        // Assumes line_offset fits in 16 bits — true for all BlazeFace transposes.
        debug_assert!(line_offset <= 0xFFFF, "line_offset {} does not fit in 16 bits", line_offset);
        regs::write(regs::streng_reg(OUT, regs::STRENG_STRD_OFF), line_offset & 0xFFFF);
        regs::write(regs::streng_reg(OUT, regs::STRENG_FOFFSET_OFF), frame_offset);
        regs::write(regs::streng_reg(OUT, regs::STRENG_FRAME_RPT_OFF), frame_loop_cnt);
        regs::write(regs::streng_reg(OUT, regs::STRENG_FRPTOFF_OFF), loop_offset);
        // LIMITEN: FRAMELIMIT=1, STOPPREFTC=1 (bit-1 is the reset value ST
        // preserves — stop prefetching once the last programmed byte has
        // been fetched; without this the engine keeps prefetching and never
        // reaches the "frame overflow" completion state), DOFF_MSB from
        // batch_offset high bits.
        regs::write(
            regs::streng_reg(OUT, regs::STRENG_LIMITEN_OFF),
            regs::STRENG_LIMITEN_STOPPREFTC
                | regs::STRENG_LIMITEN_FRAMELIMIT
                | (batch_offset_hi << regs::STRENG_LIMITEN_DOFF_MSB_LSB),
        );
        regs::write(regs::streng_reg(OUT, regs::STRENG_LIMIT_OFF), frame_tot_cnt);

        // Enable frame-overflow (completion) + illegal-cfg (error) events on
        // the output engine. Without this, the engine completes the transfer
        // silently and no INTCTRL bit is ever latched. Mirrors ST's
        // `LL_Streng_TensorInit` for the dir=1 case.
        regs::write(
            regs::streng_reg(OUT, regs::STRENG_EVENT_OFF),
            regs::STRENG_EVENT_EN_OFLOW_FRM | regs::STRENG_EVENT_EN_ILLCFG,
        );

        // ── Program STRENG-0 (input, raw sequential read) ──────────────────
        // CTRL: DIR=0 (bus->stream), RAW=1, SINGLE=1 (frame_tot_cnt=1), 8-bit.
        let ctrl_in = regs::STRENG_CTRL_RAW
            | regs::STRENG_CTRL_SINGLE
            | (8u32 << regs::STRENG_CTRL_SIZE0_LSB);
        regs::write(regs::streng_reg(IN, regs::STRENG_CTRL_OFF), ctrl_in);
        regs::write(regs::streng_reg(IN, regs::STRENG_ADDR_OFF), input_addr);
        // FSIZE in raw mode = total number of transfer units (bytes here).
        regs::write(regs::streng_reg(IN, regs::STRENG_FSIZE_OFF), in_bytes);
        regs::write(regs::streng_reg(IN, regs::STRENG_LIMITEN_OFF),
            regs::STRENG_LIMITEN_STOPPREFTC | regs::STRENG_LIMITEN_FRAMELIMIT);
        regs::write(regs::streng_reg(IN, regs::STRENG_LIMIT_OFF), 1);
        // Enable illegal-cfg error event on the input engine only (completion
        // is signalled by the output engine).
        regs::write(regs::streng_reg(IN, regs::STRENG_EVENT_OFF), regs::STRENG_EVENT_EN_ILLCFG);

        // ── Program the stream switch: route STRENG-0 -> STRENG-1 ──────────
        // Destination index for STRENG-1 = 1. LINK0 = src port id of STRENG-0 = 0.
        let src_id  = regs::strsw_src_streng(IN);
        regs::write(dst_reg, regs::STRSW_DST_EN0 | (src_id << regs::STRSW_DST_LINK0_LSB));
        // Enable the switch. Use a plain write (not RMW) to match ST's
        // `LL_Switch_Init_NoReset`, which unconditionally writes EN=1 and
        // therefore discards any stale CLR/CONFCLR bits that would otherwise
        // hold the switch in reset.
        regs::write(regs::STRSWITCH_CTRL, regs::STRSWITCH_CTRL_EN);

        // ── Pre-arm interrupt-status polling ───────────────────────────────
        // We poll INTCTRL.INTREG (latched hardware status) for the OUT
        // engine's completion event; a bit-flip there is our "done" signal.
        // The RUNNING bit in CTRL cannot be used reliably because it has a
        // small assertion latency after we set EN — a fast tail-read wins
        // the race and sees RUNNING=0 before the engine ever starts.
        //
        // Block ALL sources on IRQ line 0 for the duration of this transfer
        // so the OS ISR does not steal (and clear) our completion bits.
        let saved_ormsk = regs::read(regs::intctrl_intormsk(0));
        regs::write(regs::intctrl_intormsk(0), 0xFFFF_FFFF);
        let our_int_mask = (1u32 << IN) | (1u32 << OUT)
                         | (1u32 << (regs::INT_STRENG_ERR_SHIFT + IN as u32))
                         | (1u32 << (regs::INT_STRENG_ERR_SHIFT + OUT as u32));
        // Clear any stale INTCTRL latches for our engines.
        regs::write(regs::INTCTRL_INTCLR, our_int_mask);

        // ── Start the engines ──────────────────────────────────────────────
        cortex_m::asm::dsb();
        regs::modify(regs::streng_reg(OUT, regs::STRENG_CTRL_OFF), |v| v | regs::STRENG_CTRL_EN);
        regs::modify(regs::streng_reg(IN,  regs::STRENG_CTRL_OFF), |v| v | regs::STRENG_CTRL_EN);

        // Snapshot immediately (within a few cycles of enable) so we can see
        // if the engines actually asserted RUNNING at all.
        DBG_EARLY_OUT_CTRL.store(regs::read(regs::streng_reg(OUT, regs::STRENG_CTRL_OFF)), Ordering::Relaxed);
        DBG_EARLY_IN_CTRL.store(regs::read(regs::streng_reg(IN,  regs::STRENG_CTRL_OFF)), Ordering::Relaxed);
        DBG_EARLY_INTREG.store(regs::read(regs::INTCTRL_INTREG), Ordering::Relaxed);

        // ── Wait for completion via INTCTRL.INTREG ─────────────────────────
        //
        // Bit `OUT` = STRENG-OUT completion, bit `10+OUT` = STRENG-OUT error,
        // similarly for IN. Bounded spin; no `.await` so `with_timeout` at
        // the caller cannot preempt us.
        let done_bit  = 1u32 << OUT;
        let err_bits  = (1u32 << (regs::INT_STRENG_ERR_SHIFT + IN  as u32))
                      | (1u32 << (regs::INT_STRENG_ERR_SHIFT + OUT as u32));
        let mut spun: u32 = 0;
        let (result, last_intreg): (Result<(), Error>, u32) = loop {
            let intreg = regs::read(regs::INTCTRL_INTREG);
            if intreg & err_bits != 0 {
                let engines = ((intreg & err_bits) >> regs::INT_STRENG_ERR_SHIFT) as u16;
                break (Err(Error::StreamingEngine(engines)), intreg);
            }
            if intreg & done_bit != 0 {
                break (Ok(()), intreg);
            }
            spun = spun.wrapping_add(1);
            if spun > 2_000_000 {
                break (Err(Error::StreamingEngine(1 << OUT)), intreg);
            }
        };
        DBG_LAST_INTREG.store(last_intreg, Ordering::Relaxed);
        DBG_LAST_OUT_CTRL.store(regs::read(regs::streng_reg(OUT, regs::STRENG_CTRL_OFF)), Ordering::Relaxed);
        DBG_LAST_IN_CTRL.store(regs::read(regs::streng_reg(IN,  regs::STRENG_CTRL_OFF)), Ordering::Relaxed);
        DBG_LAST_SPUN.store(spun, Ordering::Relaxed);
        DBG_LAST_OUT_POS.store(regs::read(regs::streng_reg(OUT, regs::STRENG_POS_OFF)), Ordering::Relaxed);
        DBG_LAST_IN_POS.store(regs::read(regs::streng_reg(IN,  regs::STRENG_POS_OFF)), Ordering::Relaxed);
        DBG_LAST_OUT_IRQ.store(regs::read(regs::streng_irq(OUT)), Ordering::Relaxed);
        DBG_LAST_IN_IRQ.store(regs::read(regs::streng_irq(IN)),  Ordering::Relaxed);
        DBG_LAST_OUT_EVT.store(regs::read(regs::streng_reg(OUT, regs::STRENG_EVENT_OFF)), Ordering::Relaxed);
        DBG_LAST_SW_CTRL.store(regs::read(regs::STRSWITCH_CTRL), Ordering::Relaxed);
        DBG_LAST_SW_DST.store(regs::read(dst_reg), Ordering::Relaxed);
        DBG_LAST_ICTRL.store(regs::read(regs::INTCTRL_CTRL), Ordering::Relaxed);

        // ── Tear down ──────────────────────────────────────────────────────
        // Ack per-STRENG IRQ latches, then disable both engines via a plain
        // CTRL=0 and clear our DST route. Restore the INTCTRL OR-mask so the
        // OS ISR resumes servicing the sources it was configured for.
        for n in [IN, OUT] {
            let v = regs::read(regs::streng_irq(n));
            if v != 0 { regs::write(regs::streng_irq(n), v); }
            regs::write(regs::streng_reg(n, regs::STRENG_CTRL_OFF), 0);
            // Disable per-engine event sources — the epoch controller expects
            // to program these fresh for the next blob.
            regs::write(regs::streng_reg(n, regs::STRENG_EVENT_OFF), 0);
        }
        regs::write(dst_reg, 0);
        regs::write(regs::INTCTRL_INTCLR, our_int_mask);
        regs::write(regs::intctrl_intormsk(0), saved_ormsk);

        result
    }

    /// Read the diagnostic snapshot captured on the *last* call to
    /// [`dma_transpose_int8`]. Returns `(intreg, out_ctrl, in_ctrl, spun)`.
    pub fn last_transpose_debug(&self) -> (u32, u32, u32, u32) {
        (
            DBG_LAST_INTREG.load(Ordering::Relaxed),
            DBG_LAST_OUT_CTRL.load(Ordering::Relaxed),
            DBG_LAST_IN_CTRL.load(Ordering::Relaxed),
            DBG_LAST_SPUN.load(Ordering::Relaxed),
        )
    }

    /// Full diagnostic snapshot from the last DMA-transpose call. Fields:
    /// `(intreg, out_ctrl, in_ctrl, spun, out_pos, in_pos, out_irq, in_irq,
    ///   out_evt, sw_ctrl, sw_dst, ictrl, early_out_ctrl, early_in_ctrl,
    ///   early_intreg)`.
    pub fn last_transpose_debug_full(&self) -> [u32; 15] {
        [
            DBG_LAST_INTREG.load(Ordering::Relaxed),
            DBG_LAST_OUT_CTRL.load(Ordering::Relaxed),
            DBG_LAST_IN_CTRL.load(Ordering::Relaxed),
            DBG_LAST_SPUN.load(Ordering::Relaxed),
            DBG_LAST_OUT_POS.load(Ordering::Relaxed),
            DBG_LAST_IN_POS.load(Ordering::Relaxed),
            DBG_LAST_OUT_IRQ.load(Ordering::Relaxed),
            DBG_LAST_IN_IRQ.load(Ordering::Relaxed),
            DBG_LAST_OUT_EVT.load(Ordering::Relaxed),
            DBG_LAST_SW_CTRL.load(Ordering::Relaxed),
            DBG_LAST_SW_DST.load(Ordering::Relaxed),
            DBG_LAST_ICTRL.load(Ordering::Relaxed),
            DBG_EARLY_OUT_CTRL.load(Ordering::Relaxed),
            DBG_EARLY_IN_CTRL.load(Ordering::Relaxed),
            DBG_EARLY_INTREG.load(Ordering::Relaxed),
        ]
    }

    /// Run a network: execute a list of epoch blocks in order, awaiting each
    /// hardware blob and invoking the software callbacks in between — the
    /// equivalent of looping `LL_ATON_RT_RunEpochBlock()` until
    /// `LL_ATON_RT_DONE`.
    ///
    /// Stops at the first hardware error.
    pub async fn run_network(&mut self, epochs: &[EpochBlock<'_>]) -> Result<(), Error> {
        for eb in epochs {
            if let Some(f) = eb.start {
                f();
            }
            if let Some(blob) = eb.blob {
                self.run_epoch_blob(blob).await?;
            }
            if let Some(f) = eb.end {
                f();
            }
        }
        Ok(())
    }
}

impl<'d, T: Instance> Drop for Npu<'d, T> {
    fn drop(&mut self) {
        T::Interrupt::disable();

        // LL_ATON_DeInit: interrupt controller, bus interfaces, clocks.
        regs::write(regs::INTCTRL_CTRL, 0);
        for i in 0..regs::BUSIF_NUM {
            regs::write(regs::busif_ctrl(i), 0);
        }
        regs::write(regs::CLKCTRL_AGATES0, 0);
        regs::write(regs::CLKCTRL_AGATES1, 0);
        regs::write(regs::CLKCTRL_BGATES, 0);
        regs::write(regs::CLKCTRL_CTRL, 0);

        // Gate the NPU kernel clock.
        pac::RCC.ahb5enr().modify(|w| w.set_npuen(false));
    }
}

trait SealedInstance {}

/// NPU instance.
#[allow(private_bounds)]
pub trait Instance: SealedInstance + PeripheralType + 'static + Send {
    /// Interrupt for this instance (ATON interrupt line 0).
    type Interrupt: interrupt::typelevel::Interrupt;
}

impl SealedInstance for crate::peripherals::NPU {}
impl Instance for crate::peripherals::NPU {
    type Interrupt = crate::interrupt::typelevel::NPU0;
}
