//! NPU — ST Neural-ART accelerator ("ATON") of the STM32N6.
//!
//! The Neural-ART NPU is a data-flow machine: convolution accelerators,
//! activation/pooling/arithmetic units and DMA "streaming engines" connected
//! by a stream switch. For inference, ST's Edge AI tooling compiles a network
//! into *epochs* — self-contained hardware schedules. With the (default,
//! recommended) `--enable-epoch-controller` option, each hardware epoch is
//! emitted as a **blob**: a command stream that the NPU's built-in *epoch
//! controller* unit executes autonomously, programming all units and raising
//! an interrupt when the epoch completes. The CPU's job is reduced to:
//!
//! 1. load (and optionally relocate/patch) the blobs — see [`ecloader`],
//! 2. point the epoch controller at a blob and start it,
//! 3. sleep until the end-of-epoch interrupt,
//! 4. run any interleaved *software epochs* (CPU-side operators emitted by
//!    the tool, e.g. a final dequantize) and cache maintenance callbacks,
//! 5. repeat for the next epoch block.
//!
//! This driver implements that execution model, mirroring ST's `LL_ATON`
//! runtime (`LL_ATON_RT_RunEpochBlock` + `ATON_STD_IRQHandler`) with an async
//! API. Networks compiled to *streaming-engine* epochs (without the epoch
//! controller) are **not** supported.
//!
//! # Prerequisites
//!
//! System-level setup that the driver deliberately leaves to board/startup
//! code, matching the split in ST's examples:
//!
//! - NPU RAMs (AXISRAM3..6) powered and clocked, if the network's memory
//!   pools live there (`RCC.MEMENR`, RAMCFG).
//! - When running with TrustZone / RIF: the NPU (and NPU cache) bus masters
//!   granted access to the memories holding weights and activations.
//! - Input/output/blob buffers placed in NPU-visible memory, respecting the
//!   cache rules below.
//! - The NPU cache should be enabled ([`cache::npu_cache_enable`]) when
//!   weights live in cacheable external memory (flash/PSRAM).
//!
//! # Caches
//!
//! Buffers shared between CPU and NPU need explicit maintenance; the
//! [`cache`] submodule provides both MCU-side (Cortex-M55 D-cache) and
//! NPU-side (CACHEAXI) operations. ST Edge AI generates the required calls as
//! per-epoch callbacks — port them into the epoch's `start`/`end` functions.
//!
//! # Example
//!
//! ```rust,ignore
//! use embassy_stm32::{bind_interrupts, npu, peripherals};
//! use embassy_stm32::npu::ecloader::EcBinary;
//!
//! bind_interrupts!(struct Irqs {
//!     NPU0 => npu::InterruptHandler<peripherals::NPU>;
//! });
//!
//! // EC binary generated by ST Edge AI (`<network>_ecblobs.h`, here included
//! // as a u64 array) and a writable, NPU-visible copy of its blob.
//! static EC_BIN: &[u64] = &[/* ... */];
//! static BLOB: StaticCell<[u64; 3800]> = StaticCell::new();
//!
//! let p = embassy_stm32::init(Default::default());
//! let mut npu = npu::Npu::new(p.NPU, Irqs);
//!
//! // Network init: load the blob, relocate its "user input" symbol to the
//! // actual input buffer (mirrors LL_ATON_EC_Network/Inference_Init_*).
//! let bin = EcBinary::new(EC_BIN).unwrap();
//! let blob = BLOB.init([0; 3800]);
//! bin.load_blob(blob).unwrap();
//! let mut prev_base = 0;
//! bin.reloc_by_id(blob, "_user_io_input_0", input_buf.as_ptr() as u32, &mut prev_base).unwrap();
//!
//! // Inference: run the epoch list of the network.
//! npu.run_epoch_blob(blob).await.unwrap();
//! ```
//!
//! For multi-epoch networks, [`Npu::run_network`] executes a list of
//! [`EpochBlock`]s (hardware blobs interleaved with software epochs), which
//! is the direct equivalent of the generated `EpochBlock_ItemTypeDef` array.

pub mod cache;
pub mod ecloader;

use core::future::poll_fn;
use core::marker::PhantomData;
use core::sync::atomic::{AtomicU32, Ordering};
use core::task::Poll;

use embassy_hal_internal::PeripheralType;
use embassy_sync::waitqueue::AtomicWaker;

use crate::interrupt::typelevel::Interrupt;
use crate::{Peri, interrupt, pac};

const BUSIF_COUNT: usize = 2;
const STRENG_COUNT: usize = 10;
const INT_STRENG_EVT_MASK: u32 = 0x0000_03FF;
const INT_ECTRL_EVT: u32 = 1 << 28;

/// Interrupt handler for ATON interrupt line 0 (NVIC `NPU0`).
///
/// All ATON interrupt sources are routed to this single line, matching ST's
/// runtime (`ATON_STD_IRQ_LINE = 0`).
pub struct InterruptHandler<T: Instance> {
    _phantom: PhantomData<T>,
}

/// Driver event bit: epoch controller finished a blob.
const EVT_EC_DONE: u32 = 1 << 0;

static WAKER: AtomicWaker = AtomicWaker::new();
static EVENTS: AtomicU32 = AtomicU32::new(0);
static ERRORS: AtomicU32 = AtomicU32::new(0);

impl<T: Instance> interrupt::typelevel::Handler<T::Interrupt> for InterruptHandler<T> {
    unsafe fn on_interrupt() {
        let irqs = pac::NPU.intctrl().intreg().read();

        // Acknowledge interrupt *sources* first; the interrupt controller
        // latch is cleared afterwards, otherwise it re-latches immediately.
        if irqs.ectrl_evt() || irqs.ectrl_err() || irqs.ectrl_noack() {
            let v = pac::NPU.epochctrl().irq().read();
            pac::NPU.epochctrl().irq().write_value(v);
        }
        let streng = irqs.streng_evt() | irqs.streng_err();
        for i in 0..STRENG_COUNT {
            if streng & (1 << i) != 0 {
                let v = pac::NPU.streng(i).irq().read();
                pac::NPU.streng(i).irq().write_value(v);
            }
        }

        // Everything except the end-of-blob event and streaming-engine
        // completion events is an error condition for this execution model.
        let raw_errors = irqs.0 & !(INT_ECTRL_EVT | INT_STRENG_EVT_MASK);
        if raw_errors != 0 {
            // Mask line 0 completely to guard against interrupt storms from
            // sources that stay asserted; `run_epoch_blob` restores the mask.
            pac::NPU
                .intctrl()
                .intormsk(0)
                .write_value(pac::npu::regs::Intstatus(0xFFFF_FFFF));
            ERRORS.fetch_or(raw_errors, Ordering::Relaxed);
        }
        if irqs.ectrl_evt() {
            EVENTS.fetch_or(EVT_EC_DONE, Ordering::Relaxed);
        }

        cortex_m::asm::dsb();
        pac::NPU.intctrl().intclr().write_value(irqs);
        cortex_m::asm::dsb();

        WAKER.wake();
    }
}

/// NPU error.
#[derive(Debug, Eq, PartialEq, Copy, Clone)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[non_exhaustive]
pub enum Error {
    /// The buffer passed as a blob does not start with the blob magic.
    InvalidBlob,
    /// The epoch controller reported an error (illegal opcode, bus fault).
    EpochController,
    /// The epoch controller waited for a unit acknowledge that never came.
    EpochControllerNoAck,
    /// Epoch-controller CLR/CONFCLR teardown did not complete. Contains the
    /// final raw EPOCHCTRL.CTRL value; bit 1 identifies CLR and bit 30
    /// identifies CONFCLR.
    EpochControllerTeardown(u32),
    /// One or more streaming engines reported an error (bitmask by engine).
    StreamingEngine(u16),
    /// One or more bus interfaces reported an error (bitmask by unit).
    BusInterface(u8),
    /// Unexpected interrupt source(s) (raw INTCTRL bitmask).
    Fault(u32),
}

fn decode_errors(bits: u32) -> Error {
    let s = pac::npu::regs::Intstatus(bits);
    if s.ectrl_err() {
        Error::EpochController
    } else if s.ectrl_noack() {
        Error::EpochControllerNoAck
    } else if s.streng_err() != 0 {
        Error::StreamingEngine(s.streng_err())
    } else if s.busif_err() != 0 {
        Error::BusInterface(s.busif_err())
    } else {
        Error::Fault(bits)
    }
}

/// One entry of a network's epoch list — the Rust equivalent of the generated
/// `EpochBlock_ItemTypeDef`.
///
/// `start` runs before the hardware epoch is started (typically MCU/NPU cache
/// maintenance for the epoch's inputs), `end` after it completes (cache
/// invalidation of outputs, or the body of a pure software epoch).
#[derive(Copy, Clone)]
pub struct EpochBlock<'a> {
    /// Called before the epoch (blob) is started.
    pub start: Option<fn()>,
    /// Called after the epoch completes.
    pub end: Option<fn()>,
    /// Epoch controller blob to execute; `None` for a pure software epoch.
    pub blob: Option<&'a [u64]>,
}

impl<'a> EpochBlock<'a> {
    /// A hardware epoch executing `blob` on the epoch controller.
    pub const fn hw(blob: &'a [u64]) -> Self {
        Self {
            start: None,
            end: None,
            blob: Some(blob),
        }
    }

    /// A hardware epoch with cache-maintenance/trace callbacks.
    pub const fn hw_with(blob: &'a [u64], start: Option<fn()>, end: Option<fn()>) -> Self {
        Self {
            start,
            end,
            blob: Some(blob),
        }
    }

    /// A pure software epoch: `start`/`end` run on the CPU, no hardware use.
    pub const fn sw(start: Option<fn()>, end: Option<fn()>) -> Self {
        Self { start, end, blob: None }
    }
}

/// Neural-ART NPU driver.
pub struct Npu<'d, T: Instance> {
    _peri: Peri<'d, T>,
}

impl<'d, T: Instance> Npu<'d, T> {
    /// Enable and initialize the NPU.
    ///
    /// Enables the NPU kernel clock, resets the IP, ungates all ATON-internal
    /// unit clocks, enables the bus interfaces and configures the interrupt
    /// controller (the equivalent of `LL_ATON_RT_RuntimeInit()`).
    pub fn new(
        peri: Peri<'d, T>,
        _irq: impl interrupt::typelevel::Binding<T::Interrupt, InterruptHandler<T>> + 'd,
    ) -> Self {
        // Kernel clock + reset pulse.
        // Match ST's LL_AHB5 helpers: use the atomic set/clear aliases and
        // read AHB5ENR back after enabling to provide the documented RCC
        // peripheral-clock startup delay.
        pac::RCC.ahb5ensr().write(|w| w.set_npuens(true));
        let _ = pac::RCC.ahb5enr().read();
        pac::RCC.ahb5rstsr().write(|w| w.set_npursts(true));
        pac::RCC.ahb5rstcr().write(|w| w.set_npurstc(true));

        // ATON global init (LL_ATON_Init): clear the clock-controller
        // pipeline, then enable it and ungate all unit clocks. Per-unit
        // dynamic clock gating (BGATES) is not used — all gates stay open.
        pac::NPU.clkctrl().ctrl().modify(|w| w.set_clr(true));
        pac::NPU.clkctrl().ctrl().write(|w| w.set_en(true));
        pac::NPU
            .clkctrl()
            .agates0()
            .write_value(pac::npu::regs::Agates(0xFFFF_FFFF));
        pac::NPU
            .clkctrl()
            .agates1()
            .write_value(pac::npu::regs::Agates(0xFFFF_FFFF));
        pac::NPU
            .clkctrl()
            .bgates()
            .write_value(pac::npu::regs::Bgates(0xFFFF_FFFF));

        // Enable the bus interfaces.
        for i in 0..BUSIF_COUNT {
            pac::NPU.busif(i).ctrl().write(|w| w.set_en(true));
        }

        // Interrupt controller: disable + clear pipeline + reset config...
        pac::NPU.intctrl().ctrl().write(|w| w.set_clr(true));
        while pac::NPU.intctrl().ctrl().read().clr() {}
        pac::NPU.intctrl().ctrl().write(|w| w.set_confclr(true));
        while pac::NPU.intctrl().ctrl().read().confclr() {}

        // ...then route to line 0: OR-mask blocks the (polled) streaming
        // engine completion events and passes every other event and error;
        // the AND-mask group stays disabled (all ones).
        pac::NPU
            .intctrl()
            .intormsk(0)
            .write_value(pac::npu::regs::Intstatus(INT_STRENG_EVT_MASK));
        pac::NPU
            .intctrl()
            .intandmsk(0)
            .write_value(pac::npu::regs::Intstatus(0xFFFF_FFFF));
        pac::NPU.intctrl().ctrl().modify(|w| w.set_en(true));

        EVENTS.store(0, Ordering::Relaxed);
        ERRORS.store(0, Ordering::Relaxed);

        T::Interrupt::unpend();
        unsafe { T::Interrupt::enable() };

        Self { _peri: peri }
    }

    /// Execute one epoch controller blob and wait for its completion.
    ///
    /// `blob` must contain a loaded blob — magic word, length, instructions —
    /// as produced by [`ecloader::EcBinary::load_blob`] (or a fully linked
    /// blob straight from `<network>_ecblobs.h`). The slice's 8-byte
    /// alignment satisfies the epoch controller's address requirement.
    ///
    /// If the blob (or any data it reads) was written by the CPU into
    /// MCU-cacheable memory, clean the MCU cache first (see [`cache`]).
    ///
    /// The future completes when the epoch controller raises its
    /// end-of-epoch interrupt. No hardware timeout is applied; wrap the
    /// future in `embassy_time::with_timeout` if needed.
    pub async fn run_epoch_blob(&mut self, blob: &[u64]) -> Result<(), Error> {
        if blob.is_empty() || blob[0] as u32 != ecloader::BLOB_MAGIC {
            return Err(Error::InvalidBlob);
        }

        EVENTS.store(0, Ordering::Relaxed);
        ERRORS.store(0, Ordering::Relaxed);

        // Unmask the epoch for line 0: keep streaming-engine completion
        // events blocked, let the epoch-controller event and all errors
        // through (mirrors __LL_ATON_RT_SetWaitMask for blob epochs).
        pac::NPU
            .intctrl()
            .intandmsk(0)
            .write_value(pac::npu::regs::Intstatus(!INT_STRENG_EVT_MASK));

        // Make sure blob memory writes are visible before the EC fetches it.
        cortex_m::asm::dsb();

        // Configure and start the epoch controller (LL_EpochCtrl_Init).
        pac::NPU
            .epochctrl()
            .ctrl()
            .write_value(pac::npu::regs::EpochctrlCtrl(0)); // step mode off
        pac::NPU
            .epochctrl()
            .addr()
            .write_value(pac::npu::regs::EpochctrlAddr(blob.as_ptr() as u32));
        pac::NPU.epochctrl().ctrl().modify(|w| w.set_en(true));

        let res = poll_fn(|cx| {
            WAKER.register(cx.waker());
            let err = ERRORS.load(Ordering::Relaxed);
            if err != 0 {
                return Poll::Ready(Err(decode_errors(err)));
            }
            if EVENTS.load(Ordering::Relaxed) & EVT_EC_DONE != 0 {
                return Poll::Ready(Ok(()));
            }
            Poll::Pending
        })
        .await;

        // Stop the epoch controller and clear its pipeline & configuration,
        // matching ST's `ATON_DISABLE_CLR_CONFCLR`. ST polls indefinitely;
        // retain the same register sequence but guard the polls so a wedged
        // unit is reported instead of blocking the entire executor forever.
        const TEARDOWN_SPIN_LIMIT: u32 = 1_000_000;
        let mut teardown_error = None;
        pac::NPU.epochctrl().ctrl().write(|w| w.set_clr(true));
        let mut spins = 0;
        while pac::NPU.epochctrl().ctrl().read().clr() {
            spins += 1;
            if spins == TEARDOWN_SPIN_LIMIT {
                teardown_error = Some(Error::EpochControllerTeardown(pac::NPU.epochctrl().ctrl().read().0));
                break;
            }
        }
        if teardown_error.is_none() {
            pac::NPU.epochctrl().ctrl().write(|w| w.set_confclr(true));
            spins = 0;
            while pac::NPU.epochctrl().ctrl().read().confclr() {
                spins += 1;
                if spins == TEARDOWN_SPIN_LIMIT {
                    teardown_error = Some(Error::EpochControllerTeardown(pac::NPU.epochctrl().ctrl().read().0));
                    break;
                }
            }
        }

        // Re-mask the epoch event and restore the OR-mask (the IRQ handler
        // fully masks the line after an error).
        pac::NPU
            .intctrl()
            .intandmsk(0)
            .write_value(pac::npu::regs::Intstatus(0xFFFF_FFFF));
        pac::NPU
            .intctrl()
            .intormsk(0)
            .write_value(pac::npu::regs::Intstatus(INT_STRENG_EVT_MASK));

        teardown_error.map_or(res, Err)
    }

    /// Run a network: execute a list of epoch blocks in order, awaiting each
    /// hardware blob and invoking the software callbacks in between — the
    /// equivalent of looping `LL_ATON_RT_RunEpochBlock()` until
    /// `LL_ATON_RT_DONE`.
    ///
    /// Stops at the first hardware error.
    pub async fn run_network(&mut self, epochs: &[EpochBlock<'_>]) -> Result<(), Error> {
        for eb in epochs {
            if let Some(f) = eb.start {
                f();
            }
            if let Some(blob) = eb.blob {
                self.run_epoch_blob(blob).await?;
            }
            if let Some(f) = eb.end {
                f();
            }
        }
        Ok(())
    }
}

impl<'d, T: Instance> Drop for Npu<'d, T> {
    fn drop(&mut self) {
        T::Interrupt::disable();

        // LL_ATON_DeInit: interrupt controller, bus interfaces, clocks.
        pac::NPU.intctrl().ctrl().write_value(pac::npu::regs::IntctrlCtrl(0));
        for i in 0..BUSIF_COUNT {
            pac::NPU.busif(i).ctrl().write_value(pac::npu::regs::BusifCtrl(0));
        }
        pac::NPU.clkctrl().agates0().write_value(pac::npu::regs::Agates(0));
        pac::NPU.clkctrl().agates1().write_value(pac::npu::regs::Agates(0));
        pac::NPU.clkctrl().bgates().write_value(pac::npu::regs::Bgates(0));
        pac::NPU.clkctrl().ctrl().write_value(pac::npu::regs::ClkctrlCtrl(0));

        // Gate the NPU kernel clock.
        pac::RCC.ahb5encr().write(|w| w.set_npuenc(true));
    }
}

trait SealedInstance {}

/// NPU instance.
#[allow(private_bounds)]
pub trait Instance: SealedInstance + PeripheralType + 'static + Send {
    /// Interrupt for this instance (ATON interrupt line 0).
    type Interrupt: interrupt::typelevel::Interrupt;
}

foreach_interrupt! {
    (NPU0) => {
        impl SealedInstance for crate::peripherals::NPU {}

        impl Instance for crate::peripherals::NPU {
            type Interrupt = crate::interrupt::typelevel::NPU0;
        }
    };
}
