// Shared touch-project config code generation for build scripts.

use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

pub fn touch_project_dir(manifest_dir: &Path) -> PathBuf {
    env::var("TOUCH_PROJECT")
        .map(|name| manifest_dir.join("../touch-projects").join(name))
        .unwrap_or_else(|_| manifest_dir.join("../touch-projects/Demo"))
}

pub fn generate_touch_config(manifest_dir: &Path, out_dir: &Path) {
    let project = touch_project_dir(manifest_dir);
    let hall_path = project.join("hall_config.json");
    let can_path = project.join("can_config.json");

    println!("cargo:rerun-if-changed={}", hall_path.display());
    println!("cargo:rerun-if-changed={}", can_path.display());
    println!("cargo:rerun-if-env-changed=TOUCH_PROJECT");

    let hall_json: serde_json::Value =
        serde_json::from_str(&fs::read_to_string(&hall_path).expect("read hall_config.json"))
            .expect("parse hall_config.json");
    let can_json: serde_json::Value =
        serde_json::from_str(&fs::read_to_string(&can_path).expect("read can_config.json"))
            .expect("parse can_config.json");

    let fields = hall_json["fields"].as_array().expect("fields array");
    let field_count = fields.len();
    let button_count = field_count * 3 + 3;

    let ui = &hall_json["ui"];
    let display_width: u16 = env::var("HALL_DISPLAY_WIDTH")
        .ok()
        .and_then(|v| v.parse().ok())
        .or_else(|| hall_json["display_width"].as_u64().map(|v| v as u16))
        .unwrap_or(800);
    let display_height: u16 = env::var("HALL_DISPLAY_HEIGHT")
        .ok()
        .and_then(|v| v.parse().ok())
        .or_else(|| hall_json["display_height"].as_u64().map(|v| v as u16))
        .unwrap_or(480);

    let mut rust = String::new();
    writeln!(rust, "// @generated by build.rs — do not edit").unwrap();
    writeln!(rust, "pub const DISPLAY_WIDTH: u16 = {display_width};").unwrap();
    writeln!(rust, "pub const DISPLAY_HEIGHT: u16 = {display_height};").unwrap();
    writeln!(rust, "pub const FIELD_COUNT: usize = {field_count};").unwrap();
    writeln!(rust, "pub const BUTTON_COUNT: usize = {button_count};").unwrap();
    writeln!(rust, "pub const GROUP_BUTTON_BASE: u8 = {};", field_count * 3).unwrap();
    writeln!(rust).unwrap();

    writeln!(
        rust,
        "pub const APP_TITLE: &str = {:?};",
        hall_json["app_title"].as_str().unwrap_or("")
    )
    .unwrap();
    writeln!(
        rust,
        "pub const PAGE_TITLE_PREFIX: &str = {:?};",
        hall_json["page_title_prefix"].as_str().unwrap_or("")
    )
    .unwrap();
    writeln!(
        rust,
        "pub const HALL_NAME: &str = {:?};",
        hall_json["hall_name"].as_str().unwrap_or("")
    )
    .unwrap();
    writeln!(
        rust,
        "pub const OFF_LABEL: &str = {:?};",
        ui["off_label"].as_str().unwrap_or("")
    )
    .unwrap();
    writeln!(
        rust,
        "pub const ALL_PREFIX: &str = {:?};",
        ui["all_prefix"].as_str().unwrap_or("")
    )
    .unwrap();
    writeln!(
        rust,
        "pub const LUX_SUFFIX: &str = {:?};",
        ui["lux_suffix"].as_str().unwrap_or("")
    )
    .unwrap();
    writeln!(
        rust,
        "pub const CENTRAL_OFF_LABEL: &str = {:?};",
        ui["central_off_label"].as_str().unwrap_or("")
    )
    .unwrap();
    writeln!(
        rust,
        "pub const GROUP_EYEBROW: &str = {:?};",
        ui["group_eyebrow"].as_str().unwrap_or("")
    )
    .unwrap();
    writeln!(
        rust,
        "pub const ALL_FIELDS_HEADING: &str = {:?};",
        ui["all_fields_heading"].as_str().unwrap_or("")
    )
    .unwrap();
    writeln!(
        rust,
        "pub const SUMMARY_READY: &str = {:?};",
        ui["summary_ready"].as_str().unwrap_or("Lichtsteuerung bereit")
    )
    .unwrap();
    writeln!(
        rust,
        "pub const TRIBUNE_EYEBROW: &str = {:?};",
        ui["tribune_eyebrow"].as_str().unwrap_or("")
    )
    .unwrap();
    writeln!(
        rust,
        "pub const FIELD_EYEBROW: &str = {:?};",
        ui["field_eyebrow"].as_str().unwrap_or("")
    )
    .unwrap();
    writeln!(rust).unwrap();

    writeln!(rust, "pub struct FieldLayout {{").unwrap();
    writeln!(rust, "    pub id: &'static str,").unwrap();
    writeln!(rust, "    pub label: &'static str,").unwrap();
    writeln!(rust, "    pub eyebrow: &'static str,").unwrap();
    writeln!(rust, "    pub default_lux: u16,").unwrap();
    writeln!(rust, "    pub button_base: u8,").unwrap();
    writeln!(rust, "}}").unwrap();
    writeln!(rust).unwrap();

    writeln!(rust, "pub const FIELDS: [FieldLayout; FIELD_COUNT] = [").unwrap();
    for (i, field) in fields.iter().enumerate() {
        writeln!(
            rust,
            "    FieldLayout {{ id: {:?}, label: {:?}, eyebrow: {:?}, default_lux: {}, button_base: {} }},",
            field["id"].as_str().unwrap_or(""),
            field["label"].as_str().unwrap_or(""),
            field["eyebrow"].as_str().unwrap_or(""),
            field["default_lux"].as_u64().unwrap_or(0) as u16,
            i * 3,
        )
        .unwrap();
    }
    writeln!(rust, "];").unwrap();
    writeln!(rust).unwrap();

    writeln!(rust, "pub const BUTTON_TOKENS: [&str; BUTTON_COUNT] = [").unwrap();
    for field in fields {
        let id = field["id"].as_str().unwrap_or("");
        writeln!(rust, "    {:?},", format!("field:{id}:500")).unwrap();
        writeln!(rust, "    {:?},", format!("field:{id}:300")).unwrap();
        writeln!(rust, "    {:?},", format!("field:{id}:0")).unwrap();
    }
    writeln!(rust, "    \"group:play-fields:500\",").unwrap();
    writeln!(rust, "    \"group:play-fields:300\",").unwrap();
    writeln!(rust, "    \"group:all-fields:0\",").unwrap();
    writeln!(rust, "];").unwrap();
    writeln!(rust).unwrap();

    let enabled = can_json["enabled"].as_bool().unwrap_or(true);
    let channel = can_json["channel"].as_str().unwrap_or("can0");
    let baud = can_json["baud"].as_u64().unwrap_or(500_000) as u32;
    let tx_id = can_json["tx_id"].as_u64().unwrap_or(512) as u16;
    let tx_endian = can_json["tx_endian"].as_str().unwrap_or("little");
    let command_repeat_ms = can_json["command_repeat_ms"].as_u64().unwrap_or(25);
    let long_press_ms = can_json["long_press_ms"].as_u64().unwrap_or(800);
    let recv_timeout_ms = (can_json["recv_timeout"].as_f64().unwrap_or(0.2) * 1000.0).round() as u64;
    let rx_debounce_ms = can_json["rx_debounce_ms"].as_u64().unwrap_or(50);
    let rx_poll_ms = if rx_debounce_ms == 0 {
        recv_timeout_ms
    } else {
        recv_timeout_ms.min((rx_debounce_ms / 2).max(10))
    };
    let websocket_enabled = can_json["websocket_enabled"].as_bool().unwrap_or(false);
    let websocket_port = can_json["websocket_port"].as_u64().unwrap_or(63150) as u16;
    let touch_websocket_enabled = can_json["touch_websocket_enabled"].as_bool().unwrap_or(false);
    let touch_websocket_port = can_json["touch_websocket_port"].as_u64().unwrap_or(63151) as u16;
    let minp = can_json["minp"].as_array().expect("minp array");
    let minp_level_on_even = can_json["minp_level_on_even"].as_bool().unwrap_or(true);
    let state_script_name = can_json["state_script"].as_str().unwrap_or("");
    let state_script_path = project.join(state_script_name);
    let (state_script_enabled, state_script) = if state_script_name.is_empty() {
        (false, String::new())
    } else {
        println!("cargo:rerun-if-changed={}", state_script_path.display());
        let script = fs::read_to_string(&state_script_path)
            .unwrap_or_else(|_| panic!("read state script {}", state_script_path.display()));
        (true, script)
    };

    writeln!(rust, "pub const CAN_ENABLED: bool = {enabled};").unwrap();
    writeln!(rust, "pub const CAN_CHANNEL: &str = {channel:?};").unwrap();
    writeln!(rust, "pub const CAN_BAUD: u32 = {baud};").unwrap();
    writeln!(rust, "pub const CAN_TX_ID: u16 = {tx_id};").unwrap();
    writeln!(rust, "pub const CAN_TX_LITTLE_ENDIAN: bool = {};", tx_endian == "little").unwrap();
    writeln!(rust, "pub const CAN_COMMAND_REPEAT_MS: u64 = {command_repeat_ms};").unwrap();
    writeln!(rust, "pub const LONG_PRESS_MS: u64 = {long_press_ms};").unwrap();
    writeln!(rust, "pub const CAN_RECV_TIMEOUT_MS: u64 = {recv_timeout_ms};").unwrap();
    writeln!(rust, "pub const CAN_RX_DEBOUNCE_MS: u64 = {rx_debounce_ms};").unwrap();
    writeln!(rust, "pub const CAN_RX_POLL_MS: u64 = {rx_poll_ms};").unwrap();
    writeln!(rust, "pub const MINP_LEVEL_ON_EVEN: bool = {minp_level_on_even};").unwrap();
    writeln!(rust, "pub const CAN_WEBSOCKET_ENABLED: bool = {websocket_enabled};").unwrap();
    writeln!(rust, "pub const CAN_WEBSOCKET_PORT: u16 = {websocket_port};").unwrap();
    writeln!(rust, "pub const CAN_TOUCH_WEBSOCKET_ENABLED: bool = {touch_websocket_enabled};").unwrap();
    writeln!(rust, "pub const CAN_TOUCH_WEBSOCKET_PORT: u16 = {touch_websocket_port};").unwrap();
    writeln!(rust, "pub const MINP_COUNT: usize = {};", minp.len()).unwrap();
    writeln!(rust, "pub const MINP_RX_ID: u16 = {};", minp[0][0].as_u64().unwrap_or(645) as u16)
        .unwrap();
    writeln!(rust).unwrap();

    writeln!(rust, "pub struct MinpEntry {{").unwrap();
    writeln!(rust, "    pub can_id: u16,").unwrap();
    writeln!(rust, "    pub active_value: u8,").unwrap();
    writeln!(rust, "    pub byte_index: u8,").unwrap();
    writeln!(rust, "    pub bit_index: u8,").unwrap();
    writeln!(rust, "}}").unwrap();
    writeln!(rust).unwrap();
    writeln!(rust, "pub const MINP: [MinpEntry; MINP_COUNT] = [").unwrap();
    for entry in minp {
        let arr = entry.as_array().expect("minp tuple");
        writeln!(
            rust,
            "    MinpEntry {{ can_id: {}, active_value: {}, byte_index: {}, bit_index: {} }},",
            arr[0].as_u64().unwrap_or(0) as u16,
            arr[1].as_u64().unwrap_or(0) as u8,
            arr[2].as_u64().unwrap_or(0) as u8,
            arr[3].as_u64().unwrap_or(0) as u8,
        )
        .unwrap();
    }
    writeln!(rust, "];").unwrap();
    writeln!(rust).unwrap();
    writeln!(rust, "pub const STATE_SCRIPT_ENABLED: bool = {state_script_enabled};").unwrap();
    writeln!(rust, "pub const STATE_SCRIPT: &str = {:?};", state_script).unwrap();

    fs::write(out_dir.join("touch_config.rs"), rust).expect("write touch_config.rs");
}
