//! Auto-generate the peripheral / interrupt singleton declarations for
//! `embassy-silabs` by walking `silabs_metapac::metadata::METADATA`.
//!
//! Mirrors `embassy-stm32/build.rs`'s approach (and the wider
//! embassy-rs / `*-metapac` pattern):
//!
//! - Read the per-chip metadata exposed by `silabs-metapac` once the
//!   chip's Cargo feature is enabled.
//! - For every peripheral instance, emit a singleton in
//!   `embassy_hal_internal::peripherals_definition!{…}` (so the type
//!   exists) and `embassy_hal_internal::peripherals_struct!{…}` (so
//!   `init()` returns it in `Peripherals`).
//! - The chosen time-driver timer (`time-driver-timer0`, etc.) is
//!   present in `peripherals_definition!` but skipped from
//!   `peripherals_struct!` — the time driver owns it.
//! - Emit `interrupt_mod!{…}` for every NVIC vector the chip exposes.
//! - GPIO pins are not yet in the PAC metadata. Series 2 has a
//!   stable port-A..D / 16 pins-per-port layout — hard-code those
//!   here until the data pipeline grows a pin extraction stage.
//! - Emit `cargo:rustc-cfg=silabs_series_<N>_config="<M>"` from the
//!   chip's `_SILICON_LABS_32B_SERIES_<N>_CONFIG_<M>` so HAL source can
//!   gate per-family erratas with
//!   `#[cfg(silabs_series_2_config = "...")]`.
//!
//! The generated file lives at `$OUT_DIR/_generated.rs` and is included
//! from `src/lib.rs` via `include!(concat!(env!("OUT_DIR"), "/_generated.rs"))`.

use std::collections::BTreeSet;
use std::fmt::Write as _;
use std::path::PathBuf;
use std::{env, fs};

use silabs_metapac::metadata::METADATA;

fn main() {
    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR not set"));
    let out_path = out_dir.join("_generated.rs");

    let mut out = String::new();
    out.push_str("// Generated by embassy-silabs/build.rs. Do not edit.\n\n");

    // Singleton names: peripheral instances (filtered to those worth
    // exposing) followed by GPIO pins.
    // 1. Peripheral instances.
    let mut singletons: Vec<String> = Vec::new();
    for p in METADATA.peripherals {
        if skip_peripheral_kind(p.kind) {
            continue;
        }
        singletons.push(p.name.to_string());
    }

    // 2. GPIO pins. Series 2 layout is ports A..D × 16 pins each. The
    //    largest currently-supported chip (EFR32MG26 IM68) exposes all
    //    of these; smaller packages physically bond fewer, but the
    //    silicon block is uniform — keeping the full set in the type
    //    system just means a few unused singletons on smaller parts.
    if METADATA.peripherals.iter().any(|p| p.name == "GPIO") {
        for port in &['A', 'B', 'C', 'D'] {
            for pin in 0..16 {
                singletons.push(format!("P{port}{pin:02}"));
            }
        }
    }

    // Sort for deterministic output. Singletons are independent so order
    // doesn't matter functionally, but stable order keeps build-script
    // diffs readable across regenerations.
    singletons.sort();
    singletons.dedup();

    // Handle time-driver-XXXX features.
    let time_driver = match env::vars()
        .map(|(a, _)| a)
        .filter(|x| x.starts_with("CARGO_FEATURE_TIME_DRIVER_"))
        .get_one()
    {
        Ok(x) => Some(
            x.strip_prefix("CARGO_FEATURE_TIME_DRIVER_")
                .unwrap()
                .to_ascii_lowercase(),
        ),
        Err(GetOneError::None) => None,
        Err(GetOneError::Multiple) => panic!("Multiple time-driver-xxx Cargo features enabled"),
    };

    let time_driver_singleton = match time_driver.as_ref().map(|x| x.as_ref()) {
        None => "",
        Some("timer0") => "TIMER0",
        Some("timer1") => "TIMER1",
        Some("any") => ["TIMER0", "TIMER1"]
            .iter()
            .find(|tim| singletons.contains(&tim.to_string()))
            .expect("time-driver-any requested, but the chip doesn't have TIMER0 or TIMER1."),
        _ => panic!("unknown time_driver {:?}", time_driver),
    };

    if !time_driver_singleton.is_empty() {
        println!(
            "cargo:rustc-cfg=time_driver_{}",
            time_driver_singleton.to_ascii_lowercase()
        );
    }
    for tim in ["timer0", "timer1"] {
        println!("cargo:rustc-check-cfg=cfg(time_driver_{tim})");
    }

    // Emit peripherals_definition! / peripherals_struct!.
    writeln!(out, "embassy_hal_internal::peripherals_definition!(").unwrap();
    for s in &singletons {
        writeln!(out, "    {s},").unwrap();
    }
    writeln!(out, ");\n").unwrap();

    writeln!(out, "embassy_hal_internal::peripherals_struct!(").unwrap();
    for s in &singletons {
        if s == time_driver_singleton {
            // Owned by the time driver — keep the type, drop the field.
            continue;
        }
        writeln!(out, "    {s},").unwrap();
    }
    writeln!(out, ");\n").unwrap();

    // Emit interrupt_mod!. Dedup by name — METADATA.interrupts is
    // already deduped in the generator, but defensive in case that ever
    // changes.
    let mut seen: BTreeSet<&str> = BTreeSet::new();
    let mut irq_names: Vec<&str> = Vec::new();
    for i in METADATA.interrupts {
        if seen.insert(i.name) {
            irq_names.push(i.name);
        }
    }
    writeln!(out, "embassy_hal_internal::interrupt_mod!(").unwrap();
    for name in &irq_names {
        writeln!(out, "    {name},").unwrap();
    }
    writeln!(out, ");\n").unwrap();

    if !time_driver_singleton.is_empty() {
        if !METADATA.interrupts.iter().any(|i| i.name == time_driver_singleton) {
            panic!("Tried to select {time_driver_singleton}, which is not available on this device");
        }
        writeln!(out).unwrap();
        writeln!(out, "#[cfg(feature = \"rt\")]").unwrap();
        writeln!(out, "#[interrupt]").unwrap();
        writeln!(out, "fn {time_driver_singleton}() {{").unwrap();
        writeln!(out, "    crate::time_driver::get_driver().on_interrupt();").unwrap();
        writeln!(out, "}}").unwrap();
    }

    fs::write(&out_path, &out).expect("write _generated.rs");

    // Emit silabs_series + silabs_series_<N>_config cfg flags. Mirrors
    // the SDK's `_SILICON_LABS_32B_SERIES_<N>` and
    // `_SILICON_LABS_32B_SERIES_<N>_CONFIG_<M>` macros — HAL source
    // gates erratas and per-generation register code with
    // `#[cfg(silabs_series_2_config = "6")]` etc.
    use silabs_metapac::metadata::Series;
    let (series, cfg) = match METADATA.series {
        Series::Series2(n) => (2u8, n as u16),
        Series::Series3(n) => (3u8, n),
    };
    println!("cargo:rustc-cfg=silabs_series=\"{series}\"");
    println!("cargo:rustc-cfg=silabs_series_{series}_config=\"{cfg}\"");
    // Declare the cfg names so `unexpected_cfgs` lint doesn't fire on
    // downstream code that uses these gates.
    println!("cargo:rustc-check-cfg=cfg(silabs_series, values(\"2\", \"3\"))");
    println!(
        "cargo:rustc-check-cfg=cfg(silabs_series_2_config, values(\"1\", \"2\", \"3\", \"4\", \"5\", \"6\", \"7\", \"8\", \"9\"))"
    );
    println!("cargo:rustc-check-cfg=cfg(silabs_series_3_config, values(\"301\"))");

    println!("cargo:rerun-if-changed=build.rs");
}

/// Skip kinds that don't make sense as embassy peripheral singletons.
/// Conservative — only DEVINFO is dropped (read-only chip identity, not
/// a controllable peripheral). Security / mailbox / config peripherals
/// stay in so HALs can grow drivers for them without revisiting this list.
fn skip_peripheral_kind(kind: &str) -> bool {
    matches!(kind, "devinfo")
}

enum GetOneError {
    None,
    Multiple,
}

trait IteratorExt: Iterator {
    fn get_one(self) -> Result<Self::Item, GetOneError>;
}

impl<T: Iterator> IteratorExt for T {
    fn get_one(mut self) -> Result<Self::Item, GetOneError> {
        match self.next() {
            None => Err(GetOneError::None),
            Some(res) => match self.next() {
                Some(_) => Err(GetOneError::Multiple),
                None => Ok(res),
            },
        }
    }
}
