//! Auto-generate the peripheral / interrupt singleton declarations for
//! `embassy-silabs` by walking `silabs_metapac::metadata::METADATA`.
//!
//! Mirrors `embassy-stm32/build.rs`'s approach (and the wider
//! embassy-rs / `*-metapac` pattern):
//!
//! - Read the per-chip metadata exposed by `silabs-metapac` once the
//!   chip's Cargo feature is enabled.
//! - For every peripheral instance, emit a singleton in
//!   `embassy_hal_internal::peripherals_definition!{…}` (so the type
//!   exists) and `embassy_hal_internal::peripherals_struct!{…}` (so
//!   `init()` returns it in `Peripherals`).
//! - The chosen time-driver timer (`time-driver-timer0`, etc.) is
//!   present in `peripherals_definition!` but skipped from
//!   `peripherals_struct!` — the time driver owns it.
//! - Emit `interrupt_mod!{…}` for every NVIC vector the chip exposes.
//! - GPIO pins are not yet in the PAC metadata. Series 2 has a
//!   stable port-A..D / 16 pins-per-port layout — hard-code those
//!   here until the data pipeline grows a pin extraction stage.
//! - Emit `cargo:rustc-cfg=silabs_series_<N>_config="<M>"` from the
//!   chip's `_SILICON_LABS_32B_SERIES_<N>_CONFIG_<M>` so HAL source can
//!   gate per-family erratas with
//!   `#[cfg(silabs_series_2_config = "...")]`.
//!
//! The generated file lives at `$OUT_DIR/_generated.rs` and is included
//! from `src/lib.rs` via `include!(concat!(env!("OUT_DIR"), "/_generated.rs"))`.

use std::collections::BTreeSet;
use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::PathBuf;

use silabs_metapac::metadata::METADATA;

fn main() {
    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR not set"));
    let out_path = out_dir.join("_generated.rs");

    let mut out = String::new();
    out.push_str("// Generated by embassy-silabs/build.rs. Do not edit.\n\n");

    // Singleton names: peripheral instances (filtered to those worth
    // exposing) followed by GPIO pins.
    // 1. Peripheral instances.
    let mut singletons: Vec<String> = Vec::new();
    for p in METADATA.peripherals {
        if skip_peripheral_kind(p.kind) {
            continue;
        }
        singletons.push(p.name.to_string());
    }

    // 2. GPIO pins. Series 2 layout is ports A..D × 16 pins each. The
    //    largest currently-supported chip (EFR32MG26 IM68) exposes all
    //    of these; smaller packages physically bond fewer, but the
    //    silicon block is uniform — keeping the full set in the type
    //    system just means a few unused singletons on smaller parts.
    if METADATA.peripherals.iter().any(|p| p.name == "GPIO") {
        for port in &['A', 'B', 'C', 'D'] {
            for pin in 0..16 {
                singletons.push(format!("P{port}{pin:02}"));
            }
        }
    }

    // Sort for deterministic output. Singletons are independent so order
    // doesn't matter functionally, but stable order keeps build-script
    // diffs readable across regenerations.
    singletons.sort();
    singletons.dedup();

    // Pick the time-driver singleton. The Cargo feature is exclusive
    // (`time-driver-timer0` and `time-driver-any`; `_time-driver` is
    // internal). TIMER0 is the only driver implementation today.
    let time_driver_singleton = pick_time_driver(&singletons);

    // Emit peripherals_definition! / peripherals_struct!.
    writeln!(out, "embassy_hal_internal::peripherals_definition!(").unwrap();
    for s in &singletons {
        writeln!(out, "    {s},").unwrap();
    }
    writeln!(out, ");\n").unwrap();

    writeln!(out, "embassy_hal_internal::peripherals_struct!(").unwrap();
    for s in &singletons {
        if Some(s.as_str()) == time_driver_singleton.as_deref() {
            // Owned by the time driver — keep the type, drop the field.
            continue;
        }
        writeln!(out, "    {s},").unwrap();
    }
    writeln!(out, ");\n").unwrap();

    // Emit interrupt_mod!. Dedup by name — METADATA.interrupts is
    // already deduped in the generator, but defensive in case that ever
    // changes.
    let mut seen: BTreeSet<&str> = BTreeSet::new();
    let mut irq_names: Vec<&str> = Vec::new();
    for i in METADATA.interrupts {
        if seen.insert(i.name) {
            irq_names.push(i.name);
        }
    }
    writeln!(out, "embassy_hal_internal::interrupt_mod!(").unwrap();
    for name in &irq_names {
        writeln!(out, "    {name},").unwrap();
    }
    writeln!(out, ");").unwrap();

    fs::write(&out_path, &out).expect("write _generated.rs");

    // Emit silabs_series + silabs_series_<N>_config cfg flags. Mirrors
    // the SDK's `_SILICON_LABS_32B_SERIES_<N>` and
    // `_SILICON_LABS_32B_SERIES_<N>_CONFIG_<M>` macros — HAL source
    // gates erratas and per-generation register code with
    // `#[cfg(silabs_series_2_config = "6")]` etc.
    use silabs_metapac::metadata::Series;
    let (series, cfg) = match METADATA.series {
        Series::Series2(n) => (2u8, n as u16),
        Series::Series3(n) => (3u8, n),
    };
    println!("cargo:rustc-cfg=silabs_series=\"{series}\"");
    println!("cargo:rustc-cfg=silabs_series_{series}_config=\"{cfg}\"");
    // Declare the cfg names so `unexpected_cfgs` lint doesn't fire on
    // downstream code that uses these gates.
    println!("cargo:rustc-check-cfg=cfg(silabs_series, values(\"2\", \"3\"))");
    println!(
        "cargo:rustc-check-cfg=cfg(silabs_series_2_config, values(\"1\", \"2\", \"3\", \"4\", \"5\", \"6\", \"7\", \"8\", \"9\"))"
    );
    println!("cargo:rustc-check-cfg=cfg(silabs_series_3_config, values(\"301\"))");

    println!("cargo:rerun-if-changed=build.rs");
}

/// Skip kinds that don't make sense as embassy peripheral singletons.
/// Conservative — only DEVINFO is dropped (read-only chip identity, not
/// a controllable peripheral). Security / mailbox / config peripherals
/// stay in so HALs can grow drivers for them without revisiting this list.
fn skip_peripheral_kind(kind: &str) -> bool {
    matches!(kind, "devinfo")
}

/// Resolve the `time-driver-*` Cargo features to a singleton name.
fn pick_time_driver(singletons: &[String]) -> Option<String> {
    if env::var_os("CARGO_FEATURE_TIME_DRIVER_TIMER0").is_some() {
        return Some("TIMER0".to_string());
    }
    if env::var_os("CARGO_FEATURE_TIME_DRIVER_ANY").is_some() {
        // Pick the lowest-numbered TIMER present on this chip.
        return singletons.iter().find(|s| s.starts_with("TIMER")).cloned();
    }
    None
}
